export function accountUI(){const $=id=>document.getElementById(id);let current=null;
 const gate=document.createElement('div');gate.id='accountGate';gate.className='veil';gate.innerHTML='<section class="panel account-panel"><small>VIBE CITY / EXPEDITION ACCESS</small><h2>Enter the world.</h2><div id="accountFields"></div><form id="verifyForm" class="hidden"><p>Verify your email before entering the game. Existing characters stay with this account.</p><label>EMAIL<input id="verifyEmail" type="email" autocomplete="email" required></label><label class="toggle"><input id="verifyTerms" type="checkbox" required> I accept the <a href="/wiki/terms.html" target="_blank">Terms of Service</a>.</label><label class="toggle"><input id="verifyMarketing" type="checkbox"> Email me newsletters and marketing updates (optional).</label><button id="saveEmail">SAVE & SEND VERIFICATION</button></form><div id="verifyActions" class="hidden"><button id="resendVerification">RESEND EMAIL</button><button id="checkVerification">I VERIFIED MY EMAIL</button><button id="gateSignout">SIGN OUT</button></div><div id="accountFeedback" role="status"></div><p><a href="/wiki/privacy.html" target="_blank">Privacy notice</a> · <a href="https://wiki.vibe-city.net" target="_blank">Game wiki</a></p></section>';document.body.append(gate);$('accountFields').append($('accountForm'),$('accountError'));
 const fields=document.createElement('div');fields.innerHTML='<label>EMAIL (REQUIRED FOR SIGNUP)<input id="signupEmail" type="email" autocomplete="email"></label><label class="toggle"><input id="signupTerms" type="checkbox"> I accept the <a href="/wiki/terms.html" target="_blank">Terms of Service</a>.</label><label class="toggle"><input id="signupMarketing" type="checkbox"> Email me newsletters and marketing updates (optional).</label>';$('accountForm').querySelector('.account-actions').before(fields);
 function render(profile){current=profile;const verified=!!profile?.emailVerified&&profile?.termsVersion==='2026-09-16';gate.classList.toggle('hidden',verified);$('landing').classList.toggle('hidden',!verified);$('accountForm').classList.toggle('hidden',!!profile);$('verifyForm').classList.toggle('hidden',!profile||verified);$('verifyActions').classList.toggle('hidden',!profile||verified);$('characterPanel').classList.toggle('hidden',!profile);$('joinForm').classList.toggle('hidden',!verified);if(!profile)return;$('verifyEmail').value=profile.email||'';$('verifyTerms').checked=!!profile.termsVersion;$('verifyMarketing').checked=!!profile.marketing;$('accountName').textContent=profile.username;const selected=$('character').value||localStorage.getItem('vc-selected-character');$('character').replaceChildren(...profile.characters.map(c=>{const option=document.createElement('option');option.value=c.id;option.textContent=c.name;return option;}));if(profile.characters.some(c=>c.id===selected))$('character').value=selected;$('createCharacter').disabled=profile.characters.length>=3;$('characterCount').textContent=`${profile.characters.length} / 3 characters`;$('enter').disabled=!verified||!profile.characters.length;}
 async function refresh(){const r=await fetch('/api/account',{cache:'no-store'});if(!r.ok)throw Error('Account service unavailable.');const data=await r.json();render(data.profile);return data;}
 async function request(body){const r=await fetch('/api/account',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(data.error||'Account request failed.');render(data.profile);$('accountError').textContent='';$('accountFeedback').textContent=data.notice||data.message||'';return data;}
 async function auth(action){$('loginAccount').disabled=$('registerAccount').disabled=true;try{await request({action,username:$('username').value,password:$('password').value,email:$('signupEmail').value,terms:$('signupTerms').checked,marketing:$('signupMarketing').checked});$('password').value='';}catch(e){$('accountError').textContent=e.message;}finally{$('loginAccount').disabled=$('registerAccount').disabled=false;}}
 $('loginAccount').onclick=()=>auth('login');$('registerAccount').onclick=()=>auth('register');$('accountForm').onsubmit=e=>{e.preventDefault();auth('login');};$('characterForm').onsubmit=async e=>{e.preventDefault();try{await request({action:'character',name:$('characterName').value});$('character').selectedIndex=$('character').options.length-1;localStorage.setItem('vc-selected-character',$('character').value);$('characterName').value='';}catch(e){$('accountError').textContent=e.message;}};
 const safe=fn=>async()=>{try{await fn();}catch(e){$('accountFeedback').textContent=e.message;}};
 $('verifyForm').onsubmit=e=>{e.preventDefault();safe(()=>request({action:'enroll',email:$('verifyEmail').value,terms:$('verifyTerms').checked,marketing:$('verifyMarketing').checked}))();};$('resendVerification').onclick=safe(()=>request({action:'resend'}));$('checkVerification').onclick=safe(refresh);
 $('logoutAccount').onclick=$('gateSignout').onclick=safe(async()=>{await request({action:'logout'});location.reload();});$('character').onchange=()=>localStorage.setItem('vc-selected-character',$('character').value);
 const prefs=document.createElement('label');prefs.className='toggle';const checkbox=document.createElement('input');checkbox.type='checkbox';prefs.append(checkbox,document.createTextNode('Newsletter and marketing emails'));$('characterPanel').append(prefs);checkbox.onchange=safe(()=>request({action:'preferences',marketing:checkbox.checked}));
 const code=new URL(location.href).searchParams.get('verify');(async()=>{try{if(code){await request({action:'verify',code});history.replaceState({},'',location.pathname);}await refresh();checkbox.checked=!!current?.marketing;}catch(e){$('accountFeedback').textContent=e.message;}})();
 return{profile:()=>current};}
