export function accountUI(){const $=id=>document.getElementById(id);let current=null;
function render(profile){current=profile;$('accountForm').classList.toggle('hidden',!!profile);$('characterPanel').classList.toggle('hidden',!profile);$('joinForm').classList.toggle('hidden',!profile);if(!profile)return;$('accountName').textContent=profile.username;const selected=$('character').value||localStorage.getItem('vc-selected-character');$('character').replaceChildren(...profile.characters.map(c=>{const option=document.createElement('option');option.value=c.id;option.textContent=c.name;return option;}));if(profile.characters.some(c=>c.id===selected))$('character').value=selected;$('createCharacter').disabled=profile.characters.length>=3;$('characterCount').textContent=`${profile.characters.length} / 3 characters`;$('enter').disabled=!profile.characters.length;}
async function request(body){const r=await fetch('/api/account',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(data.error||'Account request failed.');render(data.profile);$('accountError').textContent='';return data;}
async function auth(action){$('loginAccount').disabled=$('registerAccount').disabled=true;try{await request({action,username:$('username').value,password:$('password').value});$('password').value='';}catch(e){$('accountError').textContent=e.message;}finally{$('loginAccount').disabled=$('registerAccount').disabled=false;}}
$('loginAccount').onclick=()=>auth('login');$('registerAccount').onclick=()=>auth('register');$('accountForm').onsubmit=e=>{e.preventDefault();auth('login');};$('characterForm').onsubmit=async e=>{e.preventDefault();try{await request({action:'character',name:$('characterName').value});$('character').selectedIndex=$('character').options.length-1;$('characterName').value='';}catch(e){$('accountError').textContent=e.message;}};
$('logoutAccount').onclick=async()=>{try{await request({action:'logout'});location.reload();}catch(e){$('accountError').textContent=e.message;}};
$('character').onchange=()=>localStorage.setItem('vc-selected-character',$('character').value);
fetch('/api/account').then(r=>{if(!r.ok)throw Error();return r.json();}).then(d=>render(d.profile)).catch(()=>$('accountError').textContent='Account service unavailable. Refresh to retry.');
return{profile:()=>current};}
