export function accountUI(){const $=id=>document.getElementById(id),recoveryToken=new URL(location.href).searchParams.get('recover');let current=null,screen=recoveryToken?'reset':'form',checking=false;
 const gate=document.createElement('div');gate.id='accountGate';gate.className='veil';gate.innerHTML='<section class="panel account-panel"><small>VIBE CITY / EXPEDITION ACCESS</small><h2>Enter the world.</h2><div id="accountFields"></div><form id="verifyForm" class="hidden"><p>Verify your email before entering the game. Existing characters stay with this account.</p><label>EMAIL<input id="verifyEmail" type="email" autocomplete="email" required></label><label class="toggle"><input id="verifyTerms" type="checkbox" required> I accept the <a href="/wiki/terms.html" target="_blank">Terms of Service</a>.</label><label class="toggle"><input id="verifyMarketing" type="checkbox"> Email me newsletters and marketing updates (optional).</label><button id="saveEmail">SAVE & SEND VERIFICATION</button></form><div id="verifyActions" class="hidden"><button id="resendVerification">RESEND EMAIL</button><button id="checkVerification">I VERIFIED MY EMAIL</button><button id="gateSignout">SIGN OUT</button></div><div id="accountFeedback" role="status"></div><p><a href="/wiki/privacy.html" target="_blank">Privacy notice</a> · <a href="https://wiki.vibe-city.net" target="_blank">Game wiki</a></p></section>';document.body.append(gate);$('accountFields').append($('accountForm'),$('accountError'));
 const status=document.createElement('div');status.id='verificationStatus';status.className='hidden';status.innerHTML='<h2 id="verificationHeading"></h2><p id="verificationInstructions"></p><button id="continueVerification" class="hidden">CONTINUE TO VIBE CITY</button><button id="closeVerification">CLOSE THIS TAB</button><p id="closeVerificationHelp" role="status"></p><button id="changeVerificationEmail">CHANGE EMAIL</button>';gate.querySelector('#verifyForm').after(status);
 const recovery=document.createElement('div');recovery.id='recoveryPanel';recovery.innerHTML='<form id="recoveryForm" class="hidden"><h2>Recover your account.</h2><p>Enter the verified email on your account. The response is the same whether an account can receive a recovery message or not.</p><label for="recoveryEmail">EMAIL</label><input id="recoveryEmail" type="email" autocomplete="email" maxlength="254" required><div class="account-actions"><button id="requestRecovery">SEND RECOVERY LINK</button><button id="cancelRecovery" type="button">BACK TO SIGN IN</button></div><p id="recoveryStatus" class="hidden" role="status" tabindex="-1"></p><p id="recoveryRequestError" role="alert"></p></form><form id="resetForm" class="hidden"><h2>Set a new password.</h2><label for="newPassword">NEW PASSWORD</label><input id="newPassword" type="password" autocomplete="new-password" minlength="10" maxlength="128" required><label for="confirmPassword">CONFIRM NEW PASSWORD</label><input id="confirmPassword" type="password" autocomplete="new-password" minlength="10" maxlength="128" required><button id="resetPassword">RESET PASSWORD</button><p id="recoveryError" role="alert"></p></form>';status.after(recovery);
 const fields=document.createElement('div');fields.innerHTML='<label>EMAIL (REQUIRED FOR SIGNUP)<input id="signupEmail" type="email" autocomplete="email"></label><label class="toggle"><input id="signupTerms" type="checkbox"> I accept the <a href="/wiki/terms.html" target="_blank">Terms of Service</a>.</label><label class="toggle"><input id="signupMarketing" type="checkbox"> Email me newsletters and marketing updates (optional).</label>';$('accountForm').querySelector('.account-actions').before(fields);
 function render(profile){current=profile;if(screen==='waiting'&&profile?.emailVerified)screen='complete';const verified=!!profile?.emailVerified&&profile?.termsVersion==='2026-09-16';const showingStatus=screen==='waiting'||screen==='complete',showingRecovery=screen==='recovery'||screen==='reset';gate.classList.toggle('hidden',verified&&!showingStatus&&!showingRecovery);$('landing').classList.toggle('hidden',!verified||showingStatus||showingRecovery);$('accountForm').classList.toggle('hidden',!!profile||showingStatus||showingRecovery);$('verifyForm').classList.toggle('hidden',!profile||verified||showingStatus||showingRecovery);$('verifyActions').classList.toggle('hidden',!profile||verified||screen==='complete'||showingRecovery);$('recoveryForm').classList.toggle('hidden',screen!=='recovery');$('resetForm').classList.toggle('hidden',screen!=='reset');if(screen==='reset'&&document.activeElement!==$('newPassword'))$('newPassword').focus();status.classList.toggle('hidden',!showingStatus);gate.querySelector('.account-panel > h2').classList.toggle('hidden',showingStatus||showingRecovery);$('verificationHeading').textContent=screen==='complete'?'Email verified.':'Check your email.';$('verificationInstructions').textContent=screen==='complete'?'Your email is verified. Continue to Vibe City, or close this tab and return to your game tab.':`We sent a verification link to ${profile?.email||'your email address'}. Open it to finish signing up. You can close this tab, or leave it open—it will update automatically after verification. Check your spam folder if needed.`;$('continueVerification').classList.toggle('hidden',screen!=='complete');$('changeVerificationEmail').classList.toggle('hidden',screen!=='waiting');$('characterPanel').classList.toggle('hidden',!profile||showingRecovery);$('joinForm').classList.toggle('hidden',!verified||showingRecovery);if(!profile)return;$('verifyEmail').value=profile.email||'';$('verifyTerms').checked=!!profile.termsVersion;$('verifyMarketing').checked=!!profile.marketing;$('accountName').textContent=profile.username;const selected=$('character').value||localStorage.getItem('vc-selected-character');$('character').replaceChildren(...profile.characters.map(c=>{const option=document.createElement('option');option.value=c.id;option.textContent=c.name;return option;}));if(profile.characters.some(c=>c.id===selected))$('character').value=selected;$('createCharacter').disabled=profile.characters.length>=3;$('characterCount').textContent=`${profile.characters.length} / 3 characters`;$('enter').disabled=!verified||!profile.characters.length;}
 async function refresh(){const r=await fetch('/api/account',{cache:'no-store'});if(!r.ok)throw Error('Account service unavailable.');const data=await r.json();render(data.profile);return data;}
 async function request(body){const r=await fetch('/api/account',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(data.error||'Account request failed.');if(body.action==='verify')screen='complete';else if(['register','enroll','resend'].includes(body.action)&&!data.notice&&!data.profile?.emailVerified)screen='waiting';else if(body.action==='logout')screen='form';render(data.profile);$('accountError').textContent='';$('accountFeedback').textContent=data.notice||data.message||'';return data;}
 async function auth(action){$('loginAccount').disabled=$('registerAccount').disabled=true;try{await request({action,username:$('username').value,password:$('password').value,email:$('signupEmail').value,terms:$('signupTerms').checked,marketing:$('signupMarketing').checked});$('password').value='';}catch(e){$('accountError').textContent=e.message;}finally{$('loginAccount').disabled=$('registerAccount').disabled=false;}}
 $('loginAccount').onclick=()=>auth('login');$('registerAccount').onclick=()=>auth('register');$('accountForm').onsubmit=e=>{e.preventDefault();auth('login');};$('characterForm').onsubmit=async e=>{e.preventDefault();try{await request({action:'character',name:$('characterName').value});$('character').selectedIndex=$('character').options.length-1;localStorage.setItem('vc-selected-character',$('character').value);$('characterName').value='';}catch(e){$('accountError').textContent=e.message;}};
 $('forgotPassword').onclick=()=>{screen='recovery';render(current);$('recoveryEmail').focus();};$('cancelRecovery').onclick=()=>{screen='form';render(current);$('username').focus();};
 $('recoveryForm').onsubmit=async e=>{e.preventDefault();$('requestRecovery').disabled=true;$('recoveryRequestError').textContent='';$('recoveryStatus').classList.add('hidden');try{const data=await request({action:'recover',email:$('recoveryEmail').value});$('recoveryStatus').textContent=data.message;$('recoveryStatus').classList.remove('hidden');$('recoveryStatus').focus();}catch(error){$('recoveryRequestError').textContent=error.message;}finally{$('requestRecovery').disabled=false;}};
 $('resetForm').onsubmit=async e=>{e.preventDefault();$('recoveryError').textContent='';if($('newPassword').value!==$('confirmPassword').value){$('recoveryError').textContent='Passwords do not match.';$('confirmPassword').focus();return;}$('resetPassword').disabled=true;try{const data=await request({action:'reset',token:recoveryToken,password:$('newPassword').value});screen='form';history.replaceState({},'',location.pathname);$('newPassword').value=$('confirmPassword').value='';render(null);$('accountFeedback').textContent=data.message;$('username').focus();}catch(error){$('recoveryError').textContent=error.message;$('recoveryError').focus();}finally{$('resetPassword').disabled=false;}};
 const safe=fn=>async()=>{try{await fn();}catch(e){$('accountFeedback').textContent=e.message;}};
 $('verifyForm').onsubmit=e=>{e.preventDefault();safe(()=>request({action:'enroll',email:$('verifyEmail').value,terms:$('verifyTerms').checked,marketing:$('verifyMarketing').checked}))();};$('resendVerification').onclick=safe(()=>request({action:'resend'}));$('checkVerification').onclick=safe(refresh);
 $('continueVerification').onclick=()=>{screen='form';$('accountFeedback').textContent='';render(current);};$('changeVerificationEmail').onclick=()=>{screen='form';render(current);};$('closeVerification').onclick=()=>{window.close();$('closeVerificationHelp').textContent='If this tab stays open, close it using your browser’s tab close button.';};
 async function checkInBackground(){if(checking||screen!=='waiting'||document.hidden)return;checking=true;try{await refresh();}catch{}finally{checking=false;}}
 setInterval(checkInBackground,5000);window.addEventListener('focus',checkInBackground);document.addEventListener('visibilitychange',checkInBackground);
 $('logoutAccount').onclick=$('gateSignout').onclick=safe(async()=>{await request({action:'logout'});location.reload();});$('character').onchange=()=>localStorage.setItem('vc-selected-character',$('character').value);
 const prefs=document.createElement('label');prefs.className='toggle';const checkbox=document.createElement('input');checkbox.type='checkbox';prefs.append(checkbox,document.createTextNode('Newsletter and marketing emails'));$('characterPanel').append(prefs);checkbox.onchange=safe(()=>request({action:'preferences',marketing:checkbox.checked}));
 const code=new URL(location.href).searchParams.get('verify');(async()=>{try{if(code){await request({action:'verify',code});history.replaceState({},'',location.pathname);}await refresh();checkbox.checked=!!current?.marketing;}catch(e){$('accountFeedback').textContent=e.message;}})();
 return{profile:()=>current};}
