import {RESOURCES,RECIPES,itemCount} from '/shared/world.js';
import {itemIcon} from './item-icons.js';
const tools=['fabricator','cutter','flashlight','repair','rifle'],items=[...Object.keys(RESOURCES),...tools];
export function createBackpackUI({send,useTool}){
 const root=document.getElementById('backpack');root.innerHTML='<div class="pack-summary"><b id="packCount"></b><meter id="packFill" min="0" max="60"></meter></div><div class="pack-layout"><div id="packGrid" class="inventory-grid" aria-label="Backpack items"></div><section class="item-detail"><h3 id="packName">Select an item</h3><p id="packDescription"></p><div id="packItemActions"></div><label for="packBeltSlot">Belt slot</label><select id="packBeltSlot"></select><button id="packAssign">ASSIGN TO BELT</button><label for="packDropAmount">Drop quantity</label><input id="packDropAmount" type="number" min="1" max="60" value="1"><button id="packDrop">DROP STACK</button><p id="packHelp">Select an item to inspect it. Dropped resources can be picked up by other players.</p></section></div>';
 const $=id=>document.getElementById(id),slots=new Map();let player=null,selected='ferrite';const owned=item=>tools.includes(item)?!!(item==='flashlight'?player?.flashlightOwned:player?.[item]):(player?.inventory[item]||0)>0;
 for(let i=0;i<10;i++){const option=document.createElement('option');option.value=i;option.textContent=`${(i+1)%10}`;$('packBeltSlot').append(option);}
 function detail(){if(!player)return;const tool=tools.includes(selected),definition=RESOURCES[selected]||RECIPES[selected];$('packName').textContent=definition.name;$('packDescription').textContent=tool?RECIPES[selected].description:`${player.inventory[selected]||0} carried · ${selected==='ration'?'Ready to eat.':selected==='water'?'Ready to drink.':'Use for fabrication or store in a cargo locker.'}`;$('packAssign').disabled=!owned(selected)||(!tool&&!['water','ration'].includes(selected));$('packDrop').disabled=tool||!owned(selected);$('packDropAmount').disabled=tool;$('packDropAmount').max=String(player.inventory[selected]||1);$('packItemActions').replaceChildren();if(owned(selected)&&['fabricator','ration','water','flashlight','repair','rifle'].includes(selected)){const b=document.createElement('button');b.textContent=selected==='ration'?'EAT':selected==='water'?'DRINK':selected==='fabricator'?'EQUIP DRIVER':'USE';b.onclick=()=>{if(selected==='ration')send({type:'eat'});else if(selected==='water')send({type:'drink'});else if(selected==='flashlight')send({type:'light'});else useTool(selected);};$('packItemActions').append(b);}}
 for(const item of items){const b=document.createElement('button');b.className='inventory-slot';b.dataset.packItem=item;b.style.setProperty('--item-color',`#${(RESOURCES[item]?.color||0x90d5c6).toString(16).padStart(6,'0')}`);b.innerHTML=`${itemIcon(item)}<span class="slot-name"></span><b class="slot-count"></b>`;b.querySelector('.slot-name').textContent=(RESOURCES[item]||RECIPES[item]).name;b.onclick=b.onfocus=()=>{selected=item;for(const[key,slot]of slots)slot.classList.toggle('selected',key===selected);detail();};slots.set(item,b);$('packGrid').append(b);}
 $('packAssign').onclick=()=>send({type:'belt',slot:Number($('packBeltSlot').value),item:selected});$('packDrop').onclick=()=>send({type:'drop',item:selected,amount:Number($('packDropAmount').value)});
 function navigate(key){const active=document.activeElement,index=items.indexOf(active?.dataset.packItem);if(index<0)return false;if(key==='ArrowDown'&&index+4>=items.length){$('packBeltSlot').focus();return true;}if(key==='ArrowUp'&&index<4){document.getElementById('guideTab-backpack').focus();return true;}const delta={ArrowLeft:-1,ArrowRight:1,ArrowUp:-4,ArrowDown:4}[key];if(!delta)return false;slots.get(items[Math.max(0,Math.min(items.length-1,index+delta))])?.focus();return true;}
 root.addEventListener('keydown',e=>{if(navigate(e.key))e.preventDefault();});
 return{controller(input){return navigate(input.pressed[12]?'ArrowUp':input.pressed[13]?'ArrowDown':input.pressed[14]?'ArrowLeft':input.pressed[15]?'ArrowRight':'');},update(p){player=p;$('packCount').textContent=`${itemCount(p.inventory)} / 60 items`;$('packFill').value=itemCount(p.inventory);for(const[item,b]of slots){const n=tools.includes(item)?owned(item)?1:0:p.inventory[item]||0;b.classList.toggle('empty',!n);b.querySelector('.slot-count').textContent=tools.includes(item)?n?'✓':'—':n;b.setAttribute('aria-label',`${(RESOURCES[item]||RECIPES[item]).name}, ${tools.includes(item)?n?'available':'not crafted':`${n} carried`}`);}const focus=document.activeElement,inside=$('packItemActions').contains(focus);if(!inside)detail();}};
}
