import {resourceDeposits} from './resource-deposits.js';
import {depositKind} from '../shared/resource-deposits.js';
import {createMotionSampler} from './motion-sampling.js';
const motionSampler=createMotionSampler();
import {atmosphere,groundScatter} from './world-atmosphere.js';
import {loadFieldArt,fieldArtReady,fieldArtState,fieldModel,fieldResource,fieldProp,animateFieldModel} from './field-art.js';
import {RoundedBoxGeometry} from './vendor/geometries/RoundedBoxGeometry.js';
import {createStorageUI} from './storage-ui.js';
import {contextAction} from '/shared/context-action.js';
import {sunlight} from '/shared/sunlight.js';
import {adminTools} from './admin-tools.js';
import {BUTTONS,DEFAULT_BINDINGS,ACTION_LABELS,createGamepadReader,loadBindings} from './gamepad.js';
import {snapBuild} from '/shared/build-grid.js';
import {expeditionUI} from './expedition-ui.js';
import {planetRenderer,vehicleRenderer,vector,orient,fromPoint,coralFluxDepositDescriptor,createCoralFluxDeposit} from './planet-renderer.js';
import {travel,basis,point,MONUMENTS,classifyBiome,planetDistance} from '/shared/planet.js';
import {coralShelfLandmark} from '/shared/landmarks.js';
import * as THREE from 'three';
import {accountUI} from './account.js';
import {daylight,SPECIES} from '/shared/ecology.js';
import {wildlifeRenderer} from './wildlife.js';
import {bindControls} from './controls.js';
import {createReconnectController} from './reconnect.js';
import {createInputReconciler} from './reconciliation.js';
import {acceptSnapshotBaseline,applySnapshotDelta,coralFieldCutterFeedback,coralFluxAccessibleRegenerationFeedback,coralFluxResourceLabel,parseSnapshotMessage} from './snapshot-delta.js';
import {createAudioEngine,createAudioSettings} from './audio.js';
import {createAuthoredMeshObject,disposeAuthoredMesh,loadAuthoredMesh} from './authored-mesh.js';
import {height,surface,stairProfile,generate,rng,RUIN,RECIPES,RESOURCES,shape,doorParts,dist,placementError,canAfford,itemCount,sheltered,powered,blocked,interactionTarget} from '/shared/world.js';
const account=accountUI();
const tipsOn=localStorage.getItem('vc-tips')!=='off';document.documentElement.classList.toggle('tips-off',!tipsOn);document.getElementById('showTips').checked=tipsOn;document.getElementById('showTips').onchange=e=>{localStorage.setItem('vc-tips',e.target.checked?'on':'off');document.documentElement.classList.toggle('tips-off',!e.target.checked);};
const $=id=>document.getElementById(id),canvas=$('world');
const audioSettings=createAudioSettings(localStorage),audio=createAudioEngine({settings:audioSettings,createContext:()=>{const Context=window.AudioContext||window.webkitAudioContext;if(!Context)throw Error('Web Audio unavailable');return new Context();}});
const renderAudioSettings=()=>{const value=audioSettings.get();$('audioMuted').checked=value.muted;$('interfaceVolume').value=value.interfaceVolume;$('worldVolume').value=value.worldVolume;$('interfaceVolumeValue').textContent=`${value.interfaceVolume}%`;$('worldVolumeValue').textContent=`${value.worldVolume}%`;};
renderAudioSettings();
$('audioMuted').onchange=e=>{audio.setMuted(e.target.checked);renderAudioSettings();};
for(const[category,id]of[['interface','interfaceVolume'],['world','worldVolume']])$(id).oninput=e=>{audioSettings.setCategory(category,Number(e.target.value));renderAudioSettings();};
const activateAudio=()=>{void audio.activate(true);};window.addEventListener('pointerdown',activateAudio,{capture:true});window.addEventListener('keydown',activateAudio,{capture:true});
let renderer;
try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});}catch(e){$('joinError').textContent='This browser needs WebGL 2 enabled to render the world.';throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;
const scene=new THREE.Scene();scene.background=new THREE.Color('#718f96');scene.fog=new THREE.FogExp2('#819da0',.012);
const skyAtmosphere=atmosphere(scene);let scatter=null;
const camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,.1,230);
const skyLight=new THREE.HemisphereLight(0xc4e5e0,0x573746,1.8);scene.add(skyLight);const sun=new THREE.DirectionalLight(0xffd4a6,2.5);sun.position.set(-24,48,18);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-45,right:45,top:45,bottom:-45,near:1,far:110});sun.shadow.bias=-.001;scene.add(sun);
const deposits=resourceDeposits(scene);
const wildlife=wildlifeRenderer(scene);const vehicles=vehicleRenderer(scene);let planet=null;
const mat=(color,opts={})=>new THREE.MeshStandardMaterial({color,roughness:.85,flatShading:true,...opts});
const materials={cargo:mat(0x5d8790),workbench:mat(0x607b76),perimeter:mat(0x65746c),campGate:mat(0x756f5d),lamp:mat(0xffdfa0,{emissive:0xffce7e,emissiveIntensity:2}),deck:mat(0x4d666c),wall:mat(0xd3d0b7),roof:mat(0x8fa99a),angledCanopy:mat(0x789b91),stairs:mat(0x617c80),railing:mat(0x65746c),heater:mat(0x384e59),trim:mat(0xf4b28f),glow:mat(0x9effd5,{emissive:0x57bb9e,emissiveIntensity:1}),dark:mat(0x203c48),coralFlux:mat(0xe68a82,{emissive:0x572b48,emissiveIntensity:.35}),depletedCoralFlux:mat(0x776b78)};
function mesh(g,m,parent=scene){const obj=new THREE.Mesh(g,m);parent.add(obj);return obj;}
function box(w,h,d,m,parent){const o=mesh(new RoundedBoxGeometry(w,h,d,1,Math.min(.045,w*.15,h*.15,d*.15)),m,parent);o.castShadow=true;o.receiveShadow=true;return o;}
let worldGroup=new THREE.Group(),coralFluxGroup=new THREE.Group();scene.add(worldGroup);let state={seed:7319,time:0,structures:[],resources:generate(7319),players:[]},snapshotRevision=null,id=null,ws=null,joined=false;
let terrain,ruinPulse,resourceMeshes={},resourceKey='',structureKey='',currentBiome=null,currentLandmark=null,structuresGroup=new THREE.Group(),preview=new THREE.Group(),assetGeneration=0,assetController=null,brokenSignalRingState='fallback';scene.add(structuresGroup,preview);
const dummy=new THREE.Object3D();
function buildEnvironment(seed){
 assetController?.abort();const generation=++assetGeneration,controller=new AbortController();assetController=controller;brokenSignalRingState='fallback';
 scene.remove(worldGroup);worldGroup.traverse(o=>{if(o.geometry&&!o.userData.sharedArt)o.geometry.dispose();});worldGroup=new THREE.Group();coralFluxGroup=new THREE.Group();worldGroup.add(coralFluxGroup);scene.add(worldGroup);
 scatter?.dispose();scatter=groundScatter(scene,seed);planet?.dispose();planet=planetRenderer(scene,seed);terrain=planet.terrain;planet.update(me()||{x:0,z:3});
 for(const type of Object.keys(RESOURCES)){const authored=fieldResource(type),geo=authored||(type==='fiber'?new THREE.ConeGeometry(.65,1.9,5):type==='crystal'?new THREE.OctahedronGeometry(.85,0):new THREE.DodecahedronGeometry(.85,0));const m=mat(authored?0xffffff:RESOURCES[type].color,type==='crystal'?{emissive:0x4b3d95,emissiveIntensity:.5}:{});if(authored){m.vertexColors=true;m.flatShading=false;}const inst=new THREE.InstancedMesh(geo,m,1000);inst.castShadow=true;worldGroup.add(inst);resourceMeshes[type]=inst;}
 const y=height(RUIN.x,RUIN.z,seed),ruin=new THREE.Group(),fallback=new THREE.Group();ruin.position.set(RUIN.x,y,RUIN.z);fallback.name='broken-signal-ring-fallback';fallback.userData.authoredAssetFallback=true;ruin.add(fallback);worldGroup.add(ruin);
 for(const [x,z] of [[-3,-3],[3,-3],[-3,3],[3,3]]){const col=box(.95,5,.95,materials.dark,fallback);col.position.set(x,2.5,z);const tip=box(1.15,.15,1.15,materials.trim,fallback);tip.position.set(x,5,z);}
 const ring=mesh(new THREE.TorusGeometry(3.6,.22,5,40,Math.PI*1.65),materials.wall,fallback);ring.position.set(0,6.4,0);ring.rotation.z=.3;
 const console=box(1.2,.8,1,materials.dark,ruin);console.position.y=.4;ruinPulse=mesh(new THREE.OctahedronGeometry(.5),materials.glow,ruin);ruinPulse.position.y=1.6;
 void loadAuthoredMesh({url:'/client/assets/broken-signal-ring.json',signal:controller.signal,create:data=>createAuthoredMeshObject(THREE,data,{'weathered-ivory':materials.wall,'dark-blue-green':materials.dark,'mint-energy':materials.glow,'coral-lavender':materials.trim}),isCurrent:()=>assetGeneration===generation&&!controller.signal.aborted}).then(candidate=>{if(!candidate||assetGeneration!==generation||controller.signal.aborted){disposeAuthoredMesh(candidate);return;}ruin.add(candidate);ruin.remove(fallback);disposeAuthoredMesh(fallback);brokenSignalRingState='authored';});
 const pad=mesh(new THREE.CylinderGeometry(1.8,2,.1,8),materials.dark,worldGroup);pad.position.set(0,height(0,0,seed)+.05,0);
 const moon=mesh(new THREE.IcosahedronGeometry(11,2),mat(0xf1d1ae),worldGroup);moon.position.set(-50,46,-91);const moonring=mesh(new THREE.TorusGeometry(18,.35,5,64),mat(0xf0d5bc),worldGroup);moonring.position.copy(moon.position);moonring.rotation.set(1,.3,.4);
 resourceKey='';structureKey='';updateGeometry();
}
function pieceMesh(piece,ghost=false){const group=new THREE.Group(),stairs=piece.type==='stairs'?stairProfile(state,piece):null,s=stairs?{...stairs.centre,y:stairs.centre.y-.06,frame:stairs.frame}:shape(piece,state.seed);group.userData.pieceType=piece.type;group.userData.pieceId=piece.id;group.userData.open=!!piece.open;group.position.copy(vector(s.x,s.z,s.y));orient(group,s.frame.x,s.frame.z);const authored=!ghost&&fieldProp(piece.type,s);if(authored){group.add(authored);return group;}const color=ghost?new THREE.MeshBasicMaterial({color:0xb9f1c7,transparent:true,opacity:.48,depthWrite:false}):(materials[piece.type==='floor'?'deck':piece.type]||materials.wall);if(piece.type==='door'){for(const part of doorParts(piece,state.seed)){const object=box(part.w,part.h,part.d,color,group);object.position.set(part.x,part.y,part.z);}}else if(piece.type==='doorway'){const alongX=s.w>s.d,postW=.55,postOffset=1.225;for(const side of[-1,1]){const post=box(alongX?postW:s.w,s.h,alongX?s.d:postW,color,group);post.position[alongX?'x':'z']=side*postOffset;}const lintel=box(s.w,.45,s.d,color,group);lintel.position.y=s.h/2-.225;}else if(piece.type==='campGate'){const alongX=s.w>s.d;for(const side of[-1,1]){const post=box(.22,s.h,.22,color,group);post.position[alongX?'x':'z']=side*1.35;}const leaf=box(alongX?(piece.open?.14:2.45):(piece.open?2.45:.14),1.65,alongX?(piece.open?2.45:.14):(piece.open?.14:2.45),color,group);leaf.position.set(piece.open?(alongX?-1.2:1.2):0,-.35,piece.open?(alongX?1.2:-1.2):0);}else if(piece.type==='railing'){const alongX=s.w>s.d;for(const side of[-1,1]){const post=box(.18,s.h,.18,color,group);post.position[alongX?'x':'z']=side*1.35;}for(const level of[.38,.82]){const rail=box(alongX?2.7:.12,.12,alongX?.12:2.7,color,group);rail.position.y=level-s.h/2;}}else if(piece.type==='angledCanopy'){const panel=box(s.w,s.h,s.d,color,group);panel.rotation.set(-.28,((piece.rotation%4)+4)%4*Math.PI/2,0,'YXZ');}else if(piece.type==='stairs'){const r=((piece.rotation||0)%4+4)%4,ramp=box(r%2?stairs.length:1.6,.12,r%2?1.6:stairs.length,color,group);if(r===0)ramp.rotation.x=-stairs.angle;if(r===1)ramp.rotation.z=-stairs.angle;if(r===2)ramp.rotation.x=stairs.angle;if(r===3)ramp.rotation.z=stairs.angle;}else box(s.w,s.h,s.d,color,group);
 if(!ghost){if(piece.type==='heater'){const core=mesh(new THREE.OctahedronGeometry(.4),materials.glow,group);core.position.y=.6;const aura=mesh(new THREE.RingGeometry(6.8,7,48),new THREE.MeshBasicMaterial({color:0xa6eccb,side:THREE.DoubleSide,transparent:true,opacity:.22,depthWrite:false}),group);aura.rotation.x=-Math.PI/2;aura.position.y=-.65;}else if(piece.type==='floor'){for(const x of [-1.35,1.35]){const rail=box(.07,.04,2.8,materials.trim,group);rail.position.set(x,.11,0);}}else if(piece.type==='cargo'){const seam=box(1.52,.06,1.02,materials.dark,group);seam.position.y=.22;const latch=box(.25,.3,.06,materials.glow,group);latch.position.set(0,.05,.53);}else if(piece.type==='wall'){const stripe=box(s.w>.2?s.w:.2,.08,s.d>.2?s.d:.2,materials.trim,group);stripe.position.y=.7;}}
 return group;
}
function clearGroup(group){for(const obj of [...group.children]){obj.traverse(o=>{if(o.geometry&&!o.userData.sharedArt)o.geometry.dispose();});group.remove(obj);}}
function updateGeometry(){const rk=state.resources.map(n=>n.id+':'+n.amount).join(',');if(rk!==resourceKey){resourceKey=rk;deposits.update(state);clearGroup(coralFluxGroup);for(const n of state.resources){const deposit=createCoralFluxDeposit(n,materials.coralFlux,materials.depletedCoralFlux);if(!deposit)continue;deposit.position.copy(vector(n.x,n.z,n.y));orient(deposit,n.x,n.z);deposit.rotateY(n.x*1.7);coralFluxGroup.add(deposit);}for(const type of Object.keys(RESOURCES)){let i=0;for(const n of state.resources.filter(n=>n.type===type&&n.amount>0&&!depositKind(n)&&!coralFluxDepositDescriptor(n))){const size=.6+Math.min(4,n.amount)*.1;dummy.position.copy(vector(n.x,n.z,n.y+(type==='fiber'?.8:.6)*(fieldArtReady()?size:1)));orient(dummy,n.x,n.z);dummy.rotateY(n.x*1.7);if(type==='crystal')dummy.rotateZ(.12);dummy.scale.setScalar(size);dummy.updateMatrix();resourceMeshes[type].setMatrixAt(i++,dummy.matrix);}resourceMeshes[type].count=i;resourceMeshes[type].instanceMatrix.needsUpdate=true;resourceMeshes[type].computeBoundingSphere();}}
 const sk=state.structures.map(s=>s.id+':'+!!s.open).join(',');if(sk!==structureKey){structureKey=sk;clearGroup(structuresGroup);for(const s of state.structures)structuresGroup.add(pieceMesh(s));}}
function astronaut(color){const imported=fieldModel('explorer');if(imported)return imported;const group=new THREE.Group(),suit=mat(color);const torso=box(.62,.75,.4,suit,group);torso.position.y=1.05;const head=mesh(new THREE.IcosahedronGeometry(.36,1),materials.wall,group);head.position.y=1.65;const visor=box(.47,.19,.11,materials.dark,group);visor.position.set(0,1.66,.3);const pack=box(.45,.55,.25,materials.trim,group);pack.position.set(0,1.08,-.3);const legs=[];for(const x of [-.18,.18]){const leg=box(.2,.58,.22,materials.dark,group);leg.position.set(x,.38,0);legs.push(leg);const arm=box(.17,.68,.2,suit,group);arm.position.set(x*2.3,1.02,0);}group.userData.legs=legs;return group;}
const avatars=new Map(),inputReconciler=createInputReconciler();let localPos=new THREE.Vector3(0,0,3),yaw=0,pitch=.42,distance=5.5,keys={},buildMode=false,selected='floor',rotation=0,piece=null,lastInput=0,lastGather=0,guide=false,toastTimer;
const staffTools=adminTools({character:()=>me(),selectPiece:key=>{selected=key;buildMode=true;guideOpen(false);updateHUD();},notify:msg=>notify(msg)});
function me(){return state.players.find(p=>p.id===id);}
let visualActionUntil=0;
function send(m){if(['gather','attack','build','scan','salvage'].includes(m.type))visualActionUntil=performance.now()+650;if(m.type==='vehicleBuild'&&staffTools.quickBuild()){staffTools.vehicle(m.vehicle);return;}if(m.type==='build'&&staffTools.quickBuild()){staffTools.build(m);return;}if(ws?.readyState===1&&joined)ws.send(JSON.stringify(m));}
$('jumpAction').onclick=()=>{if(joined&&!guide)send({type:'jump'});};
function sendInput(input){if(ws?.readyState!==1||!joined)return;const message=inputReconciler.queue({type:'input',...input});if(message)ws.send(JSON.stringify(message));}
function notify(msg){$('toast').textContent=msg;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3500);}
function guideOpen(open){controls.reset();moveTarget=null;guide=open;$('guide').classList.toggle('hidden',!open);if(!open)$('menuButton').focus();keys={};sendInput({x:0,z:0});if(open){document.exitPointerLock?.();void staffTools.refresh();renderRecipes();document.querySelector('[data-guide-tab][aria-selected="true"]').focus();}audio.play('interface');}
function capture(){canvas.requestPointerLock?.()?.catch?.(()=>notify('Mouse capture unavailable. Drag on the world to orbit.'));}
function selectGuideTab(key){for(const tab of document.querySelectorAll('[data-guide-tab]')){const active=tab.dataset.guideTab===key;tab.setAttribute('aria-selected',String(active));tab.tabIndex=active?0:-1;$(tab.getAttribute('aria-controls')).classList.toggle('hidden',!active);}$('guide').querySelector('.guide-content').scrollTop=0;}
for(const tab of document.querySelectorAll('[data-guide-tab]')){tab.onclick=()=>selectGuideTab(tab.dataset.guideTab);tab.onkeydown=e=>{const tabs=[...document.querySelectorAll('[data-guide-tab]')].filter(tab=>!tab.classList.contains('hidden')),i=tabs.indexOf(tab);let next;if(e.key==='ArrowRight')next=(i+1)%tabs.length;if(e.key==='ArrowLeft')next=(i+tabs.length-1)%tabs.length;if(e.key==='Home')next=0;if(e.key==='End')next=tabs.length-1;if(next!==undefined){e.preventDefault();selectGuideTab(tabs[next].dataset.guideTab);tabs[next].focus();}};}
function toggleBackpack(){if(!joined)return;if(guide&&!$('guide').classList.contains('hidden')&&$('guideTab-backpack').getAttribute('aria-selected')==='true'){guideOpen(false);return;}if(guide)closeControllerMenu();selectGuideTab('backpack');guideOpen(true);}
$('backpackAction').onclick=toggleBackpack;
$('menuButton').onclick=()=>guideOpen(true);$('closeGuide').onclick=()=>guideOpen(false);
let recipeState='';
const reconnect=createReconnectController({attempt:connectExplorer,exhausted:()=>{$('network').textContent='OFFLINE';$('joinError').textContent='Connection lost. Rejoin manually.';$('enter').disabled=false;notify('Automatic reconnect stopped. Rejoin when the server is available.');}});
$('leave').onclick=()=>{reconnect.stop();sendInput({x:0,z:0});ws?.close();location.reload();};
function connectExplorer(){$('enter').disabled=true;$('joinError').textContent='Connecting to the expedition server…';
 const character=$('character').value;if(!character){$('joinError').textContent='Create or select a character first.';$('enter').disabled=false;return;}localStorage.setItem('vc-selected-character',character);
 const socket=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/api/ws`);ws=socket;
 socket.onopen=()=>socket.send(JSON.stringify({type:'join',character,server:'quiet-basin'}));
 socket.onmessage=e=>{if(ws!==socket)return;let m;try{m=parseSnapshotMessage(e.data);}catch{socket.close(4000,'Snapshot resync');return;}if(m.type==='error'){notify(m.message);$('joinError').textContent=m.message;$('enter').disabled=false;socket.close();return;}
 if(m.type==='notice')notify(m.message);
 if(m.type==='welcome'){let baseline;try{baseline=acceptSnapshotBaseline(m.state,m.revision);}catch{socket.close(4000,'Snapshot resync');return;}reconnect.connected();inputReconciler.reset();id=m.id;state=baseline;snapshotRevision=m.revision;joined=true;void staffTools.refresh();localPos.set(me().x,surface(state,me().x,me().z),me().z);buildEnvironment(state.seed);$('landing').classList.add('hidden');$('hud').classList.remove('hidden');if(!document.documentElement.classList.contains('tips-off'))notify('Drag to look. Tap terrain or use the movement pad to walk.');}
 if(m.type==='delta'||m.type==='state'){let nextState,nextRevision;try{if(m.type==='delta'){nextState=applySnapshotDelta(state,m.delta,snapshotRevision);nextRevision=m.delta.revision;}else{if(m.revision!==snapshotRevision+1)throw TypeError('Snapshot revision skipped');nextState=acceptSnapshotBaseline(m.state,m.revision);nextRevision=m.revision;}}catch{socket.close(4000,'Snapshot resync');return;}state=nextState;motionSampler.push(state,performance.now());snapshotRevision=nextRevision;reconnect.stable();const p=me();if(p){const corrected=inputReconciler.reconcile(localPos,p,m.inputAck);if(!p.vehicle){localPos.x=corrected.x;localPos.z=corrected.z;}}updateGeometry();if(storageId)renderStorage();terminal.update();if(guide){const key=JSON.stringify([p?.inventory,p?.cutter,p?.flashlightOwned,p?.unlocked,state.players.map(player=>[player.id,player.name]),state.structures.filter(s=>s.type==='workbench').map(s=>[s.id,s.power,s.water,s.readyAt,s.cycleUntil,s.canUseWorkbench,s.workbenchGrantedTo,s.canCancelWorkbench,s.workbenchCancelJobId])]);if(key!==recipeState){recipeState=key;renderRecipes();}}$('saveStatus').textContent=m.saveError||`Saved · ${m.lastSaved?new Date(m.lastSaved).toLocaleTimeString():'pending'}`;}
 if(m.type==='result'){terminal.feedback(m.message);if(m.message!=='Jump')notify(m.message);audio.play('world');if(guide)renderRecipes();}
 updateHUD();};
 socket.onclose=()=>{if(ws!==socket)return;void audio.suspend();$('enter').disabled=false;joined=false;snapshotRevision=null;inputReconciler.reset();keys={};controls.reset();moveTarget=null;if(reconnect.active){$('network').textContent='RECONNECTING';notify('Reconnecting to the expedition…');reconnect.disconnected();}else if(!$('joinError').textContent)$('joinError').textContent='Server unavailable. Please try again.';};socket.onerror=()=>{if(ws===socket)$('joinError').textContent='Could not reach the expedition server.';};
}

async function showServers(){ $('findGame').classList.add('hidden');$('serverBrowser').classList.remove('hidden');$('serverInfo').textContent='Checking server…';try{const res=await fetch('/api/servers',{cache:'no-store'});if(!res.ok)throw Error();const data=await res.json(),server=data.servers[0];document.querySelector('.server-card b').textContent=server.name;$('enter').textContent='JOIN '+server.name.toUpperCase()+' ↗';$('serverInfo').textContent=`${server.players} / ${server.maxPlayers} explorers online · Seeded planetary expedition`;$('enter').disabled=server.players>=server.maxPlayers||!$('character').value;}catch{$('serverInfo').textContent='Unable to check occupancy. You can still try joining.';$('enter').disabled=!$('character').value;}}
$('findGame').onclick=showServers;$('backTitle').onclick=()=>{$('serverBrowser').classList.add('hidden');$('findGame').classList.remove('hidden');};

$('joinForm').onsubmit=e=>{e.preventDefault();connectExplorer();};
function renderWorkbenchAccess(p){const manager=$('workbenchAccessManager'),roster=$('workbenchAccessRoster'),candidate=$('workbenchAccessCandidate'),grant=$('grantWorkbenchAccess'),bench=state.structures.filter(s=>s.type==='workbench'&&Array.isArray(s.workbenchGrantedTo)&&dist(s,p)<=3).sort((a,b)=>dist(a,p)-dist(b,p))[0],focused=manager.contains(document.activeElement)?document.activeElement.getAttribute('aria-label'):null;manager.classList.toggle('hidden',!bench);roster.replaceChildren();candidate.replaceChildren();if(!bench)return;const grantedIds=new Set(bench.workbenchGrantedTo.map(character=>character.id));for(const character of state.players.filter(character=>character.id!==id&&!grantedIds.has(character.id))){const option=document.createElement('option');option.value=character.id;option.textContent=character.name;candidate.append(option);}grant.disabled=!candidate.options.length;grant.onclick=()=>send({type:'workbenchAccess',id:bench.id,target:candidate.value,allow:true});for(const character of bench.workbenchGrantedTo){const row=document.createElement('div');row.className='workbench-access-row';const name=document.createElement('span');name.textContent=character.name;const revoke=document.createElement('button');revoke.textContent='REVOKE';revoke.setAttribute('aria-label',`Revoke workbench access for ${character.name}`);revoke.onclick=()=>send({type:'workbenchAccess',id:bench.id,target:character.id,allow:false});row.append(name,revoke);roster.append(row);}if(focused){const restore=[...manager.querySelectorAll('[aria-label]')].find(element=>element.getAttribute('aria-label')===focused)||(focused.startsWith('Revoke workbench access for ')?grant:null);restore?.focus();}}
function renderRecipes(){const p=me();if(!p)return;renderWorkbenchAccess(p);const focused=$('recipes').contains(document.activeElement)?document.activeElement.getAttribute('aria-label'):null;$('backpack').textContent=Object.entries(p.inventory).map(([k,v])=>`${RESOURCES[k].name}: ${v}`).join(' · ');$('recipes').replaceChildren();for(const [key,r] of Object.entries(RECIPES)){const div=document.createElement('div');div.className='recipe';const button=document.createElement('button'),bench=key==='ration'?state.structures.filter(s=>s.type==='workbench'&&(s.owner===p.id||s.canUseWorkbench===true)&&dist(s,p)<=3).sort((a,b)=>dist(a,p)-dist(b,p))[0]:null,cancelBench=key==='ration'?state.structures.filter(s=>s.type==='workbench'&&s.canCancelWorkbench===true&&dist(s,p)<=3).sort((a,b)=>dist(a,p)-dist(b,p))[0]:null,benchRecipe=key==='ration',craftable=['cutter','flashlight','rifle','repair'].includes(key),owned=key==='cutter'?p.cutter:key==='flashlight'?p.flashlightOwned:!!p[key],action=benchRecipe?'Queue':craftable?(owned?'Equipped':'Craft'):r.unlock&&!p.unlocked?'Locked':'Select';button.textContent=action.toUpperCase();button.setAttribute('aria-label',`${action} ${r.name.toLowerCase()}`);button.disabled=benchRecipe?(!bench||!Number.isSafeInteger(bench.cycleUntil)||bench.water>=3||!canAfford(p,key)):(craftable&&(owned||!canAfford(p,key)))||(r.unlock&&!p.unlocked);button.onclick=()=>{if(benchRecipe)send({type:'workbench',id:bench.id,recipe:'ration',sequence:bench.cycleUntil});else if(craftable)send({type:'craft',recipe:key});else{selected=key;buildMode=true;guideOpen(false);updateHUD();}};const title=document.createElement('b');title.textContent=r.name;const cost=document.createElement('small');cost.textContent=Object.entries(r.cost).map(([k,v])=>`${v} ${RESOURCES[k].name}`).join(' + ');const desc=document.createElement('p');desc.textContent=benchRecipe?!bench?'Move within 3 m of a workbench you may use':bench.water>=3?'QUEUE FULL':bench.power===100&&state.time>=bench.readyAt?'BLOCKED · MAKE BACKPACK SPACE':bench.water?`IN PROGRESS · ${Math.floor(bench.power)}% · ${bench.water}/3 jobs`:'Ready · 5 server seconds':r.description;div.append(button,title,cost,desc);if(benchRecipe&&typeof cancelBench?.workbenchCancelJobId==='string'){const cancel=document.createElement('button');cancel.textContent='CANCEL PENDING';cancel.setAttribute('aria-label','Cancel my pending Field meal');cancel.onclick=()=>send({type:'workbenchCancel',id:cancelBench.id,jobId:cancelBench.workbenchCancelJobId});div.append(cancel);}$('recipes').append(div);}if(focused){const buttons=[...$('recipes').querySelectorAll('button:not(:disabled)')],restore=buttons.find(button=>button.getAttribute('aria-label')===focused)||(focused==='Cancel my pending Field meal'?buttons.find(button=>button.getAttribute('aria-label')==='Queue field meal')||$('guideTab-fabrication'):null);restore?.focus();}}
const pieces=['floor','wall','roof','heater','perimeter','campGate','lamp','cargo','doorway','angledCanopy','door','stairs','railing','workbench'];pieces.forEach((key,i)=>{const b=document.createElement('button'),cost=document.createElement('small');if(i<9){const shortcut=document.createElement('b');shortcut.textContent=i+1;b.append(shortcut);}cost.textContent=Object.entries(RECIPES[key].cost).map(([k,v])=>v+' '+k).join(' / ');b.append(document.createTextNode(RECIPES[key].name),cost);b.setAttribute('aria-label',`Build ${RECIPES[key].name.toLowerCase()}`);b.onclick=()=>{selected=key;buildMode=true;updateHUD();};b.dataset.piece=key;$('hotbar').append(b);});
function attack(){const p=me();if(!p)return;const range=p.rifle?35:2.8;const targets=[...state.players.filter(q=>q.id!==id),...(state.creatures||[]),...state.structures,...(state.vehicles||[])];const c=targets.filter(c=>{const dx=c.x-p.x,dz=c.z-p.z,d=dist(c,p);return d<range&&d>.1&&(dx*-Math.sin(yaw)+dz*-Math.cos(yaw))/Math.hypot(dx,dz)>.65;}).sort((a,b)=>dist(a,p)-dist(b,p))[0];if(c)send({type:'attack',id:c.id,ranged:!!p.rifle});else notify('Aim toward a target in reach.');}
$('attackAction').onclick=attack;$('lightAction').onclick=()=>send({type:'light'});$('eatAction').onclick=()=>send({type:'eat'});
let repeatActionKey=null;
function interact(repeating=false){const p=me();if(!p||!joined||guide)return;const action=contextAction(state,p,{buildMode,yaw});const key=action?JSON.stringify([action.kind,action.message]):null;if(!repeating)repeatActionKey=key;if(!action||repeating&&(!action.repeat||key!==repeatActionKey))return;if(action.kind==='place'){if(piece)send({type:'build',piece:selected,x:piece.x,z:piece.z,rotation,site:piece.site,gx:piece.gx,gz:piece.gz});return;}if(action.kind==='storage'){$('storageAction').click();return;}if(action.kind==='fabrication'){guideOpen(true);selectGuideTab('fabrication');return;}if(['habitat','vehicles'].includes(action.kind)){terminal.open(action.kind);return;}if(action.message.type==='gather'&&coralFieldCutterFeedback(state.resources,p,action.message,dist))return;send(action.message);}

function updateHUD(){const p=me();if(!p)return;const action=contextAction(state,p,{buildMode,yaw});$('gatherAction').textContent=action?.label||'Action';$('gatherAction').disabled=!action;$('network').textContent=`${state.playerCount||state.players.length} EXPLORER${state.playerCount===1?'':'S'} ONLINE`;
 const day=daylight(state.time,state.settings);$('dayClock').textContent=`DAY ${day.day} · ${sunlight(state.time,state.planet,p).label} · ${day.remaining}s`;const storm=state.time%150>=105;$('weather').textContent=storm?`ION WIND · ${Math.ceil(150-state.time%150)}s`:`CALM · WIND IN ${Math.ceil(105-state.time%150)}s`;
 $('survivalStatus').textContent=`O₂ ${Math.ceil(p.oxygen)} · WATER ${Math.ceil(p.water)} · FOOD ${Math.ceil(p.food)} · STAMINA ${Math.ceil(p.stamina)}`;$('charge').value=p.charge;$('health').value=p.health;$('chargeText').textContent=`${Math.ceil(p.charge)}%`;$('healthText').textContent=`${Math.ceil(p.health)}%`;$('protection').textContent=powered(state,p)?'ANCHOR FIELD · RECHARGING':sheltered(state,p)?'SHELTERED · RECHARGING':storm?'ION WIND · FIND SHELTER':'EXPOSED · SLOW DRAIN';
 $('inventory').textContent=`${itemCount(p.inventory)}/60 · ${p.inventory.ferrite} Ferrite   ·   ${p.inventory.fiber} Fiber   ·   ${p.inventory.crystal} Flux · ${p.inventory.ration||0} Meals`;$('lightAction').textContent=p.flashlightOn?'Light: ON':'Light';
 const biome=classifyBiome(p.x,p.z,state.seed),landmark=coralShelfLandmark(state.seed),nearLandmark=planetDistance(p,landmark)<=landmark.proximity,label=`${biome.name}${nearLandmark?` · Near ${landmark.name}`:''}`;currentLandmark=landmark;if(biome.id!==currentBiome?.id||$('coords').textContent!==label){currentBiome=biome;$('coords').textContent=label;}
 const bearing=Math.atan2(RUIN.x-p.x,-(RUIN.z-p.z))*180/Math.PI;$('bearing').textContent=`${Math.round(dist(p,RUIN))} m · ${Math.round((bearing+360)%360)}°`;
 const roof=state.structures.some(s=>['roof','angledCanopy'].includes(s.type)),anchor=state.structures.some(s=>s.type==='heater');
 const stages=[['Craft a field cutter',p.cutter],['Read the signal ruin',p.unlocked],['Build a canopy over a deck',roof],['Power an outpost',p.completed]];
 $('steps').replaceChildren(...stages.map(([label,done])=>{const d=document.createElement('div');d.className=done?'done':'';d.textContent=`${done?'✓':'○'} ${label}`;return d;}));
 $('objective').textContent=p.completed?'A foothold among the stars.':!p.cutter?'Start with what you find.':!p.unlocked?'Follow the broken ring.':!roof?'Make shelter.':!anchor?'Bring the signal home.':'Stand beneath your powered canopy.';
 $('objectiveDetail').textContent=p.completed?'First Signal complete. Keep exploring and expand your shared outpost.':!p.cutter?'Gather 3 ferrite and 2 ribbon fiber. Open C to fabricate your cutter.':!p.unlocked?'Seek the ring northeast of the landing point. Press E at its console.':'Build a deck, canopy and resonance anchor. A powered shelter is your first home.';
 $('lore').textContent=p.unlocked?'“We did not build the signal. We only taught it to wait.” — fragment recovered from the broken ring':'The broken ring on the ridge carries a faint repeating signal. A field cutter might let you read it.';
 for(const b of $('hotbar').children)b.classList.toggle('active',buildMode&&b.dataset.piece===selected);
 $('hotbar').classList.toggle('hidden',!buildMode);$('toolbelt').classList.toggle('hidden',buildMode);for(const b of $('toolbelt').children){const item=p.belt?.[Number(b.dataset.slot)];b.textContent=`${(Number(b.dataset.slot)+1)%10} ${item?(RECIPES[item]?.name||RESOURCES[item]?.name||item):'—'}`;}$('placeAction').disabled=!buildMode;$('rotateAction').disabled=!buildMode;$('buildAction').textContent=buildMode?'Exit build':'Build';$('buildHint').classList.toggle('hidden',!buildMode);const target=interactionTarget(state,p),nearRuin=dist(p,RUIN)<4,targetDoor=target?.type==='door'?state.structures.find(s=>s.id===target.id):null,targetGate=target?.type==='campGate'?state.structures.find(s=>s.id===target.id):null,targetResource=target?.type==='gather'?state.resources.find(n=>n.id===target.id):null,coralToolFeedback=coralFieldCutterFeedback(state.resources,p,nearRuin?{type:'scan'}:target,dist),depletedFeedback=coralFluxAccessibleRegenerationFeedback(state.resources,p,state.time,nearRuin?{type:'scan'}:target,dist),targetBench=state.structures.find(s=>s.type==='workbench'&&s.owner===p.id&&dist(s,p)<=3);const nearby=(state.creatures||[]).filter(c=>dist(c,p)<5).sort((a,b)=>dist(a,p)-dist(b,p))[0];$('interaction').textContent=buildMode?'':nearRuin?'[E] Read signal console':targetDoor?`[E] ${targetDoor.open?'Close':'Open'} sealed door`:targetGate?`[E] ${targetGate.open?'Close':'Open'} Camp gate`:coralToolFeedback?coralToolFeedback:targetResource?`[E] Gather ${coralFluxResourceLabel(targetResource)||RESOURCES[targetResource.type].name} · ${targetResource.amount} remaining`:depletedFeedback?depletedFeedback:targetBench?'Workbench nearby · open Field Guide to queue a field meal':nearby?`${SPECIES[nearby.type].name} · ${nearby.type==='grazer'?'neutral · hunt for meat':'hostile'} · Attack within 2.8 m`:'Tap terrain to walk · Drag to look';
}
window.addEventListener('keydown',e=>{if(!joined||['INPUT','SELECT'].includes(document.activeElement.tagName))return;if(['Tab','Space','KeyW','KeyA','KeyS','KeyD'].includes(e.code)&&!(e.code==='Tab'&&!$('expedition').classList.contains('hidden')))e.preventDefault();if(e.repeat)return;
 if(e.code==='KeyI'){e.preventDefault();toggleBackpack();return;}if(e.code==='KeyC'){guideOpen(!guide);return;}if(e.code==='Escape'){if(storageId){$('closeStorage').click();return;}if(guide)guideOpen(false);else if(buildMode){buildMode=false;updateHUD();}return;}if(guide)return;keys[e.code]=true;
 if(e.code==='KeyF')send({type:'light'});if(e.code==='KeyH')send({type:'eat'});if(e.code==='Space')send({type:'jump'});
 if(e.code==='KeyB'){buildMode=!buildMode;updateHUD();}if(/^Digit[0-9]$/.test(e.code)&&!buildMode){terminal.useBelt((Number(e.code.slice(-1))+9)%10);return;}if(/^Digit[1-9]$/.test(e.code)){selected=pieces[+e.code.slice(-1)-1];buildMode=true;updateHUD();}if(e.code==='KeyR')rotation=(rotation+1)%4;if(e.code==='KeyE'){interact();lastGather=performance.now();}
 if(e.code==='KeyX'){const p=me(),s=state.structures.filter(s=>s.canDismantle&&dist(s,p)<6).sort((a,b)=>dist(a,p)-dist(b,p)||Number(a.type==='floor')-Number(b.type==='floor'))[0];if(s)send({type:'dismantle',id:s.id});}
});window.addEventListener('keyup',e=>keys[e.code]=false);window.addEventListener('blur',()=>{keys={};sendInput({x:0,z:0});void audio.suspend();});document.addEventListener('visibilitychange',()=>{if(document.hidden){keys={};sendInput({x:0,z:0});void audio.suspend();}});window.addEventListener('pagehide',()=>{assetController?.abort();void audio.destroy();},{once:true});
let moveTarget=null,stuckTime=0;
function dismantleNearest(){const p=me();if(!p)return;const s=state.structures.filter(s=>s.canDismantle&&dist(s,p)<6).sort((a,b)=>dist(a,p)-dist(b,p)||Number(a.type==='floor')-Number(b.type==='floor'))[0];if(s)send({type:'dismantle',id:s.id});else notify('No nearby piece authorizes you to dismantle it.');}

let storageId=null,storageState='';
const storageUI=createStorageUI({send,notify});
$('storageAction').onclick=()=>{const p=me();const s=state.structures.filter(s=>s.type==='cargo'&&dist(s,p)<3).sort((a,b)=>dist(a,p)-dist(b,p))[0];if(!s){notify('Move within 3 m of a cargo locker.');return;}storageId=s.id;storageState='';guide=true;controls.reset();moveTarget=null;keys={};$('storagePanel').classList.remove('hidden');renderStorage();storageUI.open();};
$('closeStorage').onclick=()=>{storageId=null;guide=false;$('storagePanel').classList.add('hidden');};
function renderStorage(){const p=me(),s=state.structures.find(s=>s.id===storageId);if(!p||!s||dist(s,p)>3){$('closeStorage').click();return;}storageUI.update({p,s,inv:state.containers?.[storageId]||{},players:state.players,id});}

function terrainCameraDistance(origin,arm){const length=arm.length(),steps=Math.ceil(length/.25);for(let i=1;i<=steps;i++){const t=i/steps,position=origin.clone().addScaledVector(arm,t),coordinate=fromPoint(position),ground=vector(coordinate.x,coordinate.z,height(coordinate.x,coordinate.z,state.seed)),up=basis(coordinate.x,coordinate.z).up;if((position.x-ground.x)*up.x+(position.y-ground.y)*up.y+(position.z-ground.z)*up.z<.18)return length*t;}return Infinity;}
function visibleTerrainHit(hit){return !terrain.children.includes(hit.object)||hit.point.distanceTo(planet.patchCentre)>=78;}
const groundRay=new THREE.Raycaster();
const controls=bindControls({canvas,
 orbit:(dx,dy)=>{if(!joined||guide)return;yaw-=dx*.003;pitch=Math.max(-.08,Math.min(1.1,pitch+dy*.003));},
 groundClick:(x,y)=>{if(!joined||guide)return;if(buildMode){send({type:'build',piece:selected,x:piece?.x,z:piece?.z,rotation,site:piece?.site,gx:piece?.gx,gz:piece?.gz});return;}groundRay.setFromCamera(new THREE.Vector2(x/innerWidth*2-1,1-y/innerHeight*2),camera);const hit=groundRay.intersectObjects([terrain,planet.closeTerrain],true).find(visibleTerrainHit);if(hit){moveTarget=fromPoint(hit.point);stuckTime=0;}},
 interact:()=>{if(joined&&!guide){interact();lastGather=performance.now();}},
 build:()=>{if(!joined||guide)return;buildMode=!buildMode;moveTarget=null;updateHUD();},
 rotate:()=>rotation=(rotation+1)%4,
 place:()=>{if(joined&&!guide&&buildMode&&piece)send({type:'build',piece:selected,x:piece.x,z:piece.z,rotation,site:piece.site,gx:piece.gx,gz:piece.gz});},
 dismantle:()=>{if(joined&&!guide)dismantleNearest();},
 zoom:step=>distance=Math.max(2.5,Math.min(12,distance+step))
});
// Keep the play view compact; secondary actions remain available in the guide.
const extraActions=document.createElement('div');extraActions.className='secondary-actions';
$('guidePage-manual').prepend(extraActions);
for(const button of [...$('actionButtons').children]){
 if(button.id==='backpackAction')document.querySelector('.topright').prepend(button);
 else if(!['gatherAction','jumpAction'].includes(button.id)){extraActions.append(button);const action=button.onclick;if(action)button.onclick=event=>{guideOpen(false);action(event);};}
}
canvas.addEventListener('wheel',e=>{distance=Math.max(2.5,Math.min(12,distance+e.deltaY*.01));e.preventDefault();},{passive:false});
window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});
const gamepadReader=createGamepadReader();let padInput={x:0,z:0,sprint:false,gather:false},beltSlot=0,bindings=loadBindings(localStorage);
const controllerSettings=document.createElement('section');controllerSettings.innerHTML='<h3>PS5 / standard controller</h3><p id="controllerStatus" role="status">Connect with Bluetooth or USB, then press a controller button.</p><p class="guide-description">Left stick: move · Right stick: camera · Options: Field Guide · Create / View: Backpack · Circle: back. In menus, use the D-pad to focus controls and Cross to select. Account text entry still uses your keyboard or phone keyboard.</p><div id="controllerBindings"></div><button id="resetController">RESET BUTTON MAPPINGS</button>';$('guidePage-settings').append(controllerSettings);
function renderBindings(){const rows=$('controllerBindings');rows.replaceChildren();for(const[action,index]of Object.entries(bindings)){const row=document.createElement('label');row.className='controller-binding';row.textContent=ACTION_LABELS[action];const select=document.createElement('select');select.setAttribute('aria-label',ACTION_LABELS[action]);BUTTONS.forEach((name,i)=>{if([1,8,9].includes(i))return;const option=document.createElement('option');option.value=i;option.textContent=name;select.append(option);});select.value=index;select.onchange=()=>{const next=Number(select.value),other=Object.keys(bindings).find(k=>bindings[k]===next);if(other)bindings[other]=bindings[action];bindings[action]=next;localStorage.setItem('vc-controller-bindings',JSON.stringify(bindings));renderBindings();};row.append(select);rows.append(row);}}
renderBindings();$('resetController').onclick=()=>{bindings={...DEFAULT_BINDINGS};localStorage.removeItem('vc-controller-bindings');renderBindings();};
function closeControllerMenu(){for(const id of ['closeExpedition','closeStorage','closeGuide']){const b=$(id);if(b?.getClientRects().length){b.click();return;}}if(buildMode){buildMode=false;updateHUD();}}
function pollController(dt){let pads=[];try{pads=Array.from(navigator.getGamepads?.()||[]);}catch{}const pad=pads.find(p=>p?.connected&&p.mapping==='standard');const active=!document.hidden&&document.hasFocus();const input=gamepadReader.read(pad,active);padInput={x:0,z:0,sprint:false,gather:false};const label=pad?`Connected: ${pad.id}`:pads.some(p=>p?.connected)?'Controller detected, but this browser does not provide a standard mapping.':'Connect with Bluetooth or USB, then press a controller button.';if($('controllerStatus').textContent!==label)$('controllerStatus').textContent=label;if(!input.connected||!active)return;
 if(input.pressed[8]&&joined){toggleBackpack();return;}if(input.pressed[9]&&joined){if(guide)closeControllerMenu();else guideOpen(true);return;}if(input.pressed[1]){closeControllerMenu();return;}
 if(guide||!joined){const scope=['accountGate','expedition','storagePanel','guide','landing'].map($).find(el=>el&&!el.classList.contains('hidden'));if(!scope)return;if(scope.id==='storagePanel'&&storageUI.controller(input))return;const elements=[...scope.querySelectorAll('button:not(:disabled),input:not(:disabled),select:not(:disabled),a[href],summary')].filter(el=>el.getClientRects().length);const focus=document.activeElement,index=elements.indexOf(focus),step=input.pressed[13]||input.pressed[15]?1:input.pressed[12]||input.pressed[14]?-1:0;if(step){if(focus?.tagName==='SELECT'&&(input.pressed[14]||input.pressed[15])){focus.selectedIndex=Math.max(0,Math.min(focus.options.length-1,focus.selectedIndex+step));focus.dispatchEvent(new Event('change'));}else if(focus?.type==='range'&&(input.pressed[14]||input.pressed[15])){focus.value=String(Math.max(Number(focus.min),Math.min(Number(focus.max),Number(focus.value)+step*Number(focus.step||1))));focus.dispatchEvent(new Event('input',{bubbles:true}));}else{const next=elements[(index+step+elements.length)%elements.length];next?.focus();next?.scrollIntoView({block:'nearest'});}}if(input.pressed[0]){if(index<0)elements[0]?.focus();else focus.click();}return;}
 if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName))return;
 padInput={x:input.axes[0]||0,z:input.axes[1]||0,sprint:!!input.buttons[bindings.sprint],gather:!!input.buttons[bindings.primary]};yaw-=(input.axes[2]||0)*dt*2.4;pitch=Math.max(-.08,Math.min(1.1,pitch+(input.axes[3]||0)*dt*1.8));
 for(const[action,index]of Object.entries(bindings)){if(!input.pressed[index])continue;if(action==='jump')send({type:'jump'});if(action==='build')$('buildAction').click();if(action==='primary'){interact();lastGather=performance.now();}if(action==='rotate'&&buildMode)$('rotateAction').click();if(action==='light')send({type:'light'});if(action==='eat')send({type:'eat'});if(action==='storage')$('storageAction').click();if(action==='map')$('terminalAction').click();if(action==='use'&&!buildMode)terminal.useBelt(beltSlot);if(action==='previous'||action==='next'){const step=action==='next'?1:-1;if(buildMode){const options=Object.keys(RECIPES).filter(k=>!['cutter','flashlight','ration','rifle','repair'].includes(k));selected=options[(options.indexOf(selected)+step+options.length)%options.length];updateHUD();}else{beltSlot=(beltSlot+step+10)%10;for(const b of $('toolbelt').children)b.classList.toggle('controller-selected',Number(b.dataset.slot)===beltSlot);notify(`Belt slot ${beltSlot+1}`);}}}
}

const cameraRay=new THREE.Raycaster();
let lastActionHUD=0,last=performance.now(),frameCount=0,fpsTime=last,fps=0,previewKey='';
function animate(now){requestAnimationFrame(animate);const dt=Math.min(.05,(now-last)/1000);last=now;frameCount++;if(now-fpsTime>1000){fps=Math.round(frameCount*1000/(now-fpsTime));frameCount=0;fpsTime=now;}
 pollController(dt);const displayState=motionSampler.sample(now)||state;const p=me(),displayPlayer=displayState.players.find(q=>q.id===id)||p;if(joined&&p&&now-lastActionHUD>100){lastActionHUD=now;const action=contextAction(state,p,{buildMode,yaw});$('gatherAction').textContent=action?.label||'Action';$('gatherAction').disabled=!action;if(!buildMode)$('interaction').textContent=action?`[E] ${action.label}`:'Move closer or aim toward a target';}if(joined&&p){let mx=0,mz=0;if(!guide){const f=Number(!!keys.KeyW)-Number(!!keys.KeyS)-controls.input.z-padInput.z,r=Number(!!keys.KeyD)-Number(!!keys.KeyA)+controls.input.x+padInput.x;if(Math.abs(f)+Math.abs(r)>.05)moveTarget=null;mx=-Math.sin(yaw)*f+Math.cos(yaw)*r;mz=-Math.cos(yaw)*f-Math.sin(yaw)*r;const len=Math.hypot(mx,mz);if(len>1){mx/=len;mz/=len;}}
 if(!guide&&moveTarget){const dx=moveTarget.x-localPos.x,dz=moveTarget.z-localPos.z,len=Math.hypot(dx,dz);if(len<.3)moveTarget=null;else{mx=dx/len;mz=dz/len;}}
 const beforeMove=localPos.clone(),inputBasis=basis(localPos.x,localPos.z),oldArm={x:inputBasis.east.x*Math.sin(yaw)+inputBasis.south.x*Math.cos(yaw),y:inputBasis.east.y*Math.sin(yaw)+inputBasis.south.y*Math.cos(yaw),z:inputBasis.east.z*Math.sin(yaw)+inputBasis.south.z*Math.cos(yaw)};
 const sprint=!!(keys.ShiftLeft||keys.ShiftRight||controls.input.sprint||padInput.sprint),speed=sprint&&p.stamina>5&&p.charge>5?6.5:4.2;
 if(!p.vehicle&&!p.sleeping){const next=travel(localPos,mx*dt*speed,mz*dt*speed);if(!blocked(state,next.x,next.z)){localPos.x=next.x;localPos.z=next.z;}}else{const ride=displayState.vehicles?.find(v=>v.id===p.vehicle);localPos.x=ride?.x??p.x;localPos.z=ride?.z??p.z;}

 if(moveTarget){stuckTime=localPos.distanceTo(beforeMove)<.001?stuckTime+dt:0;if(stuckTime>.7){moveTarget=null;notify('Path blocked. Steer around the obstacle.');}}
 if(!mx&&!mz&&!p.vehicle){localPos.x=THREE.MathUtils.lerp(localPos.x,p.x,dt*12);localPos.z=THREE.MathUtils.lerp(localPos.z,p.z,dt*12);}
 const nextBasis=basis(localPos.x,localPos.z);if(beforeMove.distanceTo(localPos)>.001)yaw=Math.atan2(oldArm.x*nextBasis.east.x+oldArm.y*nextBasis.east.y+oldArm.z*nextBasis.east.z,oldArm.x*nextBasis.south.x+oldArm.y*nextBasis.south.y+oldArm.z*nextBasis.south.z);localPos.y=surface(state,localPos.x,localPos.z)+(displayPlayer.jumpHeight||0);if(now-lastInput>50){sendInput({x:mx,z:mz,vx:inputBasis.east.x*mx+inputBasis.south.x*mz,vy:inputBasis.east.y*mx+inputBasis.south.y*mz,vz:inputBasis.east.z*mx+inputBasis.south.z*mz,sprint,yaw,aimYaw:yaw+Math.PI});lastInput=now;}
 if((keys.KeyE||controls.input.gather||padInput.gather)&&!guide&&now-lastGather>(p.cutter?420:800)){interact(true);lastGather=now;}
 const b=basis(localPos.x,localPos.z),up=new THREE.Vector3(b.up.x,b.up.y,b.up.z),east=new THREE.Vector3(b.east.x,b.east.y,b.east.z),south=new THREE.Vector3(b.south.x,b.south.y,b.south.z);
 const ride=state.vehicles?.find(v=>v.id===p.vehicle),cameraDistance=distance+(ride?(ride.type==='crawler'?7:4):0);const focus=vector(localPos.x,localPos.z,localPos.y+(ride?2.5:1.4)),desired=focus.clone().addScaledVector(east,Math.sin(yaw)*cameraDistance*Math.cos(pitch)).addScaledVector(south,Math.cos(yaw)*cameraDistance*Math.cos(pitch)).addScaledVector(up,cameraDistance*Math.sin(pitch));camera.up.copy(up);planet.update(localPos);scatter?.update(localPos,state.structures,state.resources);

 const arm=desired.clone().sub(focus);cameraRay.set(focus,arm.clone().normalize());cameraRay.far=arm.length();const structureHit=cameraRay.intersectObjects(structuresGroup.children,true).find(h=>h.distance>.15&&h.object.geometry?.type!=='RingGeometry'),groundDistance=terrainCameraDistance(focus,arm),hitDistance=Math.min(structureHit?.distance??Infinity,groundDistance),obstruction=Number.isFinite(hitDistance);if(obstruction)desired.copy(focus).addScaledVector(arm.normalize(),Math.max(.4,hitDistance-.3));
 if(obstruction||camera.position.distanceTo(desired)>15)camera.position.copy(desired);else camera.position.lerp(desired,1-Math.exp(-14*dt));camera.lookAt(focus);camera.fov=THREE.MathUtils.lerp(camera.fov,sprint?61:55,1-Math.exp(-4*dt));camera.updateProjectionMatrix();

 if(buildMode&&!guide){piece={type:selected,...snapBuild(state,travel(localPos,-Math.sin(yaw)*4.5,-Math.cos(yaw)*4.5),selected),rotation};const err=placementError(state,staffTools.quickBuild()?{...p,unlocked:true}:p,piece,state.players)||(!staffTools.quickBuild()&&!canAfford(p,selected)?'Not enough resources.':'');const pk=JSON.stringify(piece)+!!err;if(pk!==previewKey){previewKey=pk;clearGroup(preview);const obj=pieceMesh(piece,true);obj.traverse(o=>{if(o.material)o.material.color.set(err?0xff766d:0xb9f1c7);});preview.add(obj);}$('buildHint').textContent=`${staffTools.quickBuild()?'ADMIN · ':''}${RECIPES[selected].name} · ${err||'VALID — click to place'} · Rotate / Place buttons`;preview.visible=true;}else preview.visible=false;
 }else if(!id){const t=now*.000025;camera.position.set(16+Math.sin(t)*8,13,26);camera.lookAt(7,1,-9);}
 const online=new Set(state.players.map(p=>p.id));for(const [key,a] of avatars)if(!online.has(key)){scene.remove(a);avatars.delete(key);}
 for(const player of displayState.players){let a=avatars.get(player.id);if(a&&fieldArtReady()&&!a.userData.art){scene.remove(a);avatars.delete(player.id);a=null;}if(!a){a=astronaut(player.id===id?0xb6d4c2:0xebac87);if(player.id!==id){const tag=document.createElement('canvas');tag.width=256;tag.height=64;const ctx=tag.getContext('2d');ctx.fillStyle='#132a31d9';ctx.fillRect(0,0,256,64);ctx.fillStyle='#e6f7e8';ctx.font='bold 26px sans-serif';ctx.textAlign='center';ctx.fillText(player.name,128,41,240);const label=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(tag),depthTest:false}));label.position.y=2.4;label.scale.set(2.3,.575,1);a.add(label);}scene.add(a);avatars.set(player.id,a);a.position.copy(vector(player.x,player.z,surface(state,player.x,player.z)+(player.jumpHeight||0)));}
 const target=player.id===id?vector(localPos.x,localPos.z,localPos.y):vector(player.x,player.z,surface(state,player.x,player.z)+(player.jumpHeight||0));const displacement=a.position.distanceTo(target),moving=displacement>.003,speed=Math.min(8,displacement*(player.id===id?1:Math.min(1,dt*12))/Math.max(.001,dt));a.position.lerp(target,player.id===id?1:Math.min(1,dt*12));orient(a,player.x,player.z);a.rotateY(player.yaw);a.visible=!player.vehicle;if(a.userData.art)animateFieldModel(a,{dt,time:now/1000,speed,jump:player.jumpHeight||0,action:player.id===id?Math.max(0,(visualActionUntil-now)/650):0,sprint:speed>4.5,sleeping:player.sleeping,cutter:player.cutter,rifle:player.rifle});else for(let i=0;i<a.userData.legs.length;i++)a.userData.legs[i].rotation.x=moving?Math.sin(now*.012+i*Math.PI)*.4:0;
 }
 if(ruinPulse){ruinPulse.rotation.y=now*.001;ruinPulse.position.y=1.7+Math.sin(now*.002)*.15;}
 const light=sunlight(state.time,state.planet,localPos),blend=1-Math.exp(-dt*2);skyLight.intensity+=(.25+light.daylight*.9-skyLight.intensity)*blend;sun.intensity+=(light.direct*3.1*light.irradiance-sun.intensity)*blend;
 const skyColor=new THREE.Color('#0c142b').lerp(new THREE.Color('#718f96'),light.daylight).lerp(new THREE.Color('#c98572'),light.twilight*.5);scene.background.lerp(skyColor,blend);sun.color.lerp(new THREE.Color('#ffd8ad').lerp(new THREE.Color('#ff9d65'),light.twilight),blend);
 const centre=joined?vector(localPos.x,localPos.z,localPos.y):new THREE.Vector3();const lightBasis=basis(localPos.x,localPos.z);skyLight.position.set(lightBasis.up.x,lightBasis.up.y,lightBasis.up.z);sun.position.copy(centre).addScaledVector(new THREE.Vector3(light.direction.x,light.direction.y,light.direction.z),48);sun.target.position.copy(centre);sun.target.updateMatrixWorld();skyAtmosphere.update(camera,light,state.time,lightBasis.up);scene.fog.color.copy(scene.background);wildlife.update(displayState,dt,id,yaw,shape);vehicles.update(displayState,dt,now/1000);
 const storm=joined&&state.time%150>=105;scene.fog.density=storm?.026:.012;renderer.render(scene,camera);
}
const belt=document.createElement('div');belt.id='toolbelt';$('hotbar').after(belt);for(let i=0;i<10;i++){const button=document.createElement('button');button.dataset.slot=i;button.textContent=`${(i+1)%10} —`;button.onclick=()=>terminal.useBelt(i);belt.append(button);}
const terminal=expeditionUI({get:()=>({state,player:me()?{...me(),role:staffTools.role(),quickBuild:staffTools.quickBuild()}:null}),send,pause:open=>{guide=open;keys={};controls.reset();moveTarget=null;sendInput({x:0,z:0});},notify,attack});
buildEnvironment(state.seed);void loadFieldArt().then(ready=>{if(ready)buildEnvironment(state.seed);});requestAnimationFrame(animate);
window.vibeAudioDiagnostics=()=>({...audio.status(),preferences:audioSettings.get()});
// Read-only diagnostics for repeatable browser verification; no gameplay mutation API.
function coralFluxDiagnostics(){camera.updateMatrixWorld();const frustum=new THREE.Frustum().setFromProjectionMatrix(new THREE.Matrix4().multiplyMatrices(camera.projectionMatrix,camera.matrixWorldInverse)),width=renderer.domElement.clientWidth,height=renderer.domElement.clientHeight;return coralFluxGroup.children.map(group=>{const bounds=new THREE.Box3().setFromObject(group),{min,max}=bounds,corners=[];for(const x of[min.x,max.x])for(const y of[min.y,max.y])for(const z of[min.z,max.z])corners.push(new THREE.Vector3(x,y,z).project(camera));return{id:group.userData.coralFluxId,depleted:group.userData.depleted,parts:group.children.length,inFrustum:frustum.intersectsBox(bounds),screenWidth:(Math.max(...corners.map(point=>point.x))-Math.min(...corners.map(point=>point.x)))*width/2,screenHeight:(Math.max(...corners.map(point=>point.y))-Math.min(...corners.map(point=>point.y)))*height/2};});}
function coralShelfEnvironmentDiagnostics(){const instances=planet?.environment?.children[0],parts=instances?.count||0;camera.updateMatrixWorld();const frustum=new THREE.Frustum().setFromProjectionMatrix(new THREE.Matrix4().multiplyMatrices(camera.projectionMatrix,camera.matrixWorldInverse));return{formations:parts/5,parts,instanced:instances?.isInstancedMesh===true,role:instances?.userData.role||null,inFrustum:parts>0&&frustum.intersectsObject(instances)};}
function coralCrownDiagnostics(){const crowns=planet?.landmarks?.children.filter(group=>group.userData.landmark?.id==='coral-crown')||[],crown=crowns[0];return{count:crowns.length,visible:crown?.visible===true,parts:crown?.children.length||0};}
function brokenSignalRingDiagnostics(){let authored=0,fallback=0,details=null;worldGroup.traverse(object=>{if(object.name==='broken-signal-ring'){authored++;details={...object.userData};}if(object.name==='broken-signal-ring-fallback')fallback++;});return{state:brokenSignalRingState,authored,fallback,details};}
window.vibeRailingDiagnostics=()=>{const previewRailing=selected==='railing'&&piece?{rotation:piece.rotation,parts:preview.children[0]?.children.length||0}:null,renderedRailings=structuresGroup.children.filter(group=>group.userData.pieceType==='railing').map(group=>{const structure=state.structures.find(s=>s.id===group.userData.pieceId);return{id:structure.id,rotation:structure.rotation,parts:group.children.length};});return{previewRailing,renderedRailings};};
window.vibeCampGateDiagnostics=()=>{const previewGroup=preview.children[0],previewLeaf=previewGroup?.children[2],previewGate=selected==='campGate'&&piece?{rotation:piece.rotation,parts:previewGroup?.children.length||0,leafSpan:Math.max(previewLeaf?.geometry.parameters.width||0,previewLeaf?.geometry.parameters.depth||0)}:null,renderedGates=structuresGroup.children.filter(group=>group.userData.pieceType==='campGate').map(group=>{const structure=state.structures.find(s=>s.id===group.userData.pieceId);return{id:structure.id,rotation:structure.rotation,open:structure.open,parts:group.children.length};});return{previewGate,renderedGates};};
Object.defineProperty(window,'vibeDiagnostics',{get:()=>{const panelSlope=panel=>{panel.updateWorldMatrix(true,false);return{xRotation:panel.rotation.x,yRotation:panel.rotation.y,worldNormal:new THREE.Vector3(0,1,0).transformDirection(panel.matrixWorld).toArray()};},previewPanel=selected==='angledCanopy'?preview.children[0]?.children[0]:null,previewStair=selected==='stairs'&&piece?{...stairProfile(state,piece),rotation:piece.rotation}:null,renderedAngledCanopies=structuresGroup.children.filter(group=>group.userData.pieceType==='angledCanopy').map(group=>panelSlope(group.children[0])),renderedStairs=structuresGroup.children.filter(group=>group.userData.pieceType==='stairs').map(group=>{const structure=state.structures.find(s=>s.id===group.userData.pieceId),ramp=group.children[0],profile=stairProfile(state,structure);return{rotation:structure.rotation,angle:profile.angle,rotationX:ramp.rotation.x,rotationZ:ramp.rotation.z,outer:profile.outer,inner:profile.inner};}),renderedDoors=structuresGroup.children.filter(group=>group.userData.pieceType==='door').map(group=>({id:group.userData.pieceId,open:group.userData.open,parts:group.children.length}));return{art:fieldArtState(),animatedAvatars:[...avatars.values()].filter(a=>a.userData.art).map(a=>({model:a.userData.model,animation:a.userData.animation})),connected:joined,reconnectActive:reconnect.active,reconnectPending:reconnect.pending,id,player:me()?structuredClone(me()):null,state:structuredClone(state),snapshotRevision,fps,drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,avatars:avatars.size,creatures:wildlife.count(),night:daylight(state.time,state.settings).night,cameraPosition:camera.position.toArray(),cameraUp:camera.up.toArray(),terrainChunks:terrain.children.length,localPosition:localPos.toArray(),surfaceAtPlayer:surface(state,localPos.x,localPos.z),biome:currentBiome?structuredClone(currentBiome):null,landmark:currentLandmark?structuredClone(currentLandmark):null,coralFluxDeposits:coralFluxDiagnostics(),coralShelfEnvironment:coralShelfEnvironmentDiagnostics(),coralCrown:coralCrownDiagnostics(),brokenSignalRing:brokenSignalRingDiagnostics(),webgl:renderer.capabilities.isWebGL2,buildMode,selected,preview:piece?{...piece}:null,previewParts:preview.children[0]?.children.length??0,previewSlope:previewPanel?panelSlope(previewPanel):null,previewStair,renderedAngledCanopies,renderedStairs,renderedDoors,inputAck:inputReconciler.latestAck,pendingInputs:inputReconciler.pendingCount};}});
