import {RECIPES,RESOURCES} from '/shared/world.js';
const group=key=>['fabricator','cutter','flashlight','repair','rifle'].includes(key)?'Tools':['floor','wall','doorway','roof','angledCanopy','stairs','railing','perimeter','campGate','door','airlock'].includes(key)?'Building':key==='ration'?'Food':'Equipment';
export function createRecipeBrowser({player}){const root=document.createElement('section');root.className='recipe-browser';root.innerHTML='<label for="recipeSearch">Find a recipe</label><input id="recipeSearch" type="search" placeholder="Search tools, structures, ingredients"><div id="recipeCategories" class="secondary-actions"></div><div id="pinnedRecipe" class="pinned-recipe" aria-live="polite"></div><p id="recipeEmpty" class="hidden">No recipes match this search.</p>';document.getElementById('recipes').before(root);const $=id=>document.getElementById(id);let category='All',pinned=null,loadedId=null,summaryKey='';
 function load(){const p=player();if(p?.id===loadedId)return;loadedId=p?.id;pinned=null;try{pinned=localStorage.getItem('vc-recipe-pin:'+loadedId);}catch{}if(!Object.hasOwn(RECIPES,pinned))pinned=null;}
 function summary(){load();const p=player(),panel=$('pinnedRecipe'),nextKey=JSON.stringify([loadedId,pinned,pinned?Object.keys(RECIPES[pinned].cost).map(k=>p?.inventory[k]):[]]);if(summaryKey===nextKey)return;summaryKey=nextKey;panel.replaceChildren();if(!pinned||!p)return;const title=document.createElement('b');title.textContent=`Tracking: ${RECIPES[pinned].name}`;panel.append(title);for(const[item,needed]of Object.entries(RECIPES[pinned].cost)){const line=document.createElement('div'),have=p.inventory[item]||0;line.textContent=`${RESOURCES[item].name}: ${have}/${needed}${have<needed?` · need ${needed-have}`:' ✓'}`;panel.append(line);}const clear=document.createElement('button');clear.textContent='UNPIN';clear.onclick=()=>{pinned=null;try{localStorage.removeItem('vc-recipe-pin:'+loadedId);}catch{}summary();};panel.append(clear);}
 function filter(){const query=$('recipeSearch').value.toLowerCase().trim();let count=0;for(const row of document.querySelectorAll('#recipes .recipe')){const key=row.dataset.recipe;if(!key)continue;const match=(category==='All'||group(key)===category)&&`${RECIPES[key].name} ${RECIPES[key].description} ${Object.keys(RECIPES[key].cost).map(k=>RESOURCES[k].name).join(' ')}`.toLowerCase().includes(query);row.classList.toggle('hidden',!match);if(match)count++;}$('recipeEmpty').classList.toggle('hidden',count>0);}
 for(const name of ['All','Tools','Building','Equipment','Food']){const b=document.createElement('button');b.textContent=name;b.setAttribute('aria-pressed',String(name===category));b.onclick=()=>{category=name;for(const button of $('recipeCategories').children)button.setAttribute('aria-pressed',String(button===b));filter();};$('recipeCategories').append(b);}$('recipeSearch').oninput=filter;
 return{decorate(row,key,p){row.dataset.recipe=key;const costs=row.querySelector('small');if(costs)costs.textContent=Object.entries(RECIPES[key].cost).map(([item,n])=>`${p.inventory[item]||0}/${n} ${RESOURCES[item].name}`).join(' · ')||'Included in your suit kit';const pin=document.createElement('button');pin.textContent='TRACK';pin.className='pin-recipe';pin.setAttribute('aria-label',`Track ${RECIPES[key].name}`);pin.onclick=()=>{load();pinned=key;try{localStorage.setItem('vc-recipe-pin:'+loadedId,key);}catch{}summary();};row.append(pin);},refresh(){filter();summary();}};
}
