import {itemIcon} from './item-icons.js';
import {RESOURCES,itemCount} from '/shared/world.js';

// Keep slot nodes alive across snapshots: controller/keyboard focus must survive transfers.
export function createStorageUI({send,notify}){
 const $=id=>document.getElementById(id),slots=new Map(),items=Object.keys(RESOURCES);let current=null,selected=null,accessKey='';

 function select(slot){selected=slot;for(const b of slots.values())b.classList.toggle('selected',b===slot);$('storageSelected').textContent=RESOURCES[slot.dataset.item].name;$('storageDirection').textContent=slot.dataset.direction==='deposit'?'BACKPACK → LOCKER':'LOCKER → BACKPACK';}
 function transfer(slot,whole=false){if(!current)return;select(slot);const{p,inv,id}=current,direction=slot.dataset.direction,item=slot.dataset.item,from=direction==='deposit'?p.inventory:inv,to=direction==='deposit'?inv:p.inventory,cap=direction==='deposit'?200:60,available=from[item]||0,raw=$('transferAmount').value,quantity=whole?200:Number(raw);if(!Number.isInteger(quantity)||quantity<1||quantity>200){notify('Choose a transfer amount from 1 to 200.');return;}const amount=Math.min(quantity,available,cap-itemCount(to));if(!available){notify(`No ${RESOURCES[item].name} in this inventory.`);return;}if(amount<1){notify('Destination is full.');return;}send({type:'transfer',id,item,direction,amount});}
 for(const direction of ['deposit','withdraw']){const grid=$(direction==='deposit'?'backpackGrid':'lockerGrid');for(const item of items){const slot=document.createElement('button');slot.type='button';slot.className='inventory-slot';slot.dataset.item=item;slot.dataset.direction=direction;slot.style.setProperty('--item-color',`#${RESOURCES[item].color.toString(16).padStart(6,'0')}`);slot.innerHTML=`${itemIcon(item)}<span class="slot-name"></span><b class="slot-count"></b>`;slot.querySelector('.slot-name').textContent=RESOURCES[item].name;slot.onfocus=()=>select(slot);slot.onclick=e=>transfer(slot,e.shiftKey);slots.set(`${direction}:${item}`,slot);grid.append(slot);}}
 for(const amount of [1,5,10,200]){const button=document.createElement('button');button.type='button';button.textContent=amount===200?'ALL':String(amount);button.setAttribute('aria-label',amount===200?'Transfer whole stack':`Transfer up to ${amount}`);button.onclick=()=>{$('transferAmount').value=String(amount);};$('storageAmounts').append(button);}
 for(const[mode,label]of [['matching','Store matching'],['deposit','Store all'],['withdraw','Take all']]){const b=document.createElement('button');b.textContent=label;b.onclick=()=>{if(current)send({type:'transferBulk',id:current.id,mode});};$('storageBulk').append(b);}
 $('storageTransfer').onclick=()=>{if(selected)transfer(selected);};
 function focusSlot(direction,index){const slot=slots.get(`${direction}:${items[index]}`);slot?.focus();slot?.scrollIntoView({block:'nearest'});}
 function navigate(key){const focus=document.activeElement;if(!focus?.classList.contains('inventory-slot'))return false;let direction=focus.dataset.direction,i=items.indexOf(focus.dataset.item);if(key==='panel'){direction=direction==='deposit'?'withdraw':'deposit';}else if(key==='left'){if(i%4===0&&direction==='withdraw'){direction='deposit';i=Math.min(items.length-1,i+3);}else i=Math.max(0,i-1);}else if(key==='right'){if((i%4===3||i===items.length-1)&&direction==='deposit'){direction='withdraw';i-=i%4;}else i=Math.min(items.length-1,i+1);}else if(key==='up'){if(i<4){$('closeStorage').focus();return true;}i-=4;}else if(key==='down'){if(i+4>=items.length){$('transferAmount').focus();return true;}i+=4;}else return false;focusSlot(direction,i);return true;}
 $('storagePanel').addEventListener('keydown',e=>{if(navigate({ArrowLeft:'left',ArrowRight:'right',ArrowUp:'up',ArrowDown:'down'}[e.key]))e.preventDefault();});
 return{
  open(){if(current?.locked)$('storageAccess').open=true;const direction='deposit',i=Math.max(0,items.findIndex(item=>(current?.p.inventory[item]||0)>0));focusSlot(direction,i);},
  controller(input){const key=input.pressed[4]||input.pressed[5]?'panel':input.pressed[12]?'up':input.pressed[13]?'down':input.pressed[14]?'left':input.pressed[15]?'right':null;if(key&&navigate(key))return true;return false;},
  update({p,s,inv,players,id}){current={p,inv,id:s.id,locked:s.canAccessCargo===false};$('storageCapacity').textContent=`Locker: ${itemCount(inv)}/200 · Backpack: ${itemCount(p.inventory)}/60`;$('backpackCapacity').textContent=`${itemCount(p.inventory)} / 60`;$('lockerCapacity').textContent=`${itemCount(inv)} / 200`;$('backpackFill').value=itemCount(p.inventory);$('lockerFill').value=itemCount(inv);
   for(const[code,slot]of slots){const count=(slot.dataset.direction==='deposit'?p.inventory:inv)[slot.dataset.item]||0;slot.querySelector('.slot-count').textContent=count;slot.classList.toggle('empty',count===0);slot.setAttribute('aria-label',`${slot.dataset.direction==='deposit'?'Store':'Take'} ${RESOURCES[slot.dataset.item].name}, ${count} available`);}
   const granted=Array.isArray(s.cargoGrantedTo)?s.cargoGrantedTo:null,newKey=JSON.stringify([s.id,granted,players.map(p=>[p.id,p.name])]);if(accessKey===newKey)return;accessKey=newKey;
   const manager=$('cargoAccessManager'),roster=$('cargoAccessRoster'),candidate=$('cargoAccessCandidate'),grant=$('grantCargoAccess'),previous=candidate.value,focused=roster.contains(document.activeElement)?document.activeElement.getAttribute('aria-label'):null;manager.classList.toggle('hidden',!granted);roster.replaceChildren();candidate.replaceChildren();if(granted){const ids=new Set(granted.map(p=>p.id));for(const p of players.filter(p=>p.id!==id&&!ids.has(p.id))){const option=document.createElement('option');option.value=p.id;option.textContent=p.name;candidate.append(option);}if([...candidate.options].some(o=>o.value===previous))candidate.value=previous;grant.disabled=!candidate.options.length;grant.onclick=()=>send({type:'cargoAccess',id:s.id,target:candidate.value,allow:true});for(const p of granted){const row=document.createElement('div');row.className='cargo-access-row';const name=document.createElement('span');name.textContent=p.name;const revoke=document.createElement('button');revoke.textContent='REVOKE';revoke.setAttribute('aria-label',`Revoke cargo access for ${p.name}`);revoke.onclick=()=>send({type:'cargoAccess',id:s.id,target:p.id,allow:false});row.append(name,revoke);roster.append(row);}}if(focused){const restore=[...roster.querySelectorAll('button')].find(b=>b.getAttribute('aria-label')===focused);(restore||(!grant.disabled?grant:candidate)).focus();}
  }
 };
}
