// Isolated fixtures seed crafting materials only; all account and storage actions use the UI.
import {chromium} from 'playwright';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {startTestServer as startServer} from './auth-helper.js';import {browserAccount} from './auth-helper.js';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'vibe-cargo-')),app=startServer({port:0,host:'127.0.0.1',saveFile:path.join(dir,'world.json')});await new Promise(r=>app.server.once('listening',r));const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}),a=await browser.newPage({viewport:{width:1400,height:900}}),b=await browser.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true}),errors=[];for(const p of[a,b])p.on('pageerror',e=>errors.push(e.message));
try{
for(const [i,p]of[a,b].entries()){await p.goto(`http://localhost:${app.server.address().port}`);await browserAccount(p,'Explorer '+i);}
for(const name of['Second','Third']){await a.locator('#characterName').fill(name);await a.locator('#createCharacter').click();await a.waitForFunction(n=>[...document.querySelector('#character').options].some(o=>o.text===n),name);}assert.equal(await a.locator('#createCharacter').isEnabled(),false);await a.locator('#character').selectOption({label:'Explorer 0'});
for(const p of[a,b]){await p.locator('#enter').click();await p.waitForFunction(()=>window.vibeDiagnostics.connected);}
const aid=await a.evaluate(()=>window.vibeDiagnostics.id),bid=await b.evaluate(()=>window.vibeDiagnostics.id),pa=app.game.world.players[aid],pb=app.game.world.players[bid];Object.assign(pa.inventory,{ferrite:20,fiber:5});pa.x=-9;pa.z=4.5;await a.waitForTimeout(400);await a.locator('#buildAction').click();await a.locator('[data-piece="cargo"]').click();await a.locator('#gatherAction').click();await a.waitForFunction(()=>window.vibeDiagnostics.state.structures.some(s=>s.type==='cargo'));await a.locator('#buildAction').click();pa.z=2;pb.x=-8;pb.z=2;await a.waitForTimeout(500);
for(const p of[a,b])await p.locator('#gatherAction').click();await a.locator('#transferAmount').fill('5');await a.locator('[data-direction=deposit][data-item=ferrite]').click();await b.waitForFunction(()=>document.querySelector('#storageCapacity').textContent.includes('Locker: 5/200'));await b.locator('#transferAmount').fill('5');await b.locator('[data-direction=withdraw][data-item=ferrite]').click();await a.waitForFunction(()=>document.querySelector('#storageCapacity').textContent.includes('Locker: 0/200'));assert.equal(pb.inventory.ferrite,5);assert.equal(pa.inventory.ferrite,9);await b.screenshot({path:'docs/screenshots/phone-storage.png'});await a.screenshot({path:'docs/screenshots/cargo-storage.png'});await a.locator('#closeStorage').click();await a.reload();await a.locator('#findGame').click();await a.waitForFunction(()=>document.querySelector('#character').options.length===3);await a.locator('#character').selectOption({label:'Explorer 0'});await a.locator('#enter').click();await a.waitForFunction(()=>window.vibeDiagnostics.connected);assert.equal(await a.evaluate(()=>window.vibeDiagnostics.player.inventory.ferrite),9);assert.deepEqual(errors,[]);console.log('PASS: account signup, three selectable characters, cargo construction, two-client deposit/withdraw, reload persistence, desktop/phone storage UI.');
}finally{await browser.close();await app.close();fs.rmSync(dir,{recursive:true});}
