import {randomUUID} from 'node:crypto';import {startServer as realServer} from '../server/index.js';
// Isolated email transport fixture. Verification still traverses the real token, expiry and account code.
export const mailbox=new Map(),recoveryMailbox=new Map();export function startTestServer(options){return realServer({...options,mailer:async(email,url)=>{const link=new URL(url),verification=link.searchParams.get('verify');if(verification)mailbox.set(email,verification);else recoveryMailbox.set(email,url);}});}
export async function browserAccount(page,name='Explorer'){
 const profile=await page.request.get(new URL('/api/account',page.url()).href).then(r=>r.json());
 if(!profile.profile){const username='test_'+randomUUID().replaceAll('-','').slice(0,16),email=username+'@example.invalid';await page.locator('#username').fill(username);await page.locator('#password').fill(randomUUID());await page.locator('#signupEmail').fill(email);await page.locator('#signupTerms').check();await page.locator('#registerAccount').click();await page.locator('#verifyActions').waitFor({state:'visible'});const code=mailbox.get(email);if(!code)throw Error('Verification fixture did not receive email');const response=await page.request.post(new URL('/api/account',page.url()).href,{data:{action:'verify',code}});if(!response.ok())throw Error(await response.text());await page.locator('#checkVerification').click();await page.locator('#continueVerification').click();}
 await page.locator('#findGame').click();if(!profile.profile?.characters.length){await page.locator('#characterName').fill(name);await page.locator('#createCharacter').click();}await page.waitForFunction(()=>document.querySelector('#character').options.length>0);
}
export async function apiAccount(base,n){const username='test_'+randomUUID().replaceAll('-','').slice(0,16),email=username+'@example.invalid';const r=await fetch(base+'/api/account',{method:'POST',headers:{'Content-Type':'application/json','x-forwarded-for':'127.0.0.'+(n+1)},body:JSON.stringify({action:'register',username,password:randomUUID(),email,terms:true,marketing:false})});if(!r.ok)throw Error(await r.text());const cookie=r.headers.get('set-cookie').split(';')[0];const headers={'Content-Type':'application/json',cookie};const verified=await fetch(base+'/api/account',{method:'POST',headers,body:JSON.stringify({action:'verify',code:mailbox.get(email)})});if(!verified.ok)throw Error(await verified.text());const c=await fetch(base+'/api/account',{method:'POST',headers,body:JSON.stringify({action:'character',name:'Explorer '+n})}).then(r=>r.json());return{cookie,character:c.profile.characters[0].id};}
