import test from 'node:test';import assert from 'node:assert/strict';import {Game} from '../server/game.js';import {makeWorld,placementError,blocked,shape} from '../shared/world.js';import {daylight,spawnCreatures,activeCreature} from '../shared/ecology.js';import {dailyBackup} from '../server/daily-save.js';import {catalog} from '../server/catalog.js';
function setup(){const g=new Game();const p=g.join('test','Explorer');g.world.creatures=[];return{g,p};}
function c(type,x=20,z=20){return{...spawnCreatures(1).find(c=>c.type===type),x,z,homeX:x,homeZ:z,attackAt:0};}
test('one server listed, creation disabled and schedule fixed in UTC',()=>{assert.deepEqual(catalog(3).servers.map(s=>[s.id,s.players,s.maxPlayers,s.dailySaveUTC]),[['quiet-basin',3,50,'00:00']]);assert.equal(catalog().creationEnabled,false);});
test('shared day/night wraps; medium predator exists only at night',()=>{assert.equal(daylight(359).night,false);assert.equal(daylight(360).night,true);assert.equal(daylight(600).day,2);assert.equal(activeCreature(c('prowler'),10),false);assert.equal(activeCreature(c('prowler'),400),true);assert.equal(activeCreature(c('grazer'),400),true);assert.equal(activeCreature(c('skitter'),10),true);});
test('neutral never attacks, small attacks by day and night, medium only at night',()=>{for(const type of ['grazer','skitter','prowler'])for(const time of [10,400]){const {g,p}=setup();p.x=20;p.z=21;g.world.time=time===400?g.world.settings.daySeconds+10:time;g.world.creatures=[c(type)];g.tick(.05);assert.equal(p.health<100,type==='skitter'||(type==='prowler'&&time===400),`${type} at ${time}`);}});
test('walls block creature movement and attacks across them',()=>{const{g,p}=setup();p.x=21;p.z=20.2;g.world.creatures=[c('skitter',21,18)];g.world.structures=[{type:'perimeter',x:21,z:21,rotation:0}];for(let i=0;i<30;i++)g.tick(.05);assert.equal(p.health,100);assert.ok(g.world.creatures[0].z<19.1);});
test('hunt, prepare and eat food; kill cannot be rewarded twice',()=>{const {g,p}=setup();p.x=20;p.z=21;p.cutter=true;p.inventory.fiber=1;const prey=c('grazer');g.world.creatures=[prey];assert.equal(g.action(p.id,{type:'attack',id:prey.id}).ok,true);g.tick(.7);prey.x=20;prey.z=20;assert.equal(g.action(p.id,{type:'attack',id:prey.id}).ok,true);assert.equal(p.inventory.meat,2);g.tick(.7);assert.equal(g.action(p.id,{type:'attack',id:prey.id}).ok,false);assert.equal(p.inventory.meat,2);assert.equal(g.action(p.id,{type:'craft',recipe:'ration'}).ok,true);p.health=40;assert.equal(g.action(p.id,{type:'eat'}).ok,true);assert.equal(p.health,75);assert.equal(p.inventory.ration,0);});
test('perimeter needs no foundation; building wall does; lamp requires supporting edge',()=>{const{g,p}=setup();p.x=9;p.z=3;const piece={type:'perimeter',x:9,z:0,rotation:0};assert.equal(placementError(g.world,p,piece),'');assert.match(placementError(g.world,p,{...piece,type:'wall'}),/deck/);assert.match(placementError(g.world,p,{...piece,type:'lamp'}),/wall/);g.world.structures.push(piece);assert.equal(placementError(g.world,p,{...piece,type:'lamp'}),'');assert.ok(blocked(g.world,9,-1.5));assert.equal(shape({...piece,type:'lamp'},g.world.seed).z,-1.3);});
test('flashlight requires crafting, drains suit battery, turns off at zero',()=>{const{g,p}=setup();assert.equal(g.action(p.id,{type:'light'}).ok,false);p.inventory.ferrite=2;p.inventory.crystal=1;assert.equal(g.action(p.id,{type:'craft',recipe:'flashlight'}).ok,true);g.action(p.id,{type:'light'});g.tick(1);assert.ok(Math.abs(p.charge-99.11)<.001);p.charge=.1;g.tick(1);assert.equal(p.flashlightOn,false);});
test('old saves upgrade without losing structures, inventory or time',()=>{const w=makeWorld();w.time=291;w.structures=[{id:'old',type:'floor',x:9,z:0}];w.players.old={id:'old',inventory:{ferrite:17},health:50};const g=new Game(w);assert.equal(g.world.time,291);assert.equal(g.world.structures[0].id,'old');assert.equal(g.world.players.old.inventory.ferrite,17);assert.equal(g.world.players.old.inventory.ration,0);assert.equal(g.world.creatures.length,12);});
test('daily snapshot uses a UTC key, is idempotent and retains current save',async()=>{const saved=new Map(),raw=JSON.stringify({world:{seed:42}});const store={key:'isolated',read:async()=>raw,command:async([cmd,key,value,...opts])=>{assert.equal(cmd,'SET');assert.deepEqual(opts,['NX','EX',691200]);if(saved.has(key))return null;saved.set(key,value);return'OK';}};const date=new Date('2026-09-17T00:00:00Z');assert.equal((await dailyBackup(store,date)).saved,true);assert.equal((await dailyBackup(store,date)).alreadySaved,true);assert.equal(saved.get('isolated:daily:2026-09-17'),raw);});
