import {browserAccount} from './auth-helper.js';
// Isolated fixture world: exercises new night-time interactions without editing the live world.
import {chromium} from 'playwright';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {startServer} from '../server/index.js';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'vibe-night-')),app=startServer({port:0,host:'127.0.0.1',saveFile:path.join(dir,'world.json')});await new Promise(r=>app.server.once('listening',r));app.game.world.time=390;
const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}),page=await browser.newPage({viewport:{width:1365,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
try{await page.goto(`http://localhost:${app.server.address().port}`);assert.equal(await page.locator('#joinForm').isVisible(),false);await page.locator('#findGame').click();assert.equal(await page.locator('#createServer').isEnabled(),false);await browserAccount(page,'Night');await page.locator('#enter').click();await page.waitForFunction(()=>window.vibeDiagnostics.connected&&window.vibeDiagnostics.creatures===12&&window.vibeDiagnostics.night);
const id=await page.evaluate(()=>window.vibeDiagnostics.id),player=app.game.world.players[id];player.inventory.ferrite=20;player.inventory.crystal=10;player.inventory.fiber=10;player.inventory.meat=1;player.x=9;player.z=4.5;await page.waitForTimeout(350);
await page.locator('#menuButton').click();await page.locator('.recipe').filter({has:page.locator('b',{hasText:'Suit flashlight'})}).locator('button').click();await page.waitForFunction(()=>window.vibeDiagnostics.player.flashlightOwned);await page.locator('.recipe').filter({has:page.locator('b',{hasText:'Field meal'})}).locator('button').click();await page.waitForFunction(()=>window.vibeDiagnostics.player.inventory.ration===1);await page.locator('#closeGuide').click();
await page.locator('#lightAction').click();await page.waitForFunction(()=>window.vibeDiagnostics.player.flashlightOn);const charge=player.charge;await page.waitForTimeout(1000);assert.ok(player.charge<charge-.5);
player.health=50;await page.locator('#eatAction').click();await page.waitForFunction(()=>window.vibeDiagnostics.player.health===85);
await page.locator('[data-piece="perimeter"]').click();await page.waitForTimeout(700);await page.locator('#placeAction').click();await page.waitForFunction(()=>window.vibeDiagnostics.state.structures.some(s=>s.type==='perimeter'));
await page.locator('[data-piece="lamp"]').click();await page.waitForTimeout(350);await page.locator('#placeAction').click();await page.waitForFunction(()=>window.vibeDiagnostics.state.structures.some(s=>s.type==='lamp'));await page.locator('#buildAction').click();await page.waitForTimeout(3600);await page.screenshot({path:'docs/screenshots/night-lights.png'});
// Daybreak hides only night predators on both simulation snapshots and renderer.
app.game.world.time=610;await page.waitForFunction(()=>!window.vibeDiagnostics.night&&window.vibeDiagnostics.creatures===10);await page.screenshot({path:'docs/screenshots/day-creatures.png'});assert.deepEqual(errors,[]);console.log('Server browser, night creatures, crafted flashlight, food, barrier and wall light verified in isolated browser world.');
}finally{await browser.close();await app.close();fs.rmSync(dir,{recursive:true});}
