// Local fixtures supply materials and distant positions; UI and network actions are real.
import {chromium} from 'playwright';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {startTestServer,browserAccount} from './auth-helper.js';import {CIRCUMFERENCE} from '../shared/planet.js';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'vibe-expedition-')),app=startTestServer({port:0,host:'127.0.0.1',saveFile:path.join(dir,'world.json')});await new Promise(r=>app.server.once('listening',r));const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}),a=await browser.newPage({viewport:{width:1400,height:900}}),b=await browser.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true}),errors=[];for(const p of[a,b])p.on('pageerror',e=>errors.push(e.message));
try{for(const[i,p]of[a,b].entries()){await p.goto(`http://localhost:${app.server.address().port}`);await browserAccount(p,'Expedition '+i);await p.locator('#enter').click();await p.waitForFunction(()=>window.vibeDiagnostics.connected);}const aid=await a.evaluate(()=>window.vibeDiagnostics.id),bid=await b.evaluate(()=>window.vibeDiagnostics.id),pa=app.game.world.players[aid],pb=app.game.world.players[bid];
await a.locator('#menuButton').click();await a.locator('#guideTab-settings').click();await a.locator('#showTips').uncheck();await a.locator('#closeGuide').click();assert.equal(await a.locator('#mission').isVisible(),false);await a.locator('#terminalAction').click();await a.locator('[data-tab="equipment"]').click();await a.getByRole('button',{name:'Test atmosphere',exact:true}).click();await a.waitForFunction(()=>!!window.vibeDiagnostics.player.airReading);await a.locator('#closeExpedition').click();
Object.assign(pa.inventory,{ferrite:30,copper:8,scrap:12});await a.waitForTimeout(250);await a.locator('#terminalAction').click();await a.locator('[data-tab="vehicles"]').click();await a.getByRole('button',{name:'Construct',exact:true}).nth(1).click();await a.waitForFunction(()=>window.vibeDiagnostics.state.vehicles.some(v=>v.type==='rover'&&v.health>0));const v=app.game.world.vehicles.find(v=>v.type==='rover'&&v.health>0);pa.x=pb.x=v.x;pa.z=pb.z=v.z;await a.waitForTimeout(350);await a.getByRole('button',{name:'Enter vehicle',exact:true}).click();await a.waitForFunction(()=>!!window.vibeDiagnostics.player.vehicle);await a.locator('#closeExpedition').click();await b.locator('#terminalAction').click();await b.locator('[data-tab="vehicles"]').click();await b.getByRole('button',{name:'Enter vehicle',exact:true}).click();await b.waitForFunction(()=>!!window.vibeDiagnostics.player.vehicle);await b.locator('#closeExpedition').click();const before=v.x;await a.keyboard.down('KeyD');await a.waitForTimeout(1200);await a.keyboard.up('KeyD');await b.waitForFunction(x=>window.vibeDiagnostics.player.x>x+2,before);assert.ok(Math.abs(pa.x-pb.x)<.5);await a.screenshot({path:'docs/screenshots/rover-expedition.png'});
await a.locator('#terminalAction').click();await a.locator('[data-tab="map"]').click();await a.locator('#markerName').fill('Our first rover');await a.getByRole('button',{name:'Mark current location'}).click();await a.waitForFunction(()=>window.vibeDiagnostics.player.markers.length===1);await a.screenshot({path:'docs/screenshots/planet-map.png'});await a.locator('[data-tab="server"]').click();assert.equal(await a.locator('#serverSettingsForm input[name="maxPlayers"]').inputValue(),'50');assert.equal(await a.getByRole('button',{name:'Save settings (admin)'}).isEnabled(),false);await a.locator('#closeExpedition').click();
// Test terrain and gravity rendering away from the original plane, including the longitude seam.
pa.vehicle=null;pb.vehicle=null;v.occupants=[];for(const[x,z,name]of[[CIRCUMFERENCE/4,0,'planet-quarter'],[0,CIRCUMFERENCE/4-20,'planet-pole'],[CIRCUMFERENCE/2-1,0,'planet-seam']]){pa.x=x;pa.z=z;await a.waitForTimeout(800);await a.keyboard.down('KeyD');await a.waitForTimeout(500);await a.keyboard.up('KeyD');await a.waitForTimeout(500);console.log(name,await a.evaluate(()=>{const d=window.vibeDiagnostics;return{p:[d.player.x,d.player.z],local:d.localPosition,camera:d.cameraPosition,up:d.cameraUp,tiles:d.terrainChunks,resources:d.state.resources.length};}));assert.ok(Number.isFinite(pa.x)&&Number.isFinite(pa.z));assert.ok(await a.evaluate(()=>window.vibeDiagnostics.drawCalls>10));await a.screenshot({path:`docs/screenshots/${name}.png`});}assert.ok(pa.x<0,'Longitude seam crossed');await a.reload();await a.locator('#findGame').click();await a.locator('#enter').click();await a.waitForFunction(()=>window.vibeDiagnostics.connected);assert.equal(await a.locator('#mission').isVisible(),false);assert.deepEqual(errors,[]);console.log('PASS: persistent tips, atmosphere scan, rover construction/driving/passenger sync, map marker, restricted admin UI, quarter-planet/pole/seam rendering.');
}finally{await browser.close();await app.close();fs.rmSync(dir,{recursive:true});}
