// Reproducible local load harness. Simulated clients are not 50 human devices or production Redis.
import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {performance,monitorEventLoopDelay} from 'node:perf_hooks';import {WebSocket} from 'ws';
import {startTestServer,apiAccount} from './auth-helper.js';import {Game} from '../server/game.js';import {itemCount} from '../shared/world.js';import {transaction} from '../server/cloud-store.js';import {joinRoom,frameRoom} from '../server/cloud-room.js';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'vibe-fifty-active-')),saveFile=path.join(dir,'world.json'),app=startTestServer({port:0,host:'127.0.0.1',saveFile}),clients=[],latencies=[],delay=monitorEventLoopDelay({resolution:10});let bytes=0,snapshots=0,inputCount=0,accepted=0;
const sleep=ms=>new Promise(r=>setTimeout(r,ms)),percentile=(values,p)=>[...values].sort((a,b)=>a-b)[Math.min(values.length-1,Math.floor(values.length*p))]||0;
async function action(c,message){assert.equal(c.pending,null);return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{c.pending=null;reject(Error('Action timeout'));},5000);c.pending={start:performance.now(),resolve:result=>{clearTimeout(timer);resolve(result);}};c.ws.send(JSON.stringify(message));});}
try{await new Promise(r=>app.server.once('listening',r));const base=`http://127.0.0.1:${app.server.address().port}`;
 for(let i=0;i<50;i++){const auth=await apiAccount(base,i),ws=new WebSocket(base.replace('http','ws'),{headers:{Cookie:auth.cookie}}),c={ws,id:auth.character,pending:null,ack:-1};clients.push(c);await new Promise((resolve,reject)=>{ws.on('error',reject);ws.on('open',()=>ws.send(JSON.stringify({type:'join',character:auth.character})));ws.on('message',raw=>{const m=JSON.parse(raw);if(m.type==='welcome')resolve();if(m.type==='error')reject(Error(m.message));if(m.type==='result'&&c.pending){const pending=c.pending;c.pending=null;latencies.push(performance.now()-pending.start);if(m.ok)accepted++;pending.resolve(m);}if(m.type==='state'||m.type==='delta'){bytes+=raw.length;snapshots++;c.ack=Math.max(c.ack,m.inputAck??-1);}});});}
 app.game.world.creatures=[];app.game.world.resources=[];for(let i=0;i<50;i++){const p=app.game.world.players[clients[i].id];p.x=(i%10)*6-27;p.z=Math.floor(i/10)*6+18;Object.assign(p.inventory,{ferrite:10,fiber:5});app.game.world.resources.push({id:'load'+i,type:'ferrite',x:p.x+2.4,z:p.z,amount:100,y:0});}
 bytes=0;snapshots=0;const started=performance.now();delay.enable();await Promise.all(clients.map(c=>action(c,{type:'craft',recipe:'cutter'}))).then(results=>assert.ok(results.every(r=>r.ok),JSON.stringify(results.filter(r=>!r.ok))));
 await Promise.all(clients.map((c,i)=>{const p=app.game.world.players[c.id];return action(c,{type:'build',piece:'floor',x:p.x,z:p.z,rotation:0});})).then(results=>assert.ok(results.every(r=>r.ok),JSON.stringify(results.filter(r=>!r.ok))));
 await sleep(350);for(let frame=0;frame<100;frame++){for(const c of clients){c.ws.send(JSON.stringify({type:'input',sequence:frame,x:frame%20<10?.1:-.1,z:0,yaw:0}));inputCount++;}if(frame%10===0)await Promise.all(clients.map((c,i)=>action(c,{type:'gather',id:'load'+i}))).then(results=>assert.ok(results.every(r=>r.ok),JSON.stringify(results.filter(r=>!r.ok))));await sleep(100);}
 // Fifty simultaneous requests compete for the same finite locker. No duplication or lost units.
 app.game.world.structures.push({id:'shared-load-box',type:'cargo',x:0,z:3,rotation:0,owner:clients[0].id,health:200});app.game.world.containers['shared-load-box']={};for(const c of clients){const p=app.game.world.players[c.id];p.x=0;p.z=3;}const totalBefore=clients.reduce((n,c)=>n+itemCount(app.game.world.players[c.id].inventory),0);
 await Promise.all(clients.map(c=>action(c,{type:'transferBulk',id:'shared-load-box',mode:'deposit'})));assert.equal(itemCount(app.game.world.containers['shared-load-box']),200);assert.equal(clients.reduce((n,c)=>n+itemCount(app.game.world.players[c.id].inventory),0)+200,totalBefore);
 await Promise.all(clients.map(c=>action(c,{type:'transferBulk',id:'shared-load-box',mode:'withdraw'})));assert.equal(itemCount(app.game.world.containers['shared-load-box']),0);assert.equal(clients.reduce((n,c)=>n+itemCount(app.game.world.players[c.id].inventory),0),totalBefore);await sleep(200);assert.ok(clients.every(c=>c.ack>=99));assert.equal(app.game.online.size,50);delay.disable();
 const savedInventories=Object.fromEntries(clients.map(c=>[c.id,structuredClone(app.game.world.players[c.id].inventory)]));app.save();const reloaded=new Game(JSON.parse(fs.readFileSync(saveFile,'utf8')));for(const c of clients)assert.deepEqual(reloaded.join(c.id,'Reload').inventory,savedInventories[c.id]);assert.equal(reloaded.world.structures.filter(s=>s.type==='floor').length,50);
 const local={players:50,seconds:+((performance.now()-started)/1000).toFixed(2),inputs:inputCount,acceptedActions:accepted,snapshots,bytes,actionP95Ms:+percentile(latencies,.95).toFixed(2),actionMaxMs:+Math.max(...latencies).toFixed(2),eventLoopP95Ms:+(delay.percentile(95)/1e6).toFixed(2),eventLoopMaxMs:+(delay.max/1e6).toFixed(2),savedReloadVerified:true,sharedLockerConservation:true};
 // Five cloud workers race through the same compare-and-set transaction path.
 class Store{raw=null;async read(){await sleep(1);return this.raw;}async compareAndSet(old,next){if(this.raw!==old)return false;this.raw=next;return true;}}const store=new Store();for(let i=0;i<50;i++)await transaction(store,r=>joinRoom(r,{id:'p'+i,session:'s'+i,name:'Load '+i}));await transaction(store,r=>{r.world.creatures=[];r.world.structures=[{id:'cloud-box',type:'cargo',x:0,z:3,owner:'p0',health:200}];r.world.containers['cloud-box']={};for(const p of Object.values(r.world.players))p.inventory.ferrite=10;});const batches=Array.from({length:5},(_,worker)=>Array.from({length:10},(_,j)=>worker*10+j));const cloudStart=performance.now();await Promise.all(batches.map(ids=>transaction(store,r=>frameRoom(r,ids.map(i=>({id:'p'+i,session:'s'+i,input:{sequence:1,x:.01,z:0}})),ids.map(i=>({id:'p'+i,session:'s'+i,key:'k'+i,message:{type:'transferBulk',id:'cloud-box',mode:'deposit'}}))))));const persisted=JSON.parse(store.raw),cloudTotal=Object.values(persisted.world.players).reduce((n,p)=>n+itemCount(p.inventory),0)+itemCount(persisted.world.containers['cloud-box']);assert.equal(cloudTotal,500);assert.equal(itemCount(persisted.world.containers['cloud-box']),200);assert.equal(Object.keys(persisted.leases).length,50);
 const report={local,cloud:{players:50,concurrentWorkers:5,seconds:+((performance.now()-cloudStart)/1000).toFixed(3),itemUnitsPreserved:cloudTotal,lockerCapacityEnforced:true},limits:'Loopback WebSockets and an in-memory CAS store. Does not measure production network/Redis latency, fifty rendered clients, or long-session stability.'};console.log(JSON.stringify(report,null,2));if(process.env.REPORT_PATH)fs.writeFileSync(process.env.REPORT_PATH,JSON.stringify(report,null,2)+'\n');
}finally{for(const c of clients)c.ws.terminate();await app.close();fs.rmSync(dir,{recursive:true,force:true});}
