import test from 'node:test';import assert from 'node:assert/strict';
import {Game} from '../server/game.js';import {placementError} from '../shared/world.js';import {snapBuild,gridPoint} from '../shared/build-grid.js';import {tileAt} from '../shared/planet.js';import {acceptSnapshotBaseline} from '../client/snapshot-delta.js';import {contextAction} from '../shared/context-action.js';import {createMotionSampler} from '../client/motion-sampling.js';
test('two lockers fit at opposite edges of one deck; overlap and unsupported equipment reject',()=>{
 const g=new Game(),p=g.join('builder','Builder');p.x=12;p.z=3;g.world.resources=[];g.world.structures=[{id:'deck',type:'floor',x:12,z:0,rotation:0}];
 const a={type:'cargo',x:12,z:-.75,rotation:0},b={...a,z:.75};assert.equal(placementError(g.world,p,a),'');g.world.structures.push({...a,id:'a'});assert.equal(placementError(g.world,p,b),'');assert.match(placementError(g.world,p,{...b,z:0}),/occup|space/);assert.match(placementError(g.world,p,{...b,z:1.25}),/whole object/);assert.match(placementError(g.world,p,{type:'bed',x:15,z:0,rotation:0}),/deck/);assert.match(placementError(g.world,p,{type:'floor',x:12.25,z:0,rotation:0}),/grid/);
 assert.equal(snapBuild(g.world,{x:12.2,z:.7},'cargo').z,.75);assert.equal(snapBuild(g.world,{x:12.2,z:.7},'floor').z,0);
});
test('site furniture fractions survive snapshot validation and remain server validated',()=>{const g=new Game(),p=g.join('b','B'),site=tileAt(300,100),centre=gridPoint(site,0,0,g.world.seed);p.x=centre.x;p.z=centre.z;const piece={id:'c',type:'cargo',site,gx:.25,gz:0,...gridPoint(site,.25,0,g.world.seed),rotation:0};delete piece.y;g.world.structures=[piece];assert.doesNotThrow(()=>acceptSnapshotBaseline(g.snapshot(),0));assert.match(placementError(g.world,p,{...piece,gx:.123}),/grid/);});
test('Action enters directly and exits even while construction is active',()=>{const world={structures:[],resources:[],creatures:[],players:[],vehicles:[{id:'v',x:12,z:0}],settings:{}},p={id:'a',x:12,z:1};assert.deepEqual(contextAction(world,p).message,{type:'vehicle',id:'v'});assert.equal(contextAction(world,{...p,vehicle:'v'},{buildMode:true}).label,'Exit vehicle');});
test('motion interpolates jump height and driving between snapshots without changing authority',()=>{const sampler=createMotionSampler(),first={players:[{id:'p',x:12,z:0,yaw:3.1,jumpHeight:0}],vehicles:[{id:'v',x:12,z:0,yaw:3.1}]},next={players:[{id:'p',x:12,z:0,yaw:-3.1,jumpHeight:1}],vehicles:[{id:'v',x:14,z:0,yaw:-3.1}]};sampler.push(first,1000);sampler.push(next,1250);const middle=sampler.sample(1375);assert.equal(middle.players[0].jumpHeight,.5);assert.ok(middle.vehicles[0].x>12.9&&middle.vehicles[0].x<13.1);assert.ok(middle.vehicles[0].yaw>3);assert.equal(next.vehicles[0].x,14);assert.equal(sampler.sample(1800).players[0].jumpHeight,1);});
import * as THREE from 'three';import {resourceDeposits} from '../client/resource-deposits.js';import {depositKind} from '../shared/resource-deposits.js';import {groundScatter} from '../client/world-atmosphere.js';
test('deposits render stable mineable provenance and remove depleted formations',()=>{const scene=new THREE.Scene(),deposits=resourceDeposits(scene),resources=Array.from({length:12},(_,i)=>({id:'ice'+i,type:'ice',amount:5,x:20+i*4,z:0,y:0}));const original=JSON.stringify(resources);deposits.update({seed:7319,resources});assert.equal(scene.children.reduce((n,m)=>n+m.count,0),12);assert.deepEqual(new Set(resources.map(depositKind)),new Set(['glacier','frozenBasin']));assert.equal(JSON.stringify(resources),original);for(const mesh of scene.children)assert.ok([...mesh.geometry.attributes.position.array].every(Number.isFinite));deposits.update({seed:7319,resources:resources.map(n=>({...n,amount:0}))});assert.equal(scene.children.reduce((n,m)=>n+m.count,0),0);});
test('scatter has irregular coordinates and identical seeded revisits',()=>{const scene=new THREE.Scene(),scatter=groundScatter(scene,7319);scatter.update({x:0,z:0},[],[]);const mesh=scene.children[0],first=mesh.instanceMatrix.array.slice(),positions=[];for(let i=0;i<mesh.count;i++)positions.push([first[i*16+12],first[i*16+14]]);assert.ok(new Set(positions.map(p=>p[0].toFixed(2))).size>positions.length*.9);scatter.update({x:60,z:60},[],[]);scatter.update({x:0,z:0},[],[]);assert.deepEqual(mesh.instanceMatrix.array,first);scatter.dispose();});
test('fine positions build through authority, charge normal costs and survive reload',()=>{const game=new Game(),p=game.join('builder','Builder');p.x=12;p.z=3;game.world.resources=[];game.world.structures=[{id:'deck',type:'floor',x:12,z:0,rotation:0,owner:p.id}];p.inventory.ferrite=20;p.inventory.fiber=10;for(const z of[-.75,.75]){game.cooldowns.clear();assert.equal(game.action(p.id,{type:'build',piece:'cargo',x:12,z,rotation:0}).ok,true);}assert.equal(p.inventory.ferrite,8);const restored=new Game(JSON.parse(JSON.stringify(game.world)));assert.deepEqual(restored.world.structures.filter(s=>s.type==='cargo').map(s=>s.z),[-.75,.75]);assert.equal(depositKind({id:'drop1',type:'ice'}),null);});
