import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {Game} from '../server/game.js';import {makeWorld,generate,RUIN,blocked,placementError} from '../shared/world.js';import {loadWorld,saveWorld} from '../server/persistence.js';
function setup(){const g=new Game();const p=g.join('test-explorer','Ada');return{g,p};}
function gatherAll(g,p,type,count){for(const n of g.world.resources.filter(n=>n.type===type)){p.x=n.x;p.z=n.z;while(n.amount>0&&p.inventory[type]<count){g.tick(1);assert.equal(g.action(p.id,{type:'gather',id:n.id}).ok,true);}if(p.inventory[type]>=count)return;}}
test('seeded terrain resources reproduce and vary with seed',()=>{assert.deepEqual(generate(17),generate(17));assert.notDeepEqual(generate(17),generate(18));});
test('complete gather → cutter → ruin → shelter → anchor loop',()=>{const {g,p}=setup();gatherAll(g,p,'ferrite',12);gatherAll(g,p,'fiber',8);assert.equal(g.action(p.id,{type:'craft',recipe:'cutter'}).ok,true);p.x=RUIN.x;p.z=RUIN.z;assert.equal(g.action(p.id,{type:'scan'}).ok,true);assert.equal(p.unlocked,true);assert.equal(p.inventory.crystal,3);p.x=11;p.z=0;
 for(const piece of ['floor','wall','roof','heater']){g.tick(1);assert.equal(g.action(p.id,{type:'build',piece,x:9,z:0,rotation:0}).ok,true,piece);}
 p.x=10;p.z=0;p.charge=20;g.tick(1);assert.ok(p.charge>20);assert.equal(p.completed,true);assert.equal(g.world.structures.length,4);
});
test('server rejects remote gathering, overspending, overlaps, lock bypass and occupied walls',()=>{const{g,p}=setup();assert.equal(g.action(p.id,{type:'gather',id:'r0'}).ok,false);assert.equal(g.action(p.id,{type:'craft',recipe:'cutter'}).ok,false);p.x=9;p.z=0;p.inventory={ferrite:100,fiber:100,crystal:100};assert.match(placementError(g.world,p,{type:'roof',x:9,z:0,rotation:0}),/deck/);assert.equal(g.action(p.id,{type:'build',piece:'floor',x:9,z:0,rotation:0}).ok,true);g.tick(1);assert.equal(g.action(p.id,{type:'build',piece:'floor',x:9,z:0,rotation:0}).ok,false);assert.equal(g.action(p.id,{type:'build',piece:'heater',x:9,z:0,rotation:0}).ok,false);p.z=-1.5;assert.equal(g.action(p.id,{type:'build',piece:'wall',x:9,z:0,rotation:0}).ok,false);});
test('shared depletion is atomic; no double gathering after last unit',()=>{const{g,p}=setup();const q=g.join('other-explorer','Bo'),n=g.world.resources[0];p.x=q.x=n.x;p.z=q.z=n.z;n.amount=1;assert.equal(g.action(p.id,{type:'gather',id:n.id}).ok,true);assert.equal(g.action(q.id,{type:'gather',id:n.id}).ok,false);assert.equal(p.inventory.ferrite+q.inventory.ferrite,1);});
test('movement normalized, wall collision, world boundary; no movement for offline players',()=>{const{g,p}=setup();g.input(p.id,{x:1,z:1});g.tick(1);assert.ok(Math.hypot(p.x,p.z-3)<4.21);p.x=9;p.z=-2.5;g.world.structures.push({id:'s1',type:'wall',x:9,z:0,rotation:0,owner:p.id});g.input(p.id,{x:0,z:1});for(let i=0;i<30;i++)g.tick(.05);assert.ok(p.z<-1.8);assert.equal(blocked(g.world,59,0),true);g.leave(p.id);const x=p.x;g.tick(1);assert.equal(p.x,x);});
test('ion wind hurts; canopy restores; recovery keeps inventory',()=>{const{g,p}=setup();g.world.time=110;p.charge=10;g.tick(1);assert.ok(p.charge<9);p.x=9;p.z=0;g.world.structures.push({type:'roof',x:9,z:0});const before=p.charge;g.tick(1);assert.ok(p.charge>before);p.x=30;p.charge=0;p.health=1;p.inventory.ferrite=8;g.tick(1);assert.equal(p.health,100);assert.equal(p.x,0);assert.equal(p.inventory.ferrite,8);});
test('dismantle is owner-only, refund once, cannot remove supporting deck',()=>{const{g,p}=setup();p.x=9;p.z=0;p.inventory.ferrite=5;p.inventory.fiber=5;g.action(p.id,{type:'build',piece:'floor',x:9,z:0,rotation:0});g.tick(1);const q=g.join('other-explorer','Bo');q.x=9;q.z=0;assert.equal(g.action(q.id,{type:'dismantle',id:'s1'}).ok,false);assert.equal(g.action(p.id,{type:'dismantle',id:'s1'}).ok,true);g.tick(1);assert.equal(g.action(p.id,{type:'dismantle',id:'s1'}).ok,false);assert.equal(p.inventory.ferrite,5);});
test('atomic save restores seed, depleted nodes, structures, progression and time',()=>{const{g,p}=setup();p.cutter=true;p.unlocked=true;p.inventory.fiber=7;p.x=11;g.world.resources[0].amount=0;g.world.structures.push({id:'s1',type:'floor',x:9,z:0,rotation:0,owner:p.id});g.world.nextStructure=2;g.tick(5);const dir=fs.mkdtempSync(path.join(os.tmpdir(),'vibe-save-'));try{const file=path.join(dir,'world.json');saveWorld(file,g.world);const restored=loadWorld(file,999);assert.deepEqual(restored,g.world);assert.equal(fs.existsSync(file+'.tmp'),false);fs.writeFileSync(file,'broken');assert.throws(()=>loadWorld(file,999));}finally{fs.rmSync(dir,{recursive:true});}});
