import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {DISMANTLE_GRANT_LIMIT,Game} from '../server/game.js';import {makeWorld,generate,RUIN,blocked,placementError} from '../shared/world.js';import {loadWorld,saveWorld} from '../server/persistence.js';
import {createSnapshotSession,nextSnapshotPacket} from '../server/snapshot-delta.js';
function setup(){const g=new Game();const p=g.join('test-explorer','Ada');return{g,p};}
function gatherAll(g,p,type,count){for(const n of g.world.resources.filter(n=>n.type===type)){p.x=n.x;p.z=n.z;while(n.amount>0&&p.inventory[type]<count){g.tick(1);assert.equal(g.action(p.id,{type:'gather',id:n.id}).ok,true);}if(p.inventory[type]>=count)return;}}
test('seeded terrain resources reproduce and vary with seed',()=>{assert.deepEqual(generate(17),generate(17));assert.notDeepEqual(generate(17),generate(18));});
test('complete gather → cutter → ruin → shelter → anchor loop',()=>{const {g,p}=setup();gatherAll(g,p,'ferrite',12);gatherAll(g,p,'fiber',8);assert.equal(g.action(p.id,{type:'craft',recipe:'cutter'}).ok,true);p.x=RUIN.x;p.z=RUIN.z;assert.equal(g.action(p.id,{type:'scan'}).ok,true);assert.equal(p.unlocked,true);assert.equal(p.inventory.crystal,3);p.x=11;p.z=0;
 for(const piece of ['floor','wall','roof','heater']){g.tick(1);assert.equal(g.action(p.id,{type:'build',piece,x:9,z:0,rotation:0}).ok,true,piece);}
 p.x=10;p.z=0;p.charge=20;g.tick(1);assert.ok(p.charge>20);assert.equal(p.completed,true);assert.equal(g.world.structures.length,4);
});
test('server rejects remote gathering, overspending, overlaps, lock bypass and occupied walls',()=>{const{g,p}=setup();assert.equal(g.action(p.id,{type:'gather',id:'r0'}).ok,false);assert.equal(g.action(p.id,{type:'craft',recipe:'cutter'}).ok,false);p.x=9;p.z=0;p.inventory={ferrite:100,fiber:100,crystal:100};assert.match(placementError(g.world,p,{type:'roof',x:9,z:0,rotation:0}),/deck/);assert.equal(g.action(p.id,{type:'build',piece:'floor',x:9,z:0,rotation:0}).ok,true);g.tick(1);assert.equal(g.action(p.id,{type:'build',piece:'floor',x:9,z:0,rotation:0}).ok,false);assert.equal(g.action(p.id,{type:'build',piece:'heater',x:9,z:0,rotation:0}).ok,false);p.z=-1.5;assert.equal(g.action(p.id,{type:'build',piece:'wall',x:9,z:0,rotation:0}).ok,false);});
test('server places a doorway frame on a supported construction-grid edge',()=>{const{g,p}=setup();p.x=9;p.z=4.5;p.inventory.ferrite=10;p.inventory.fiber=10;assert.equal(g.action(p.id,{type:'build',piece:'floor',x:9,z:0,rotation:0}).ok,true);g.tick(1);const result=g.action(p.id,{type:'build',piece:'doorway',x:9,z:0,rotation:0});assert.deepEqual(result,{ok:true,message:'Doorway frame constructed.'});assert.equal(g.world.structures[1].type,'doorway');assert.equal(g.world.structures[1].rotation,0);});
test('doorway rotations occupy distinct deck edges and conflict with walls on the same edge',()=>{const{g,p}=setup();p.x=9;p.z=4.5;p.inventory.ferrite=20;p.inventory.fiber=10;assert.equal(g.action(p.id,{type:'build',piece:'floor',x:9,z:0,rotation:0}).ok,true);g.tick(1);assert.equal(g.action(p.id,{type:'build',piece:'doorway',x:9,z:0,rotation:0}).ok,true);g.tick(1);assert.equal(g.action(p.id,{type:'build',piece:'doorway',x:9,z:0,rotation:1}).ok,true);g.tick(1);assert.equal(g.action(p.id,{type:'build',piece:'wall',x:9,z:0,rotation:0}).ok,false);});
test('server rejects doorway placement when a player overlaps its frame',()=>{const{g,p}=setup();p.x=9;p.z=4.5;p.inventory.ferrite=10;p.inventory.fiber=10;assert.equal(g.action(p.id,{type:'build',piece:'floor',x:9,z:0,rotation:0}).ok,true);g.tick(1);const q=g.join('other-explorer','Bo');q.x=7.8;q.z=-1.5;assert.match(g.action(p.id,{type:'build',piece:'doorway',x:9,z:0,rotation:0}).message,/player is in the way/);});
test('doorway requests inherit server support range affordability shape and cap checks',()=>{const{g,p}=setup();p.x=9;p.z=4.5;const build=overrides=>g.action(p.id,{type:'build',piece:'doorway',x:9,z:0,rotation:0,...overrides});assert.match(build({}).message,/deck/);g.world.structures.push({id:'deck',type:'floor',x:9,z:0,rotation:0,owner:p.id});assert.match(build({x:30}).message,/closer/);assert.match(build({rotation:4}).message,/Invalid placement/);assert.match(build({x:9.5}).message,/3 m construction grid/);assert.match(build({}).message,/resources/);p.inventory.ferrite=10;g.world.structures=Array.from({length:5000},(_,i)=>({id:`s${i}`,type:i===0?'floor':'perimeter',x:i===0?9:30+i*3,z:0,rotation:0,owner:p.id}));assert.match(build({}).message,/structure limit/);});
test('shared depletion is atomic; no double gathering after last unit',()=>{const{g,p}=setup();const q=g.join('other-explorer','Bo'),n=g.world.resources[0];p.x=q.x=n.x;p.z=q.z=n.z;n.amount=1;assert.equal(g.action(p.id,{type:'gather',id:n.id}).ok,true);assert.equal(g.action(q.id,{type:'gather',id:n.id}).ok,false);assert.equal(p.inventory.ferrite+q.inventory.ferrite,1);});
test('movement normalized, wall collision, planet traversal; no movement for offline players',()=>{const{g,p}=setup();g.input(p.id,{sequence:0,x:1,z:1});g.tick(1);assert.ok(Math.hypot(p.x,p.z-3)<4.21);p.x=9;p.z=-2.5;g.world.structures.push({id:'s1',type:'wall',x:9,z:0,rotation:0,owner:p.id});g.input(p.id,{sequence:1,x:0,z:1});for(let i=0;i<30;i++)g.tick(.05);assert.ok(p.z<-1.8);assert.equal(blocked(g.world,59,0),false);g.leave(p.id);const x=p.x;g.tick(1);assert.equal(p.x,x);});
test('doorway opening is traversable while its side posts retain collision',()=>{const{g,p}=setup();g.world.structures.push({id:'s1',type:'doorway',x:9,z:0,rotation:0,owner:p.id});assert.equal(blocked(g.world,9,-1.5),false);assert.equal(blocked(g.world,7.8,-1.5),true);});
test('ion wind hurts; canopy restores; recovery keeps inventory',()=>{const{g,p}=setup();g.world.time=110;p.charge=10;g.tick(1);assert.ok(p.charge<9);p.x=9;p.z=0;g.world.structures.push({type:'roof',x:9,z:0});const before=p.charge;g.tick(1);assert.ok(p.charge>before);p.x=30;p.charge=0;p.health=1;p.inventory.ferrite=8;g.tick(1);assert.equal(p.health,100);assert.equal(p.x,0);assert.equal(p.inventory.ferrite,8);});
test('dismantle is owner-only, refund once, cannot remove supporting deck',()=>{const{g,p}=setup();p.x=9;p.z=0;p.inventory.ferrite=5;p.inventory.fiber=5;g.action(p.id,{type:'build',piece:'floor',x:9,z:0,rotation:0});g.tick(1);const q=g.join('other-explorer','Bo');q.x=9;q.z=0;assert.equal(g.action(q.id,{type:'dismantle',id:'s1'}).ok,false);assert.equal(g.action(p.id,{type:'dismantle',id:'s1'}).ok,true);g.tick(1);assert.equal(g.action(p.id,{type:'dismantle',id:'s1'}).ok,false);assert.equal(p.inventory.ferrite,5);});
test('dismantle grants reject unknown targets without mutating the structure',()=>{const{g,p}=setup();g.world.structures.push({id:'s1',type:'floor',x:p.x,z:p.z,rotation:0,owner:p.id});const before=structuredClone(g.world.structures[0]);const result=g.action(p.id,{type:'dismantleAccess',id:'s1',target:'missing-explorer',allow:true});assert.deepEqual(result,{ok:false,message:'Choose a saved fellow explorer.'});assert.deepEqual(g.world.structures[0],before);});
test('dismantle grants reject a present saved __proto__ identity without mutation',()=>{const{g,p}=setup();Object.defineProperty(g.world.players,'__proto__',{value:{...p,id:'__proto__',name:'Unsafe'},enumerable:true,writable:true,configurable:true});g.world.structures.push({id:'s1',type:'floor',x:p.x,z:p.z,rotation:0,owner:p.id});const before=structuredClone(g.world.structures[0]);assert.equal(g.action(p.id,{type:'dismantleAccess',id:'s1',target:'__proto__',allow:true}).ok,false);assert.deepEqual(g.world.structures[0],before);});
test('dismantle grants reject a present saved prototype identity without mutation',()=>{const{g,p}=setup();g.world.players.prototype={...p,id:'prototype',name:'Unsafe'};g.world.structures.push({id:'s1',type:'floor',x:p.x,z:p.z,rotation:0,owner:p.id});const before=structuredClone(g.world.structures[0]);assert.equal(g.action(p.id,{type:'dismantleAccess',id:'s1',target:'prototype',allow:true}).ok,false);assert.deepEqual(g.world.structures[0],before);});
test('dismantle grants reject a present saved constructor identity without mutation',()=>{const{g,p}=setup();g.world.players.constructor={...p,id:'constructor',name:'Unsafe'};g.world.structures.push({id:'s1',type:'floor',x:p.x,z:p.z,rotation:0,owner:p.id});const before=structuredClone(g.world.structures[0]);assert.equal(g.action(p.id,{type:'dismantleAccess',id:'s1',target:'constructor',allow:true}).ok,false);assert.deepEqual(g.world.structures[0],before);});
test('a structure owner can explicitly grant dismantling access to a saved explorer',()=>{const{g,p}=setup();const q=g.join('other-explorer','Bo');g.world.structures.push({id:'s1',type:'floor',x:p.x,z:p.z,rotation:0,owner:p.id});assert.deepEqual(g.action(p.id,{type:'dismantleAccess',id:'s1',target:q.id,allow:true}),{ok:true,message:'Bo may dismantle this piece.'});assert.deepEqual(g.world.structures[0].dismantleGrants,[q.id]);});
test('per-structure dismantling grants stop at a fixed finite cap without mutation',()=>{const{g,p}=setup(),targets=Array.from({length:DISMANTLE_GRANT_LIMIT+1},(_,i)=>g.join(`saved-${i}`,`Saved ${i}`).id);g.world.structures.push({id:'s1',type:'floor',x:p.x,z:p.z,rotation:0,owner:p.id,dismantleGrants:targets.slice(0,DISMANTLE_GRANT_LIMIT-1)});assert.equal(g.action(p.id,{type:'dismantleAccess',id:'s1',target:targets[DISMANTLE_GRANT_LIMIT-1],allow:true}).ok,true);const atCap=structuredClone(g.world.structures[0]);assert.equal(g.action(p.id,{type:'dismantleAccess',id:'s1',target:targets[DISMANTLE_GRANT_LIMIT],allow:true}).ok,false);assert.deepEqual(g.world.structures[0],atCap);});
test('an explicitly authorized collaborator can dismantle once and receive one refund',()=>{const{g,p}=setup();const q=g.join('other-explorer','Bo');q.x=p.x;q.z=p.z;g.world.structures.push({id:'s1',type:'floor',x:p.x,z:p.z,rotation:0,owner:p.id,dismantleGrants:[q.id]});assert.equal(g.action(q.id,{type:'dismantle',id:'s1'}).ok,true);assert.deepEqual({ferrite:q.inventory.ferrite,fiber:q.inventory.fiber},{ferrite:2,fiber:1});g.tick(1);assert.equal(g.action(q.id,{type:'dismantle',id:'s1'}).ok,false);assert.deepEqual({ferrite:q.inventory.ferrite,fiber:q.inventory.fiber},{ferrite:2,fiber:1});});
test('an authorized collaborator can dismantle a doorway once under existing safeguards',()=>{const{g,p}=setup();const q=g.join('other-explorer','Bo');q.x=p.x;q.z=p.z;g.world.structures.push({id:'deck',type:'floor',x:p.x,z:p.z,rotation:0,owner:p.id},{id:'frame',type:'doorway',x:p.x,z:p.z,rotation:0,owner:p.id,dismantleGrants:[q.id]});assert.equal(g.action(q.id,{type:'dismantle',id:'frame'}).ok,true);assert.equal(q.inventory.ferrite,2);g.tick(1);assert.equal(g.action(q.id,{type:'dismantle',id:'frame'}).ok,false);assert.equal(q.inventory.ferrite,2);});
test('owner revocation takes effect on the collaborators next dismantle action',()=>{const{g,p}=setup();const q=g.join('other-explorer','Bo');q.x=p.x;q.z=p.z;g.world.structures.push({id:'s1',type:'floor',x:p.x,z:p.z,rotation:0,owner:p.id,dismantleGrants:[q.id]});assert.deepEqual(g.action(p.id,{type:'dismantleAccess',id:'s1',target:q.id,allow:false}),{ok:true,message:'Bo no longer has dismantling access.'});assert.equal(Object.hasOwn(g.world.structures[0],'dismantleGrants'),false);assert.equal(g.action(q.id,{type:'dismantle',id:'s1'}).ok,false);assert.equal(g.world.structures.length,1);});
test('malformed self duplicate prototype and non-owner grant requests fail closed',()=>{const{g,p}=setup();const q=g.join('other-explorer','Bo');g.world.structures.push({id:'s1',type:'floor',x:p.x,z:p.z,rotation:0,owner:p.id,dismantleGrants:[q.id]});const attempts=[[p.id,{type:'dismantleAccess',id:'s1',target:q.id,allow:true}],[p.id,{type:'dismantleAccess',id:'s1',target:p.id,allow:true}],[p.id,{type:'dismantleAccess',id:'s1',target:'__proto__',allow:true}],[p.id,{type:'dismantleAccess',id:'s1',target:'constructor',allow:true}],[p.id,{type:'dismantleAccess',id:'s1',target:'x'.repeat(129),allow:true}],[p.id,{type:'dismantleAccess',id:'s1',target:null,allow:true}],[p.id,{type:'dismantleAccess',id:'s1',target:q.id,allow:'yes'}],[q.id,{type:'dismantleAccess',id:'s1',target:p.id,allow:true}],[p.id,{type:'dismantleAccess',id:'missing',target:q.id,allow:true}]];for(const[actor,message]of attempts){const before=structuredClone(g.world.structures);assert.equal(g.action(actor,message).ok,false);assert.deepEqual(g.world.structures,before);}});
test('structure snapshots expose only viewer-specific dismantling authorization',()=>{const{g,p}=setup();const q=g.join('other-explorer','Bo'),r=g.join('third-explorer','Cy');g.world.structures.push({id:'s1',type:'floor',x:p.x,z:p.z,rotation:0,owner:p.id,dismantleGrants:[q.id]});const owner=g.snapshot(p.id).structures[0],collaborator=g.snapshot(q.id).structures[0],stranger=g.snapshot(r.id).structures[0],publicStructure=g.snapshot().structures[0];assert.deepEqual(owner.dismantleGrantedTo,[q.id]);assert.equal(owner.canDismantle,true);assert.equal(collaborator.canDismantle,true);for(const projected of[collaborator,stranger,publicStructure])assert.equal(Object.hasOwn(projected,'dismantleGrantedTo'),false);for(const projected of[stranger,publicStructure])assert.equal(Object.hasOwn(projected,'canDismantle'),false);for(const projected of[owner,collaborator,stranger,publicStructure])assert.equal(Object.hasOwn(projected,'dismantleGrants'),false);assert.deepEqual(g.world.structures[0].dismantleGrants,[q.id]);});
test('malformed saved dismantling grants never authorize a collaborator',()=>{const{g,p}=setup();const q=g.join('other-explorer','Bo');q.x=p.x;q.z=p.z;g.world.structures.push({id:'s1',type:'floor',x:p.x,z:p.z,rotation:0,owner:p.id,dismantleGrants:[q.id,q.id]});assert.equal(g.action(q.id,{type:'dismantle',id:'s1'}).ok,false);assert.equal(Object.hasOwn(g.snapshot(q.id).structures[0],'canDismantle'),false);assert.equal(g.world.structures.length,1);});
test('saved prototype-key dismantling grants reveal no rejected values and authorize nobody',()=>{for(const forbidden of['__proto__','prototype','constructor']){const{g,p}=setup();Object.defineProperty(g.world.players,forbidden,{value:{...p,id:forbidden,name:'Unsafe'},enumerable:true,writable:true,configurable:true});g.world.structures.push({id:'s1',type:'floor',x:p.x,z:p.z,rotation:0,owner:p.id,dismantleGrants:[forbidden]});const before=structuredClone(g.world.structures[0]),ownerView=g.snapshot(p.id).structures[0],targetView=g.snapshot(forbidden).structures[0];assert.deepEqual(ownerView.dismantleGrantedTo,[]);assert.equal(Object.hasOwn(targetView,'canDismantle'),false);assert.equal(g.action(forbidden,{type:'dismantle',id:'s1'}).ok,false);assert.deepEqual(g.world.structures[0],before);}});
test('over-cap saved dismantling grants authorize nobody and project no values',()=>{const{g,p}=setup(),targets=Array.from({length:DISMANTLE_GRANT_LIMIT+1},(_,i)=>g.join(`saved-${i}`,`Saved ${i}`));for(const target of targets){target.x=p.x;target.z=p.z;}g.world.structures.push({id:'s1',type:'floor',x:p.x,z:p.z,rotation:0,owner:p.id,dismantleGrants:targets.map(target=>target.id)});const before=structuredClone(g.world.structures[0]),ownerView=g.snapshot(p.id).structures[0],targetView=g.snapshot(targets[0].id).structures[0];assert.deepEqual(ownerView.dismantleGrantedTo,[]);assert.equal(Object.hasOwn(targetView,'canDismantle'),false);assert.equal(g.action(targets[0].id,{type:'dismantle',id:'s1'}).ok,false);assert.deepEqual(g.world.structures[0],before);});
test('authorized collaborators remain subject to distance dependency locker capacity and cooldown protections',()=>{const{g,p}=setup();const q=g.join('other-explorer','Bo'),piece=(id,type='perimeter',x=0)=>({id,type,x,z:3,rotation:0,owner:p.id,dismantleGrants:[q.id]});q.x=0;q.z=3;g.world.structures.push(piece('far','perimeter',20));assert.equal(g.action(q.id,{type:'dismantle',id:'far'}).ok,false);g.world.structures.push(piece('deck','floor'),{id:'roof',type:'roof',x:0,z:3,rotation:0,owner:p.id});assert.equal(g.action(q.id,{type:'dismantle',id:'deck'}).ok,false);g.world.structures=g.world.structures.filter(s=>!['deck','roof'].includes(s.id));q.inventory.ferrite=60;g.world.structures.push(piece('full'));assert.equal(g.action(q.id,{type:'dismantle',id:'full'}).ok,false);q.inventory.ferrite=0;g.world.structures.push(piece('locker','cargo'));g.world.containers.locker={};p.x=0;p.z=3;assert.equal(g.action(p.id,{type:'lock',mode:'set',id:'locker',pin:'2468'}).ok,true);assert.equal(g.action(q.id,{type:'dismantle',id:'locker'}).ok,false);g.world.structures.push(piece('first'),piece('second'));assert.equal(g.action(q.id,{type:'dismantle',id:'first'}).ok,true);assert.match(g.action(q.id,{type:'dismantle',id:'second'}).message,/Tool cycling/);});
test('atomic save restores seed, depleted nodes, structures, progression and time',()=>{const{g,p}=setup();p.cutter=true;p.unlocked=true;p.inventory.fiber=7;p.x=11;g.world.resources[0].amount=0;g.world.structures.push({id:'s1',type:'floor',x:9,z:0,rotation:0,owner:p.id});g.world.nextStructure=2;g.tick(5);const dir=fs.mkdtempSync(path.join(os.tmpdir(),'vibe-save-'));try{const file=path.join(dir,'world.json');saveWorld(file,g.world);const restored=loadWorld(file,999);assert.deepEqual(restored,g.world);assert.equal(fs.existsSync(file+'.tmp'),false);fs.writeFileSync(file,'broken');assert.throws(()=>loadWorld(file,999));}finally{fs.rmSync(dir,{recursive:true});}});
test('doorway persists unchanged and survives exact multiplayer snapshot delivery',()=>{const{g,p}=setup();g.world.structures.push({id:'s1',type:'doorway',x:9,z:0,rotation:2,health:200,owner:p.id});g.world.nextStructure=2;const dir=fs.mkdtempSync(path.join(os.tmpdir(),'vibe-doorway-'));try{const file=path.join(dir,'world.json');saveWorld(file,g.world);const restoredGame=new Game(loadWorld(file,999)),session=createSnapshotSession(restoredGame.snapshot(p.id));restoredGame.world.time+=.1;const packet=nextSnapshotPacket(session,restoredGame.snapshot(p.id));assert.deepEqual(restoredGame.world.structures,g.world.structures);assert.deepEqual(session.state.structures,restoredGame.snapshot(p.id).structures);assert.ok(packet.type==='state'||packet.type==='delta');}finally{fs.rmSync(dir,{recursive:true});}});
test('atomic saves preserve per-structure grants while legacy structures remain owner-only',()=>{const{g,p}=setup();const q=g.join('other-explorer','Bo');g.world.structures.push({id:'s1',type:'floor',x:p.x,z:p.z,rotation:0,owner:p.id,dismantleGrants:[q.id]},{id:'s2',type:'perimeter',x:p.x+3,z:p.z,rotation:0,owner:p.id});const dir=fs.mkdtempSync(path.join(os.tmpdir(),'vibe-grants-'));try{const file=path.join(dir,'world.json');saveWorld(file,g.world);const restoredGame=new Game(loadWorld(file,999));restoredGame.join(q.id,q.name);restoredGame.world.players[q.id].x=p.x;restoredGame.world.players[q.id].z=p.z;assert.deepEqual(restoredGame.world.structures[0].dismantleGrants,[q.id]);assert.equal(restoredGame.action(q.id,{type:'dismantle',id:'s1'}).ok,true);restoredGame.tick(1);assert.equal(restoredGame.action(q.id,{type:'dismantle',id:'s2'}).ok,false);}finally{fs.rmSync(dir,{recursive:true});}});

test('input sequences fail closed without mutating movement or acknowledgement',()=>{const{g,p}=setup();assert.equal(g.inputAck(p.id),null);assert.equal(g.input(p.id,{sequence:4,x:1,z:0}),true);assert.equal(g.inputAck(p.id),4);assert.deepEqual(g.inputs.get(p.id).x,1);for(const sequence of [4,3,-1,1.5,Number.MAX_SAFE_INTEGER+1,Infinity,undefined]){assert.equal(g.input(p.id,{sequence,x:-1,z:0}),false);assert.equal(g.inputAck(p.id),4);assert.equal(g.inputs.get(p.id).x,1);}});
