import test from 'node:test';import assert from 'node:assert/strict';import {Game} from '../server/game.js';import {travel,planetDistance,CIRCUMFERENCE,RADIUS,nearbyResources,tileAt,atmosphere,classifyBiome} from '../shared/planet.js';import {rooms,roomStatus,airlockCheck} from '../shared/rooms.js';import {validateSettings} from '../shared/settings.js';
function fixture(){const g=new Game(),p=g.join('p','Pilot');return{g,p};}
function habitat(w){const add=(type,x,z,rotation=0)=>{const s={id:'s'+(w.structures.length+1),type,x,z,rotation,owner:'p',power:100};w.structures.push(s);return s;};for(const x of[9,12,15]){add('floor',x,0);add('roof',x,0);add('wall',x,0,0);add('wall',x,0,2);}const outer=add('door',9,0,3),inner=add('airlock',9,0,1);add('wall',15,0,1);add('lifeSupport',12,0);add('bed',15,0);return{outer,inner};}
test('spherical travel returns to origin, crosses poles/seams, and resource generation is deterministic',()=>{const start={x:0,z:0};assert.ok(planetDistance(start,travel(start,CIRCUMFERENCE,0))<.001);const pole=travel(start,0,CIRCUMFERENCE/4+10);assert.ok(Number.isFinite(pole.x)&&Number.isFinite(pole.z));assert.ok(planetDistance(start,pole)>CIRCUMFERENCE/4-20);const p={x:CIRCUMFERENCE/2-1,z:0},next=travel(p,3,0);assert.ok(next.x<0);assert.ok(Math.abs(planetDistance(p,next)-3)<.001);assert.deepEqual(nearbyResources(7319,p),nearbyResources(7319,p));assert.notDeepEqual(atmosphere(1),atmosphere(2));});
test('seeded biome classification is deterministic and returns only the closed descriptor schema',()=>{const first=classifyBiome(1000,-500,7319),again=classifyBiome(1000,-500,7319);assert.deepEqual(first,again);assert.deepEqual(Object.keys(first),['id','name','palette']);assert.deepEqual(Object.keys(first.palette),['high','low','mid']);assert.ok(['quiet-basin','coral-shelf'].includes(first.id));assert.ok(['Quiet Basin','Coral Shelf'].includes(first.name));for(const color of Object.values(first.palette))assert.ok(Number.isInteger(color)&&color>=0&&color<=0xffffff);});
test('starter basin and established nearby routes retain the baseline biome for every seed',()=>{for(const seed of[7319,28])for(const distance of[0,65,116,250,320])for(const[east,south]of[[distance,0],[-distance,0],[0,distance],[0,-distance]]){const p=travel({x:0,z:0},east,south);assert.equal(classifyBiome(p.x,p.z,seed).id,'quiet-basin');}});
test('spherical travel at the protected 325 metre boundary stays in the starter biome',()=>{for(const seed of[0,1,28,7319,90210,2147483647,4294967295])for(let degrees=0;degrees<360;degrees++){const bearing=degrees*Math.PI/180,p=travel({x:0,z:0},325*Math.cos(bearing),325*Math.sin(bearing));assert.equal(classifyBiome(p.x,p.z,seed).id,'quiet-basin',`seed ${seed}, bearing ${degrees} degrees, distance ${planetDistance(p,{x:0,z:0})}`);}});
test('biome classification agrees at equivalent longitude-seam and pole coordinates',()=>{assert.deepEqual(classifyBiome(CIRCUMFERENCE/2,1234,7319),classifyBiome(-CIRCUMFERENCE/2,1234,7319));assert.deepEqual(classifyBiome(0,CIRCUMFERENCE/4,7319),classifyBiome(CIRCUMFERENCE/3,CIRCUMFERENCE/4,7319));assert.deepEqual(classifyBiome(0,-CIRCUMFERENCE/4,7319),classifyBiome(-CIRCUMFERENCE/3,-CIRCUMFERENCE/4,7319));});
test('biome classification fails closed to the baseline for non-finite inputs',()=>{const baseline=classifyBiome(0,0,7319);for(const args of[[NaN,0,7319],[0,Infinity,7319],[-70000,-30000,NaN],[0,0,'7319'],[0,0,null]])assert.deepEqual(classifyBiome(...args),baseline);});
test('streamed deposits preserve depletion through save and reject repeat rewards',()=>{const{g,p}=fixture();p.x=1000;p.z=1000;const n=nearbyResources(g.world.seed,p)[0];p.x=n.x;p.z=n.z;assert.ok(g.action(p.id,{type:'gather',id:n.id}).ok);const restored=new Game(JSON.parse(JSON.stringify(g.world)));restored.join('p','Pilot');assert.equal(restored.snapshot('p').resources.find(r=>r.id===n.id).amount,n.amount-1);assert.equal(restored.world.players.p.skills.mining,1);});
test('airlock rejects exterior placement, cycles only sealed rooms, and a breach removes habitability',()=>{const{g,p}=fixture(),{inner,outer}=habitat(g.world);p.x=9;p.z=0;assert.equal(rooms(g.world).filter(r=>r.sealed).length,2);assert.ok(!airlockCheck(g.world,inner).error);for(let i=0;i<120;i++)g.tick(.1);assert.equal(roomStatus(g.world,{x:12,z:0}).safe,true);assert.equal(g.action('p',{type:'door',id:inner.id}).ok,false);assert.ok(g.action('p',{type:'cycle',id:inner.id}).ok);for(let i=0;i<51;i++)g.tick(.1);assert.equal(roomStatus(g.world,p).safe,true);assert.ok(g.action('p',{type:'door',id:inner.id}).ok);outer.open=true;g.tick(.1);assert.equal(roomStatus(g.world,p).safe,false);inner.open=false;g.world.structures=g.world.structures.filter(s=>!(s.type==='roof'&&s.x===9));assert.ok(airlockCheck(g.world,inner).error);});
test('sealed outer door operation fails closed for unauthenticated remote malformed stale and non-door targets',()=>{const{g,p}=fixture(),{outer}=habitat(g.world);p.x=30;p.z=0;const attempts=[['missing',{type:'door',id:outer.id}],[p.id,{type:'door',id:outer.id}],[p.id,{type:'door',id:{value:outer.id}}],[p.id,{type:'door',id:'stale-door'}],[p.id,{type:'door',id:g.world.structures.find(s=>s.type==='wall').id}]];for(const[actor,message]of attempts){const before=structuredClone(g.world);assert.equal(g.action(actor,message).ok,false);assert.deepEqual(g.world,before);}});
test('door operation selects the nearest physical edge when one deck has two doors',()=>{const{g,p}=fixture();p.x=3;p.z=-3;g.world.structures.push({id:'north',type:'door',x:3,z:0,rotation:0,open:false},{id:'east',type:'door',x:3,z:0,rotation:1,open:false});assert.equal(g.action(p.id,{type:'door',id:'east'}).ok,false);assert.equal(g.action(p.id,{type:'door',id:'north'}).ok,true);assert.equal(g.world.structures.find(s=>s.id==='north').open,true);assert.equal(g.world.structures.find(s=>s.id==='east').open,false);});
test('door operation rejects a physical edge behind an intervening wall',()=>{const{g,p}=fixture();p.x=.6;p.z=0;g.world.structures.push({id:'wall',type:'wall',x:0,z:0,rotation:1},{id:'door',type:'door',x:3,z:0,rotation:1,open:false});assert.equal(g.action(p.id,{type:'door',id:'door'}).ok,false);assert.equal(g.world.structures.find(s=>s.id==='door').open,false);});
test('sleep requires suit removal and habitable bed, all active players required',()=>{const{g,p}=fixture();habitat(g.world);p.x=15;p.z=.8;const q=g.join('q','Other');q.x=14;q.z=.8;for(let i=0;i<110;i++)g.tick(.1);assert.equal(g.action('p',{type:'sleep'}).ok,false);assert.ok(g.action('p',{type:'suit'}).ok);const cycle=g.world.settings.daySeconds+g.world.settings.nightSeconds;g.world.time=g.world.settings.daySeconds+10;assert.ok(g.action('p',{type:'sleep'}).ok);g.tick(.1);assert.ok(g.world.time<cycle);q.suit=false;assert.ok(g.action('q',{type:'sleep'}).ok);g.tick(.1);assert.ok(g.world.time>=cycle);});
test('PIN lockers enforce access server-side, redact contents, revoke prior access, and rate limit guesses',()=>{const{g,p}=fixture(),q=g.join('q','Other');g.world.structures.push({id:'box',type:'cargo',x:0,z:3,owner:'p'});g.world.containers.box={ferrite:5};assert.ok(g.action('p',{type:'lock',id:'box',mode:'set',pin:'1234'}).ok);assert.equal(g.action('q',{type:'transfer',id:'box',item:'ferrite',amount:1,direction:'withdraw'}).ok,false);assert.equal(g.snapshot('q').containers.box,undefined);assert.ok(!JSON.stringify(g.snapshot('q')).includes('digest'));assert.ok(g.action('q',{type:'lock',id:'box',mode:'unlock',pin:'1234'}).ok);assert.ok(g.action('q',{type:'transfer',id:'box',item:'ferrite',amount:1,direction:'withdraw'}).ok);g.action('p',{type:'lock',id:'box',mode:'set',pin:'5678'});for(let i=0;i<5;i++)assert.equal(g.action('q',{type:'lock',id:'box',mode:'unlock',pin:'1111'}).ok,false);assert.equal(g.action('q',{type:'lock',id:'box',mode:'unlock',pin:'5678'}).ok,false);});
test('rover construction, driver/passenger synchronization, cargo and expansion limits',()=>{const{g,p}=fixture(),q=g.join('q','Other');Object.assign(p.inventory,{ferrite:40,copper:10,scrap:10});assert.ok(g.action('p',{type:'vehicleBuild',vehicle:'crawler'}).ok);const v=g.world.vehicles[0];p.x=q.x=v.x;p.z=q.z=v.z;assert.ok(g.action('p',{type:'vehicle',id:v.id}).ok);assert.ok(g.action('q',{type:'vehicle',id:v.id}).ok);g.input('p',{sequence:0,x:1,z:0});for(let i=0;i<20;i++)g.tick(.05);assert.ok(v.x>8);assert.equal(p.x,q.x);assert.ok(v.battery<100);p.inventory.ferrite=5;assert.ok(g.action('p',{type:'vehicleCargo',id:v.id,direction:'deposit',item:'ferrite',amount:5}).ok);assert.equal(v.inventory.ferrite,5);});
test('PvP respects settings and cooldown; unsupported settings and spoofed admin actions rejected',()=>{const{g,p}=fixture(),q=g.join('q','Other');q.z=4;p.cutter=true;assert.ok(g.action('p',{type:'attack',id:'q'}).ok);assert.equal(q.health,85);assert.equal(g.action('p',{type:'attack',id:'q'}).ok,false);g.world.time+=1;g.world.settings.pvp=false;assert.equal(g.action('p',{type:'attack',id:'q'}).ok,false);assert.throws(()=>validateSettings({maxPlayers:51}));assert.throws(()=>validateSettings({owner:'p'}));assert.equal(g.action('p',{type:'admin',role:'owner'}).ok,false);});

test('local construction grids stay three metres apart and seal rooms near poles and seams',async()=>{const{snapBuild,gridPoint}=await import('../shared/build-grid.js');for(const pos of[{x:0,z:CIRCUMFERENCE/4-10},{x:CIRCUMFERENCE/2-2,z:0}]){const{g,p}=fixture();const tile=snapBuild(g.world,pos);assert.ok(tile.site);const next=gridPoint(tile.site,tile.gx+1,tile.gz,g.world.seed);assert.ok(Math.abs(planetDistance(tile,next)-3)<.03);const base={...tile,owner:'p'};g.world.structures.push({...base,id:'f',type:'floor'},{...base,id:'r',type:'roof'});for(let rotation=0;rotation<4;rotation++)g.world.structures.push({...base,id:'w'+rotation,type:'wall',rotation});assert.equal(rooms(g.world)[0].sealed,true);p.x=tile.x;p.z=tile.z;assert.equal(roomStatus(g.world,p).sealed,true);const shape=(await import('../shared/world.js')).shape(g.world.structures[2],g.world.seed);assert.ok(Math.abs(planetDistance(shape,tile)-1.5)<.03);}});
