import {chromium} from 'playwright';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {startServer} from '../server/index.js';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'vibe-touch-'));const app=startServer({port:0,host:'127.0.0.1',saveFile:path.join(dir,'world.json')});await new Promise(r=>app.server.once('listening',r));const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});const errors=[];
try{const c=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:2});const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(`http://localhost:${app.server.address().port}`);await p.locator('#enter').tap();await p.waitForFunction(()=>window.vibeDiagnostics.connected);const cd=await c.newCDPSession(p);const box=await p.locator('#stick').boundingBox(),cx=box.x+box.width/2,cy=box.y+box.height/2;
const touch=(type,pts)=>cd.send('Input.dispatchTouchEvent',{type,touchPoints:pts.map(([id,x,y])=>({id,x,y,radiusX:2,radiusY:2}))});
// Real touchscreen events steer the player toward the first ferrite deposit.
await touch('touchStart',[[1,cx+18,cy-36]]);await p.waitForTimeout(1250);await touch('touchEnd',[]);await p.waitForTimeout(250);const pos=await p.evaluate(()=>window.vibeDiagnostics.player);assert.ok(pos.x>1&&pos.z<0);assert.ok(Math.hypot(pos.x-3,pos.z+3)<3);
const gather=await p.locator('#gatherAction').boundingBox();await touch('touchStart',[[2,gather.x+20,gather.y+20]]);await p.waitForTimeout(3300);await touch('touchEnd',[]);await p.waitForFunction(()=>window.vibeDiagnostics.player.inventory.ferrite===4);
// UI works with taps; no keyboard is used anywhere in this test.
await p.locator('#menuButton').tap();await p.locator('#recipes').waitFor({state:'visible'});await p.locator('#closeGuide').tap();await p.locator('#buildAction').tap();await p.waitForFunction(()=>window.vibeDiagnostics.buildMode);await p.locator('#rotateAction').tap();await p.locator('#placeAction').tap();await p.waitForTimeout(200);assert.match(await p.locator('#toast').innerText(),/resources|clear|tile|slot|close|deck|placement/);
await p.locator('#buildAction').tap();
// Multi-touch: joystick and camera gesture coexist, cancellation stops movement.
await touch('touchStart',[[1,cx,cy-32]]);await touch('touchStart',[[1,cx,cy-32],[2,270,350]]);await touch('touchMove',[[1,cx,cy-32],[2,310,355]]);await p.waitForTimeout(300);await touch('touchCancel',[]);await p.waitForTimeout(350);const before=await p.evaluate(()=>window.vibeDiagnostics.player);await p.waitForTimeout(350);const after=await p.evaluate(()=>window.vibeDiagnostics.player);assert.ok(Math.hypot(after.x-before.x,after.z-before.z)<.1);
for(const sel of ['#stick','#gatherAction','#buildAction','#menuButton']){const b=await p.locator(sel).boundingBox();assert.ok(b.x>=0&&b.y>=0&&b.x+b.width<=391&&b.y+b.height<=845,sel);}
await p.screenshot({path:'docs/screenshots/phone-portrait.png'});await p.setViewportSize({width:844,height:390});await p.waitForTimeout(250);await p.screenshot({path:'docs/screenshots/phone-landscape.png'});
// Mouse-only movement pad.
const desktop=await browser.newPage({viewport:{width:1280,height:800}});await desktop.goto(`http://localhost:${app.server.address().port}`);await desktop.locator('#enter').click();await desktop.waitForFunction(()=>window.vibeDiagnostics.connected);assert.equal(await desktop.locator('#stick').isVisible(),false);await desktop.locator('#world').click({position:{x:900,y:550}});await desktop.waitForTimeout(700);const moved=await desktop.evaluate(()=>window.vibeDiagnostics.player);assert.ok(Math.hypot(moved.x,moved.z-3)>.3);assert.deepEqual(errors,[]);
fs.writeFileSync('docs/pointer-test-report.json',JSON.stringify({at:new Date().toISOString(),passed:true,checks:['touch movement','hold to gather','tap fabrication menu','construction buttons and invalid placement','simultaneous move/look','touch cancellation stops movement','portrait controls in viewport','mouse-only movement'],physicalPhoneTested:false},null,2));console.log('Touch, multi-touch, phone layout and mouse-only checks passed');
}finally{await browser.close();await app.close();fs.rmSync(dir,{recursive:true});}
