import test from 'node:test';
import assert from 'node:assert/strict';
import {Game} from '../server/game.js';
import {respawnPoint} from '../server/survival-actions.js';
import {itemCount,RESOURCES,dist} from '../shared/world.js';
import {WORLD_CUES,createAudioEngine,createAudioSettings} from '../client/audio.js';
function fixture(){const game=new Game(),p=game.join('a','A'),q=game.join('b','B');game.world.creatures=[];game.world.structures=[{id:'box',type:'cargo',x:0,z:3,owner:'a',health:200},{id:'bed',type:'bed',x:24,z:12,owner:'a',health:200}];game.world.containers.box={};return{game,p,q,act:m=>game.action('a',m)};}
const totals=game=>Object.fromEntries(Object.keys(RESOURCES).map(k=>[k,Object.values(game.world.players).reduce((n,p)=>n+(p.inventory[k]||0),0)+Object.values(game.world.containers).reduce((n,c)=>n+(c[k]||0),0)]));
test('bulk locker transfers conserve every resource, match existing stacks and stop at capacity',()=>{const{game,p,act}=fixture();p.inventory.ferrite=20;p.inventory.fiber=15;game.world.containers.box={ferrite:180};const before=totals(game);assert.equal(act({type:'transferBulk',id:'box',mode:'matching'}).ok,true);assert.equal(game.world.containers.box.ferrite,200);assert.equal(p.inventory.fiber,15);assert.equal(act({type:'transferBulk',id:'box',mode:'deposit'}).ok,false);assert.equal(act({type:'transferBulk',id:'box',mode:'withdraw'}).ok,true);assert.equal(itemCount(p.inventory),60);assert.deepEqual(totals(game),before);assert.equal(p.journey&32,32);});
test('bulk actions cannot bypass locked cargo, revocation, distance or malformed requests',()=>{const{game,p,q,act}=fixture();p.inventory.ferrite=3;q.inventory.fiber=3;assert.equal(act({type:'lock',mode:'set',id:'box',pin:'1234'}).ok,true);const request={type:'transferBulk',id:'box',mode:'deposit'};assert.equal(game.action('b',request).ok,false);assert.equal(act({type:'cargoAccess',id:'box',target:'b',allow:true}).ok,true);assert.equal(game.action('b',request).ok,true);assert.equal(act({type:'cargoAccess',id:'box',target:'b',allow:false}).ok,true);assert.equal(game.action('b',{...request,mode:'withdraw'}).ok,false);p.x=20;assert.equal(act(request).ok,false);p.x=0;for(const change of [{mode:'steal'},{extra:1},{id:4},{mode:null}]){const before=JSON.stringify(game.world);assert.equal(act({...request,...change}).ok,false);assert.equal(JSON.stringify(game.world),before);}let invoked=false;const bad={};Object.defineProperty(bad,'ferrite',{get(){invoked=true;return 1;},enumerable:true});game.world.containers.box=bad;assert.equal(act(request).ok,false);assert.equal(invoked,false);});
test('dropped stacks debit once, survive save reload, and can be gathered by another explorer',()=>{let{game,p,act}=fixture();p.x=12;p.z=12;p.inventory.ferrite=3;const resourceCount=game.world.resources.length;for(const amount of[0,-1,1.5,61,NaN,Infinity])assert.equal(act({type:'drop',item:'ferrite',amount}).ok,false);assert.equal(act({type:'drop',item:'ferrite',amount:3}).ok,true);assert.equal(act({type:'drop',item:'ferrite',amount:3}).ok,false);assert.equal(p.inventory.ferrite,0);assert.equal(game.world.resources.length,resourceCount+1);game=new Game(JSON.parse(JSON.stringify(game.world)));const q=game.join('b','B'),drop=game.world.resources.find(n=>n.id==='drop1');q.x=drop.x;q.z=drop.z;q.cutter=true;assert.equal(game.action('b',{type:'gather',id:drop.id}).ok,true);game.world.time+=1;assert.equal(game.action('b',{type:'gather',id:drop.id}).ok,true);assert.equal(q.inventory.ferrite,3);assert.equal(game.action('b',{type:'gather',id:drop.id}).ok,false);assert.equal(game.world.nextDrop,2);});
test('home requires an owned nearby bunk, stays private, survives reload and clears dead vehicle occupancy',()=>{let{game,p,act}=fixture();assert.equal(act({type:'home',id:'bed'}).ok,false);p.x=24;p.z=12;assert.equal(act({type:'home',id:'bed'}).ok,true);assert.equal(p.journey&64,64);assert.equal(game.snapshot('b').players.find(p=>p.id==='a').homeBed,undefined);game=new Game(JSON.parse(JSON.stringify(game.world)));p=game.join('a','A');const q=game.join('b','B');q.x=24;q.z=12;assert.equal(game.action('b',{type:'home',id:'bed'}).ok,false);p.x=40;p.z=40;p.health=0;p.vehicle='v';game.world.vehicles=[{id:'v',type:'scout',x:40,z:40,yaw:0,health:300,battery:100,modules:[],occupants:['a'],inventory:{},owner:'a'}];game.tick(.01);assert.ok(dist(p,{x:24,z:12})<3);assert.equal(p.vehicle,null);assert.deepEqual(game.world.vehicles[0].occupants,[]);game.world.structures.find(s=>s.id==='bed').health=0;assert.deepEqual(respawnPoint(game.world,p),{x:0,z:3});game.world.structures=[];assert.deepEqual(respawnPoint(game.world,p),{x:0,z:3});assert.equal(game.action('a',{type:'home',id:null}).ok,true);assert.equal(p.homeBed,undefined);});
test('home recovery falls back when all candidate exits are obstructed',()=>{const{game,p}=fixture();p.homeBed='bed';game.world.structures.push(...[[0,2],[2,0],[0,-2],[-2,0],[2,2],[-2,-2]].map(([x,z],i)=>({id:'block'+i,type:'cargo',x:24+x,z:12+z,rotation:0,owner:'a'})));assert.deepEqual(respawnPoint(game.world,p),{x:0,z:3});});
test('original sound cues are distinct, short, bounded, and respect world mute',async()=>{const notes=[],levels=[],context={state:'running',currentTime:0,destination:{},createOscillator(){const n={frequency:{setValueAtTime(v){n.startFreq=v;},exponentialRampToValueAtTime(v){n.endFreq=v;}},connect(){},disconnect(){},start(){},stop(){}};notes.push(n);return n;},createGain(){return{gain:{setValueAtTime(v){levels.push(v);},exponentialRampToValueAtTime(){}},connect(){},disconnect(){}};}};const settings=createAudioSettings({getItem:()=>null,setItem(){}}),engine=createAudioEngine({settings,createContext:()=>context});await engine.activate(true);for(const cue of Object.keys(WORLD_CUES)){assert.equal(engine.play('world',cue),true);notes.at(-1).onended();}assert.ok(new Set(notes.map(n=>`${n.startFreq}:${n.endFreq}`)).size>10);assert.ok(levels.every(v=>v<=.28));settings.setCategory('world',0);assert.equal(engine.play('world','gather'),false);assert.ok(Object.values(WORLD_CUES).every(cue=>cue[2]<=.3));});

test('simulation clock catches up delayed frames with bounded collision-safe steps',async()=>{const{advanceSimulation}=await import('../server/simulation-clock.js'),steps=[];advanceSimulation({tick:dt=>steps.push(dt)},.37);assert.ok(Math.abs(steps.reduce((a,b)=>a+b,0)-.37)<1e-9);assert.ok(steps.every(dt=>dt>0&&dt<=.05));steps.length=0;advanceSimulation({tick:dt=>steps.push(dt)},60);assert.ok(Math.abs(steps.reduce((a,b)=>a+b,0)-1)<1e-9);for(const elapsed of[-1,NaN,Infinity])advanceSimulation({tick(){assert.fail('Invalid elapsed time must not advance');}},elapsed);});
