import http from 'node:http';import {randomUUID,createHash} from 'node:crypto';import {WebSocketServer,WebSocket} from 'ws';import {RedisStore,transaction} from './cloud-store.js';import {joinRoom,frameRoom,leaveRoom} from './cloud-room.js';
export function createCloudServer(store){
 const server=http.createServer(async(req,res)=>{res.setHeader('Content-Type','application/json');try{if(!store)throw Error('Persistent world storage is not configured.');await store.read();res.end(JSON.stringify({ok:true,maxPlayers:10,persistence:'redis'}));}catch(e){res.writeHead(503);res.end(JSON.stringify({ok:false,message:e.message}));}});
 const wss=new WebSocketServer({server,maxPayload:4096});const clients=new Map();let actions=[],timer=null,busy=false;
 const send=(ws,msg)=>{if(ws.readyState===WebSocket.OPEN&&ws.bufferedAmount<262144)ws.send(JSON.stringify(msg));};
 async function frame(){if(busy||!clients.size)return;busy=true;const batch=actions;actions=[];const current=[...clients.values()].map(c=>({...c,input:Date.now()-c.lastInputAt<500?c.input:{x:0,z:0}}));try{const {result}=await transaction(store,room=>frameRoom(room,current,batch));for(const c of current){if(!result.state.players.some(p=>p.id===c.id)){c.ws.close(1012,'Session expired');continue;}send(c.ws,{type:'state',state:result.state,lastSaved:new Date().toISOString()});}for(const r of result.results){const a=batch.find(a=>a.key===r.key);if(a)send(a.ws,{type:'result',ok:r.ok,message:r.message});}}catch(e){for(const a of batch)send(a.ws,{type:'result',ok:false,message:'World unavailable; action was not confirmed. Reconnect before retrying.'});for(const c of current)send(c.ws,{type:'notice',message:e.message});}finally{busy=false;}}
 wss.on('connection',ws=>{let c=null,joining=false,count=0;const deadline=setTimeout(()=>{if(!c)ws.close(1008,'Join timeout');},15000);const limiter=setInterval(()=>count=0,1000);
 ws.on('message',async raw=>{if(++count>80)return ws.close(1008,'Too many messages');let m;try{m=JSON.parse(raw);}catch{return;}if(!m||typeof m!=='object')return;
 if(m.type==='join'&&!c&&!joining){joining=true;try{if(!store)throw Error('Persistent world storage is not configured.');if(typeof m.token!=='string'||!/^\w[\w-]{15,79}$/.test(m.token))throw Error('Invalid explorer identity.');const id=createHash('sha256').update(m.token).digest('hex'),session=randomUUID(),name=String(m.name||'Explorer').replace(/[^\p{L}\p{N} _-]/gu,'').slice(0,20)||'Explorer';const {result}=await transaction(store,room=>joinRoom(room,{id,session,name}));if(!result.ok){send(ws,{type:'error',message:result.message});return;}if(ws.readyState!==WebSocket.OPEN){await transaction(store,room=>leaveRoom(room,id,session));return;}c={id,session,ws,lastInputAt:Date.now(),input:{x:0,z:0}};clients.set(session,c);clearTimeout(deadline);send(ws,{type:'welcome',id,state:result.state});if(!timer)timer=setInterval(frame,100);}catch(e){send(ws,{type:'error',message:e.message});}finally{joining=false;}return;}
 if(!c)return;if(m.type==='input'){c.lastInputAt=Date.now();c.input={x:Math.max(-1,Math.min(1,Number(m.x)||0)),z:Math.max(-1,Math.min(1,Number(m.z)||0)),sprint:m.sprint===true};}else if(actions.filter(a=>a.session===c.session).length<8){actions.push({...c,key:randomUUID(),message:m});}
 });
 ws.on('close',()=>{clearTimeout(deadline);clearInterval(limiter);if(c){clients.delete(c.session);actions=actions.filter(a=>a.session!==c.session);transaction(store,room=>leaveRoom(room,c.id,c.session)).catch(()=>{});}if(!clients.size){clearInterval(timer);timer=null;}});ws.on('error',()=>{});
 });
 return server;
}
let store;try{store=new RedisStore();}catch{}
export default createCloudServer(store);
