import {MAX_PLAYERS,DEFAULT_SETTINGS} from '../shared/settings.js';
import {Accounts,cookieToken} from './accounts.js';
import {SERVER_ID} from './catalog.js';
import http from 'node:http';import {randomUUID} from 'node:crypto';import {WebSocketServer,WebSocket} from 'ws';import {RedisStore,transaction} from './cloud-store.js';import {joinRoom,frameRoom,leaveRoom} from './cloud-room.js';import {createSnapshotSession,nextSnapshotPacket} from './snapshot-delta.js';
export function createCloudServer(store){
 const accounts=store?new Accounts(store):null;const server=http.createServer(async(req,res)=>{res.setHeader('Content-Type','application/json');try{if(!store)throw Error('Persistent world storage is not configured.');await store.read();res.end(JSON.stringify({ok:true,maxPlayers:MAX_PLAYERS,persistence:'redis'}));}catch(e){res.writeHead(503);res.end(JSON.stringify({ok:false,message:e.message}));}});
 const wss=new WebSocketServer({server,maxPayload:4096});const clients=new Map();let actions=[],timer=null,busy=false;
 const send=(ws,msg)=>{if(ws.readyState===WebSocket.OPEN&&ws.bufferedAmount<262144)ws.send(JSON.stringify(msg));};
 async function frame(){if(busy||!clients.size)return;busy=true;const batch=actions;actions=[];const current=[...clients.values()].map(c=>({...c,input:Date.now()-c.lastInputAt<500?c.input:null}));try{const {result}=await transaction(store,room=>frameRoom(room,current,batch));for(const c of current){if(!result.state.players.some(p=>p.id===c.id)){c.ws.close(1012,'Session expired');continue;}send(c.ws,nextSnapshotPacket(c.snapshotSession,result.states[c.id],{inputAck:result.inputAcks[c.id]??null,lastSaved:new Date().toISOString()}));}for(const r of result.results){const a=batch.find(a=>a.key===r.key);if(a)send(a.ws,{type:'result',ok:r.ok,message:r.message});}}catch(e){for(const a of batch)send(a.ws,{type:'result',ok:false,message:'World unavailable; action was not confirmed. Reconnect before retrying.'});for(const c of current)send(c.ws,{type:'notice',message:e.message});}finally{busy=false;}}
 wss.on('connection',(ws,req)=>{
 if(req.headers.origin){try{if(new URL(req.headers.origin).host!==req.headers.host){ws.close(1008,'Origin not allowed');return;}}catch{ws.close(1008,'Invalid origin');return;}}let c=null,joining=false,count=0;const revalidate=setInterval(async()=>{if(!c)return;try{if(!await accounts.identity(cookieToken(req),c.id))ws.close(1008,'Account access changed');}catch{ws.close(1008,'Account access changed');}},30000);const deadline=setTimeout(()=>{if(!c)ws.close(1008,'Join timeout');},15000);const limiter=setInterval(()=>count=0,1000);
 ws.on('message',async raw=>{if(++count>80)return ws.close(1008,'Too many messages');let m;try{m=JSON.parse(raw);}catch{return;}if(!m||typeof m!=='object')return;
 if(m.type==='join'&&!c&&!joining){joining=true;try{if(m.server&&m.server!==SERVER_ID)throw Error('Unknown server.');if(!store)throw Error('Persistent world storage is not configured.');const character=await accounts.identity(cookieToken(req),m.character);if(!character)throw Error('Sign in and select one of your characters.');const id=character.id,session=randomUUID(),name=character.name;const {result}=await transaction(store,room=>joinRoom(room,{id,session,name,account:character.account,role:character.role}));if(!result.ok){send(ws,{type:'error',message:result.message});return;}if(ws.readyState!==WebSocket.OPEN){await transaction(store,room=>leaveRoom(room,id,session));return;}c={id,session,ws,lastInputAt:Date.now(),input:{x:0,z:0},snapshotSession:createSnapshotSession(result.state)};clients.set(session,c);clearTimeout(deadline);send(ws,{type:'welcome',id,state:structuredClone(c.snapshotSession.state),revision:0});if(!timer)timer=setInterval(frame,100);}catch(e){send(ws,{type:'error',message:e.message});}finally{joining=false;}return;}
 if(!c)return;if(m.type==='input'){if(!Number.isSafeInteger(m.sequence)||m.sequence<0)return;c.lastInputAt=Date.now();c.input={sequence:m.sequence,x:Math.max(-1,Math.min(1,Number(m.x)||0)),z:Math.max(-1,Math.min(1,Number(m.z)||0)),sprint:m.sprint===true,aimYaw:Number.isFinite(m.aimYaw)?m.aimYaw:0,...([m.vx,m.vy,m.vz].every(Number.isFinite)?{vx:m.vx,vy:m.vy,vz:m.vz}:{})};}else if(actions.filter(a=>a.session===c.session).length<8){actions.push({...c,key:randomUUID(),message:m});}
 });
 ws.on('close',()=>{clearTimeout(deadline);clearInterval(limiter);clearInterval(revalidate);if(c){clients.delete(c.session);actions=actions.filter(a=>a.session!==c.session);transaction(store,room=>leaveRoom(room,c.id,c.session)).catch(()=>{});}if(!clients.size){clearInterval(timer);timer=null;}});ws.on('error',()=>{});
 });
 return server;
}
let store;try{store=new RedisStore();}catch{}
export default createCloudServer(store);
