import {solarProfile,travel,atmosphere,breathable,MONUMENTS,nearbyResources,planetDistance,nearbyWrecks,steering,classifyBiome} from '../shared/planet.js';
import {roomStatus,rooms,stepRooms,airlockCheck,doorSides,roomAt} from '../shared/rooms.js';
import {DEFAULT_SETTINGS} from '../shared/settings.js';
import {dist,RESOURCES,RECIPES,canAfford,pay,itemCount,freeSpace,blocked,nearestOperableDoor} from '../shared/world.js';
import {scryptSync,randomBytes,timingSafeEqual} from 'node:crypto';
import {types as utilTypes} from 'node:util';
const FORBIDDEN_CHARACTER_IDS=new Set(['__proto__','prototype','constructor']);
const BIOME_DISCOVERY_IDS=new Set(['quiet-basin','coral-shelf']);
export const BIOME_DISCOVERY_LIMIT=BIOME_DISCOVERY_IDS.size;
export const CARGO_GRANT_LIMIT=16;
export const VEHICLES={scout:{name:'Scout rover',seats:1,cargo:100,bays:2,speed:6.7,cost:{ferrite:16,copper:4,scrap:6}},rover:{name:'Expedition rover',seats:4,cargo:300,bays:4,speed:6.2,cost:{ferrite:30,copper:8,scrap:12}},crawler:{name:'Transport crawler',seats:10,cargo:800,bays:8,speed:5.3,cost:{ferrite:40,copper:10,scrap:10}}};
export function initExpedition(w){w.planet??=solarProfile(w.seed);w.settings={...DEFAULT_SETTINGS,...w.settings,daySeconds:w.planet.daySeconds,nightSeconds:w.planet.nightSeconds};w.depleted??={};w.vehicles??=[];w.nextVehicle??=1;w.locks??={};w.pinAttempts??={};w.roomAir??={};w.atmosphere??=atmosphere(w.seed);w.audit??=[];for(const p of Object.values(w.players))initPlayer(p);}
function normalizeBiomeDiscoveries(p){const property=Object.getOwnPropertyDescriptor(p,'discoveredBiomes');let normalized=[];if(property&&Object.hasOwn(property,'value')){const value=property.value;if(!utilTypes.isProxy(value)&&Array.isArray(value)&&Object.getPrototypeOf(value)===Array.prototype&&Number.isSafeInteger(value.length)&&value.length<=BIOME_DISCOVERY_LIMIT){const descriptors=Object.getOwnPropertyDescriptors(value),length=descriptors.length,values=[];if(Reflect.ownKeys(descriptors).length===value.length+1&&length&&!length.enumerable&&Object.hasOwn(length,'value')&&length.value===value.length){let valid=true;for(let index=0;index<value.length;index++){const descriptor=descriptors[index];if(!descriptor||!descriptor.enumerable||!Object.hasOwn(descriptor,'value')||typeof descriptor.value!=='string'||!BIOME_DISCOVERY_IDS.has(descriptor.value)){valid=false;break;}values.push(descriptor.value);}if(valid)normalized=[...new Set(values)];}}}Object.defineProperty(p,'discoveredBiomes',{value:normalized,enumerable:true,writable:true,configurable:true});return normalized;}
export function initPlayer(p){for(const key of Object.keys(RESOURCES))p.inventory[key]??=0;p.oxygen??=100;p.water??=100;p.food??=100;p.stamina??=100;p.suit??=true;p.skills??={mining:0,construction:0,combat:0,piloting:0};p.belt??=Array(10).fill(null);p.survey??=[];p.markers??=[];normalizeBiomeDiscoveries(p);p.vehicle??=null;p.sleeping??=false;}
export function resourcesFor(w,p){const generated=nearbyResources(w.seed,p,w.depleted);return [...w.resources.filter(n=>dist(n,p)<320),...generated];}
export function skill(p,key,amount=1){p.skills[key]=Math.min(10000,(p.skills[key]||0)+amount);}
export function cargoGrants(w,lock){const grants=lock?.cargoGrants;if(grants===undefined)return[];if(utilTypes.isProxy(grants)||!Array.isArray(grants)||Object.getPrototypeOf(grants)!==Array.prototype||grants.length>CARGO_GRANT_LIMIT)return null;const descriptors=Object.getOwnPropertyDescriptors(grants),lengthDescriptor=descriptors.length;if(Reflect.ownKeys(descriptors).length!==grants.length+1||!lengthDescriptor||lengthDescriptor.enumerable||!Object.hasOwn(lengthDescriptor,'value'))return null;for(let index=0;index<grants.length;index++){const descriptor=descriptors[index];if(!descriptor||!descriptor.enumerable||!Object.hasOwn(descriptor,'value'))return null;}if(new Set(grants).size!==grants.length||grants.some(target=>typeof target!=='string'||target.length>128||FORBIDDEN_CHARACTER_IDS.has(target)||target===lock.owner||!Object.hasOwn(w.players,target)))return null;return grants;}
export function canAccess(w,p,id){const lock=w.locks[id];if(!lock||lock.owner===p.id)return true;return(Array.isArray(lock.allowed)&&lock.allowed.includes(p.id))||cargoGrants(w,lock)?.includes(p.id)===true;}
export function stepExpedition(game,dt){const w=game.world,all=stepRooms(w,dt),players=[...game.online].map(id=>w.players[id]);for(const p of players){const biome=classifyBiome(p.x,p.z,w.seed).id;if(!p.discoveredBiomes.includes(biome))p.discoveredBiomes.push(biome);if(w.vehicles.length<100)for(const wreck of nearbyWrecks(w.seed,p))if(!w.vehicles.some(v=>v.id===wreck.id))w.vehicles.push(structuredClone(wreck));const moving=steering(game.inputs.get(p.id)||{},p),rate=w.settings.survivalRate,room=roomStatus(w,p,all);if(p.sleeping&&!room.safe)p.sleeping=false;
 p.food=Math.max(0,p.food-dt*.018*rate);p.water=Math.max(0,p.water-dt*.028*rate);const sprint=moving.sprint&&Math.hypot(moving.x,moving.z)>.1&&!p.vehicle;p.stamina=Math.max(0,Math.min(100,p.stamina+dt*(sprint?-12:9)*(p.food>0?1:.4)));
 if(p.suit){p.oxygen=Math.max(0,Math.min(100,p.oxygen+dt*(room.safe?3:-.035*rate)));}else if(!room.safe&&!breathable(w.atmosphere))p.health-=dt*8;
 if(!p.suit&&!room.safe&&w.atmosphere.temperature<0)p.health-=dt*2;if(!p.oxygen&&p.suit)p.health-=dt*5;if(!p.water||!p.food)p.health-=dt*.5;
 if(p.sleeping){p.health=Math.min(100,p.health+dt*2);p.stamina=100;}
 if(p.vehicle){const v=w.vehicles.find(v=>v.id===p.vehicle);if(!v||!v.occupants.includes(p.id)){p.vehicle=null;}else if(v.occupants[0]===p.id&&v.battery>0){const spec=VEHICLES[v.type],load=itemCount(v.inventory)/(spec.cargo+v.modules.filter(m=>m==='cargo').length*100),speed=spec.speed*w.settings.vehicleSpeed*(1+Math.min(.05,Math.sqrt(p.skills.piloting)*.002))/(1+load*.25),next=travel(v,moving.x*speed*dt,moving.z*speed*dt);if(!blocked(w,next.x,next.z)){v.x=next.x;v.z=next.z;if(Math.hypot(moving.x,moving.z)>.1){v.yaw=Math.atan2(moving.x,moving.z);v.battery=Math.max(0,v.battery-dt*.018);skill(p,'piloting',dt*.1);}}}if(v){p.x=v.x;p.z=v.z;if(v.modules.includes('oxygen')&&v.battery>0){p.oxygen=Math.min(100,p.oxygen+dt*.5);v.battery=Math.max(0,v.battery-dt*.002);}}}
 if(Math.floor(w.time)%10===0){const k=`${Math.floor(p.x/500)},${Math.floor(p.z/500)}`;if(!p.survey.includes(k))p.survey.push(k);}
 }
 const night=w.time%(w.settings.daySeconds+w.settings.nightSeconds)>=w.settings.daySeconds;if(night&&players.length&&players.filter(p=>p.sleeping&&w.time-(p.lastDamage||-100)>30).length/players.length>=w.settings.sleepPercent/100){w.time=Math.ceil(w.time/(w.settings.daySeconds+w.settings.nightSeconds))*(w.settings.daySeconds+w.settings.nightSeconds);for(const p of players)p.sleeping=false;}
 for(const v of w.vehicles){v.occupants=v.occupants.filter(id=>game.online.has(id)&&w.players[id]?.vehicle===v.id);}
}
export function expeditionAction(game,p,m){const w=game.world,fail=message=>({ok:false,message}),ok=message=>({ok:true,message});
 if(m.type==='scanAir'){if(p.charge<1)return fail('Suit battery too low.');p.charge--;p.airReading={...w.atmosphere,at:w.time};return ok(`Air tested: ${w.atmosphere.oxygen}% oxygen, ${w.atmosphere.pressure} kPa, ${w.atmosphere.temperature}°C, toxicity ${w.atmosphere.toxicity}.`);}
 if(m.type==='suit'){const safe=roomStatus(w,p).safe||(breathable(w.atmosphere)&&w.atmosphere.temperature>=0);if(p.suit&&!safe)return fail('Unsafe atmosphere or temperature. Find a habitable room.');p.suit=!p.suit;p.sleeping=false;return ok(p.suit?'Suit equipped.':'Suit removed.');}
 if(m.type==='drink'){if(!p.inventory.water)return fail('Fill a water canister at an ice processor.');if(p.water>=95)return fail('You are already hydrated.');p.inventory.water--;p.water=Math.min(100,p.water+40);return ok('Water consumed.');}
 if(m.type==='belt'){if(!Number.isInteger(m.slot)||m.slot<0||m.slot>9||!['cutter','flashlight','ration','water','rifle','repair',null].includes(m.item))return fail('Invalid belt slot.');if(m.item&&!p.inventory[m.item]&&!p[m.item]&&!(m.item==='flashlight'&&p.flashlightOwned))return fail('Carry or equip that item first.');p.belt[m.slot]=m.item;return ok('Belt updated.');}
 if(m.type==='marker'){if(!Number.isFinite(m.x)||!Number.isFinite(m.z)||typeof m.name!=='string'||m.name.length>32||p.markers.length>=30)return fail('Invalid marker or marker limit reached.');p.markers.push({x:m.x,z:m.z,name:m.name});return ok('Map marker saved.');}
 if(m.type==='door'){const s=nearestOperableDoor(w,p);if(!s||s.id!==m.id)return fail('Move closer to the door.');if(s.cycleUntil)return fail('Airlock cycle in progress.');if(s.type==='airlock'&&!s.open){const check=airlockCheck(w,s);if(check.error)return fail(check.error);if(!roomStatus(w,doorSides(s)[0]).safe||!roomStatus(w,doorSides(s)[1]).safe)return fail('Cycle the chamber before opening the inner door.');}s.open=!s.open;return ok(s.open?'Door open.':'Door sealed.');}
 if(m.type==='cycle'){const s=w.structures.find(s=>s.id===m.id&&s.type==='airlock');if(!s||dist(p,s)>4)return fail('Move closer to the airlock.');if(s.open)return fail('Close the inner door first.');const check=airlockCheck(w,s);if(check.error)return fail(check.error);s.cycleUntil=w.time+5;return ok('Airlock cycling. Keep both doors closed.');}
 if(m.type==='fuel'){const s=w.structures.find(s=>s.id===m.id&&s.type==='lifeSupport');if(!s||dist(p,s)>3||!p.inventory.crystal)return fail('Bring a flux crystal to a life-support unit.');if(s.power>=95)return fail('Power reserve is full.');p.inventory.crystal--;s.power=Math.min(100,(s.power||0)+40);return ok('Life-support reserve charged.');}
 if(m.type==='sleep'){const bed=w.structures.find(s=>s.type==='bed'&&dist(s,p)<3);if(!bed||!roomStatus(w,p).safe||p.suit)return fail('Use a bed in a habitable shelter with your suit removed.');if(w.time-(p.lastDamage||-100)<30)return fail('Cannot sleep during combat.');p.sleeping=!p.sleeping;return ok(p.sleeping?'Resting. All required players must sleep to skip night.':'Awake.');}
 if(m.type==='ice'){const s=w.structures.find(s=>s.id===m.id&&s.type==='iceProcessor');if(!s||dist(p,s)>3)return fail('Move closer to the ice processor.');s.water??=0;if(m.mode==='melt'){if(!p.inventory.ice||p.charge<2||s.water>=100)return fail('Needs ice, 2 suit power and tank space.');p.inventory.ice--;p.charge-=2;s.water+=10;return ok('Ice converted into 10 water units.');}if(s.water<10||freeSpace(p.inventory)<1)return fail('Needs 10 water units and backpack space.');s.water-=10;p.inventory.water++;return ok('Water canister filled.');}
 if(m.type==='garden'){const s=w.structures.find(s=>s.id===m.id&&s.type==='garden');if(!s||dist(p,s)>3)return fail('Move closer to the hydroponic bed.');if(s.readyAt&&w.time>=s.readyAt){if(freeSpace(p.inventory)<3)return fail('Make space for the harvest.');p.inventory.fiber+=2;p.inventory.ration++;delete s.readyAt;return ok('Harvested fiber and food.');}if(s.readyAt)return fail('Plants are growing.');if(!p.inventory.water||!p.inventory.fiber||!roomStatus(w,s).safe)return fail('Planting needs water, fiber and a habitable room.');p.inventory.water--;p.inventory.fiber--;s.readyAt=w.time+180;return ok('Hydroponics planted.');}
 if(m.type==='lock'){const s=w.structures.find(s=>s.id===m.id&&s.type==='cargo');if(!s||dist(p,s)>3)return fail('Move closer to the locker.');if(!/^\d{4,8}$/.test(m.pin||''))return fail('Use a 4–8 digit PIN.');if(m.mode==='set'){if(s.owner!==p.id)return fail('Only the builder can set the PIN.');const salt=randomBytes(16).toString('hex');w.locks[s.id]={owner:p.id,salt,digest:scryptSync(m.pin,salt,32).toString('hex'),allowed:[]};return ok('PIN changed. Previous access revoked.');}const l=w.locks[s.id];if(!l)return ok('Locker has no PIN set.');const k=p.id+':'+s.id,attempt=w.pinAttempts[k]||{count:0,until:0};if(attempt.until>w.time)return fail('Keypad locked. Wait one minute.');if(!timingSafeEqual(scryptSync(m.pin,l.salt,32),Buffer.from(l.digest,'hex'))){attempt.count++;if(attempt.count>=5){attempt.until=w.time+60;attempt.count=0;}w.pinAttempts[k]=attempt;return fail('Incorrect PIN.');}if(!l.allowed.includes(p.id))l.allowed.push(p.id);delete w.pinAttempts[k];return ok('Locker unlocked for this character.');}
 if(m.type==='vehicleRepair'){const v=w.vehicles.find(v=>v.id===m.id);if(!v||dist(v,p)>5||!p.repair||p.inventory.ferrite<8||p.inventory.copper<3)return fail('Needs a repair tool, 8 ferrite and 3 conductive ore within 5 m.');if(v.health>=300)return fail('Vehicle is already repaired.');p.inventory.ferrite-=8;p.inventory.copper-=3;v.health=Math.min(300,v.health+150);if(!v.owner){v.owner=p.id;v.battery=20;}return ok('Vehicle repaired.');}
 if(m.type==='vehicleBuild'){const spec=VEHICLES[m.vehicle];if(!spec)return fail('Choose a rover class.');if(!Object.entries(spec.cost).every(([k,n])=>p.inventory[k]>=n))return fail('Not enough vehicle materials.');if(w.vehicles.length>=100)return fail('Server vehicle limit reached.');const pos=travel(p,4,0);if(blocked(w,pos.x,pos.z)||w.vehicles.some(v=>dist(v,pos)<5))return fail('Clear more space beside you.');for(const[k,n]of Object.entries(spec.cost))p.inventory[k]-=n;w.vehicles.push({id:'v'+w.nextVehicle++,type:m.vehicle,...pos,yaw:0,health:300,battery:100,modules:[],occupants:[],inventory:{},owner:p.id});return ok(spec.name+' constructed.');}
 if(m.type==='vehicle'){if(p.vehicle){const v=w.vehicles.find(v=>v.id===p.vehicle),pos=v&&travel(v,3,0);if(v&&blocked(w,pos.x,pos.z))return fail('Exit blocked.');if(v){v.occupants=v.occupants.filter(id=>id!==p.id);p.x=pos.x;p.z=pos.z;}p.vehicle=null;return ok('Exited vehicle.');}const v=w.vehicles.find(v=>v.id===m.id);if(!v||dist(v,p)>5||v.health<=0)return fail('Move closer to a working vehicle.');if(v.occupants.length>=VEHICLES[v.type].seats)return fail('All seats are occupied.');v.occupants.push(p.id);p.vehicle=v.id;p.sleeping=false;return ok(v.occupants.length===1?'Driving. Movement controls steer the rover.':'Passenger seat occupied.');}
 if(m.type==='vehicleModule'){const v=w.vehicles.find(v=>v.id===m.id);if(!v||dist(p,v)>5||!['battery','cargo','oxygen'].includes(m.module))return fail('Move closer and choose a module.');if(v.modules.length>=VEHICLES[v.type].bays)return fail('Expansion bays full.');if(p.inventory.ferrite<4||p.inventory.copper<2)return fail('A module needs 4 ferrite and 2 conductive ore.');p.inventory.ferrite-=4;p.inventory.copper-=2;v.modules.push(m.module);if(m.module==='battery')v.battery+=100;return ok('Expansion module installed.');}
 if(m.type==='vehicleCharge'){const v=w.vehicles.find(v=>v.id===m.id);if(!v||dist(v,p)>5||!p.inventory.crystal)return fail('Bring a flux crystal to a rover.');p.inventory.crystal--;v.battery=Math.min(100+v.modules.filter(x=>x==='battery').length*100,v.battery+40);return ok('Rover battery charged.');}
 if(m.type==='vehicleCargo'){const v=w.vehicles.find(v=>v.id===m.id);if(!v||dist(v,p)>5||!Object.hasOwn(RESOURCES,m.item)||!['deposit','withdraw'].includes(m.direction)||!Number.isInteger(m.amount)||m.amount<1||m.amount>1000)return fail('Invalid cargo transfer.');const from=m.direction==='deposit'?p.inventory:v.inventory,to=m.direction==='deposit'?v.inventory:p.inventory,capacity=m.direction==='deposit'?VEHICLES[v.type].cargo+v.modules.filter(x=>x==='cargo').length*100:60;if((from[m.item]||0)<m.amount||itemCount(to)+m.amount>capacity)return fail('Not enough items or destination full.');from[m.item]-=m.amount;to[m.item]=(to[m.item]||0)+m.amount;return ok('Vehicle cargo transferred.');}
 if(m.type==='salvage'){const monument=MONUMENTS.find(s=>s.id===m.id);if(!monument||dist(p,monument)>8)return fail('Move closer to the monument console.');p.discoveries??=[];if(p.discoveries.includes(monument.id))return fail('You already recovered this archive.');const loot=monument.kind==='cryowell'?{ice:4,copper:2}:monument.kind==='graveyard'?{scrap:4,copper:2}:{crystal:2,silica:4};if(itemCount(loot)>freeSpace(p.inventory))return fail('Make room for six recovered items.');for(const[k,n]of Object.entries(loot))p.inventory[k]+=n;p.discoveries.push(monument.id);return ok(monument.name+' archive recovered.');}
 return null;
}
