import {buildingCell,cellKey,gridPoint,withinTile} from './build-grid.js';
// Airtightness follows connected 3m floor/roof cells. Missing surfaces lead outside.
const dirs=[[0,-1],[1,0],[0,1],[-1,0]],key=(x,z,site=null)=>cellKey({x,z,site});
export const cell=buildingCell;
export function edgeKey(s){const p=cell(s),d=dirs[s.rotation||0],a=key(p.x,p.z,p.site),b=key(p.x+d[0],p.z+d[1],p.site);return[a,b].sort().join('|');}
export function rooms(world){const cells=new Map(),edges=new Map();for(const s of world.structures){const c=cell(s),k=key(c.x,c.z,c.site);if(['floor','roof'].includes(s.type)){const item=cells.get(k)||{...c,floor:false,roof:false};item[s.type]=true;cells.set(k,item);}if(['wall','perimeter','door','airlock'].includes(s.type)){const k=edgeKey(s);if(!s.open)edges.set(k,s);}}
 const seen=new Set(),out=[];for(const[k,start]of cells){if(seen.has(k)||!start.floor)continue;const todo=[start],list=[],doors=new Set();let sealed=true;while(todo.length){const c=todo.pop(),id=key(c.x,c.z,c.site);if(seen.has(id))continue;seen.add(id);list.push(id);if(!c.floor||!c.roof)sealed=false;if(list.length>1024){sealed=false;break;}for(let r=0;r<4;r++){const d=dirs[r],nk=key(c.x+d[0],c.z+d[1],c.site),edge=edges.get([id,nk].sort().join('|'));if(edge){if(['door','airlock'].includes(edge.type))doors.add(edge.id);continue;}const n=cells.get(nk);if(!n?.floor)sealed=false;else if(!seen.has(nk))todo.push(n);}}
 out.push({id:list.slice().sort()[0],cells:list,sealed,doors:[...doors]});}return out;}
export function roomAt(world,p,all=rooms(world)){const floor=world.structures.find(s=>s.type==='floor'&&withinTile(s,p));if(!floor)return null;const c=cell(floor),k=key(c.x,c.z,c.site);return all.find(r=>r.cells.includes(k))||null;}
export function roomStatus(world,p,all){const room=roomAt(world,p,all);if(!room)return{sealed:false,safe:false,pressure:0,oxygen:0,temperature:-40};const samples=room.cells.map(k=>world.roomAir?.[k]||0),pressure=samples.reduce((a,b)=>a+b,0)/samples.length;return{...room,pressure,oxygen:pressure*.21,temperature:pressure>=80?18:-30,safe:room.sealed&&pressure>=80};}
export function doorSides(s){const c=cell(s),d=dirs[s.rotation||0];return c.site?[gridPoint(c.site,c.x,c.z,0),gridPoint(c.site,c.x+d[0],c.z+d[1],0)]:[{x:c.x*3,z:c.z*3},{x:(c.x+d[0])*3,z:(c.z+d[1])*3}];}
export function airlockCheck(world,door){const all=rooms(world),[a,b]=doorSides(door).map(p=>roomAt(world,p,all));if(!a?.sealed||!b?.sealed||a.id===b.id)return{error:'Both sides need separate sealed rooms. Close all doors and repair gaps.'};const chamber=a.cells.length<=b.cells.length?a:b,base=chamber===a?b:a;if(chamber.cells.length>9)return{error:'Use a chamber of at most nine floor tiles.'};const outer=world.structures.find(s=>s.type==='door'&&chamber.doors.includes(s.id)&&doorSides(s).some(p=>!roomAt(world,p,all)));if(!outer)return{error:'The chamber needs an outer sealed door leading outside.'};const support=world.structures.find(s=>s.type==='lifeSupport'&&roomAt(world,s,all)?.id===base.id&&s.power>0);if(!support)return{error:'The base room needs a powered life-support unit.'};return{chamber,base,support,outer};}
export function stepRooms(world,dt){world.roomAir??={};const all=rooms(world);for(const r of all){const support=world.structures.find(s=>s.type==='lifeSupport'&&s.power>0&&roomAt(world,s,all)?.id===r.id);const average=r.cells.reduce((n,k)=>n+(world.roomAir[k]||0),0)/r.cells.length;const pressure=Math.max(0,Math.min(100,average+dt*(r.sealed?(support?10:0):-45)));for(const k of r.cells)world.roomAir[k]=pressure;if(support)support.power=Math.max(0,support.power-dt*.03*r.cells.length);}
 for(const door of world.structures.filter(s=>s.type==='airlock'&&s.cycleUntil)){if(world.time>=door.cycleUntil){const check=airlockCheck(world,door);if(!check.error){for(const k of check.chamber.cells)world.roomAir[k]=100;check.support.power=Math.max(0,check.support.power-2);}delete door.cycleUntil;}}return all;}
